### ISSUE TITLE
Option to remove "Watch <streamer>'s past broadcast" box

### ISSUE THREAD

**Issue by DJBrazzy** [night/BetterTTV#1030]
This banner usually appears when streams aren't online, but regularly show up even when the streamer is online. Beyond that issue, I don't think it's used that much, it pushes the stream window further down the page and is generally just a nuisance. Assuming that I'm not the only one that thinks this, it should be relatively easy to make the change, as it's just toggling a div's visibility.
Thanks!

**Comment by night** [comment]
The only time I've seen the box show up when a stream is live is if the streamer is having connectivity problems. I've only seen it rarely and it doesn't seem like a major issue to me. There were a bunch of issues when they first launched this feature, but most of them were sorted out quickly. I think the feature adds a lot of value to broadcaster VoDs (which don't get a lot of traffic since videos are a separate page from the channel page and the video player only displays the offline channel image).
