### ISSUE TITLE
 Suggestions

### ISSUE THREAD

**Issue by ghost** [night/betterttv#110]
If you guys made follow button blue on channel page, why not make it blue in all pages? (profile page, game page, host page, Viewer List when you click on name)

The 'Edit' button in the channel page supposed to be white instead of pink and I think that pencil shadow should be removed (http://i.imgur.com/F5ew1CG.png)

In the Dashboard that white box supposed to be dark with white text or somethin (http://i.imgur.com/GtcrdQQ.png)

In CS:GO and twitch.tv/directory/all pages on the dark theme there is small arrow that is not visible (http://i.imgur.com/y8ynYtK.png ; The arrow should be white  http://i.imgur.com/BfPfsGB.png)
(In all channel pages  http://i.imgur.com/iPFoC2x.png ; The arrow should be white http://i.imgur.com/xUZzvOp.png)

Links are in purple colour when in theathre mode, they should be white like without theathre mode. (In theathre mode [http://i.imgur.com/O8IvSoa.png] ; Without, how it should look like [http://i.imgur.com/wQL8CYC.png])

Viewer List nicknames is purple, they should be white like without theathre mode. (In theathre mode [http://i.imgur.com/uBwAWsy.png] ; Without, how it should look like [http://i.imgur.com/08TSStG.png])
Also when you shrink viewer list in theathre mode it lefts left and right corners with some blue colour (In theathre mode [http://i.imgur.com/vB6V0Vr.png] ; Without, how it should look like [http://i.imgur.com/R6S9Nni.png])

**Comment by Sleekness** [comment]
In the last issue I was trying to say that when you are in Theather Mode, you click on Viewer List button, click on 'Shrink' button in upper right (http://i.imgur.com/yKb5u0M.png) then the Viewer List box has blue corners from the Twitch's dark chat theme (http://i.imgur.com/bUF8KZN.png). Those corners should be removed and it should look like this (When you are not in Theather Mode http://i.imgur.com/r9LpWyJ.png). And also the words 'Viewer List' at the top should be white instead of the very light purple when you are in Theather Mode

**Comment by teak** [comment]
I have fixed the Viewer List...
