### ISSUE TITLE
Can't change/save setting

### ISSUE THREAD

**Issue by Maquata** [night/BetterTTV#1115]
Whenever I open the BTTV settings and try to change them, nothing happens. For example if I try to turn on DarkenTTV by clicking On, it's still white, and when I refresh the page and open the settings again, everything I previously turned on is off again.
This happened recently and I think it might be a problem with my browser but I really have no idea what caused it and how to fix it. My Chrome cookie settings are set to _Allow local data to be set (recommended)_.
Edit: Some of the settings that I used before this problem occurred are still on, although they are set to off every time I open my settings, like BTTV emotes and clean sidebar.

**Comment by night** [comment]
I am not able to replicate any issues toggling settings. Try clearing your cookies and cache to see if that helps your issue. If problems persist, disable any other Twitch add-ons that might conflict with ours. In addition, since Twitch added the new friends list feature we no longer have a settings button in the left sidebar. You can only access BetterTTV settings from within the chat settings for the time being.
