### ISSUE TITLE
Allow Turbo-Badges to be Turned Off

### ISSUE THREAD

**Issue by Codonbyte** [night/BetterTTV#1135]
Tell me this isn't distracting: 

![too many badges](https://cloud.githubusercontent.com/assets/11092687/15135953/6fe591a8-164a-11e6-9673-7fb3dafd7553.png)

Obviously the above image shows an extreme case, but the much more common 3-badge scenario is also annoying.

![3 still too much](https://cloud.githubusercontent.com/assets/11092687/15135969/bffd4f1e-164a-11e6-83ae-8fccbce6b80b.png)

I see no reason why turbo badges should be so salient. The fact that somebody is paying twitch $8/month is completely irrelevant to me. I would love to have the ability to turn off turbo badges completely, as I find them distracting. Subscriber badges too.

**Comment by Slikrick** [comment]
if all you care about is the transparency of the image/background there is an option to enable that called "alpha chat badges" for the default badges you see around twitch including turbo. I personally don't find badges distracting though.

**Comment by Codonbyte** [comment]
No I just want to remove turbo-badges and sub badges completely, as I find them distracting. Especially when they stack up with other badges, as illustrated by the above images. I want to keep mod badges though. Alpha chat badges doesn't help, as they still take up just as much space.

**Comment by EhsanKia** [comment]
As you can imagine, Twitch wouldn't be happy with a feature like that, since we're messing with a "perk" that people are paying money for.

But if you grab the Stylish extension for Chrome or Firefox, which let's you inject custom CSS into the page, it's just one line to achieve what you need.

`.turbo.badge { display: none; }`

and

`.subscriber.badge { display: none; }`

**Comment by Codonbyte** [comment]
Oh wow, I did not know that plug-in existed. Thank you so much! I didn't think I'd get this resolved so quickly! Just added the filters and they work perfectly!

Just out of curiosity, if you were to implement this feature for BetterTTV, could twitch actually do anything about it? I mean I'm sure they're unhappy about adblock but they haven't been able to do anything about it. 

Also I doubt most people are paying for turbo or channel subscriptions just for the badge, so I don't think BetterTTV would be hurting the streaming community by having this feature.

**Comment by voloshink** [comment]
we'd rather not "what are you going to do about it" twitch. We'd like to maintain a good relationship.

**Comment by night** [comment]
major 🔑 alert: don't ever bite a hand that feeds you.. they can take away the food as quickly as they fed you it

(to clear up confusion, Twitch does not financially sponsor us but they play a big role in ensuring we remain operational on their constantly-changing infrastructure.. which they don't have to do [who remembers when we used to be break constantly, because I do])
