### ISSUE TITLE
frankerfacez and bttv intergration

### ISSUE THREAD

**Issue by ntpblack** [night/BetterTTV#1184]
frankerfacez is very respectful towards bttv and I would really wish if you guys enabled frankerfacez auto emote completion with tab to make typing emotes with keyboard auto complete ffz emotes and make everyones life easier.

**Comment by night** [comment]
Since FrankerFaceZ has typically integrated into BetterTTV (not vice versa), I'm not sure of how they currently integrate. If their emotes do not autocomplete, then they would also not show in our emote menu. Both of those issues sound like bugs in their integration, so you may want to report them to the FrankerFaceZ developers instead.
