### ISSUE TITLE
"View all rooms" overlaps the settings buttons

### ISSUE THREAD

**Issue by NBruderman** [night/BetterTTV#1303]
![untitled](https://cloud.githubusercontent.com/assets/6445601/16272579/f37d48b6-38a6-11e6-875d-53ab96a066fd.png)

**Comment by EhsanKia** [comment]
I think the fix for this should fully cover everything down there. Showing the settings button also means you're showing the "chat" button, but it doesn't really makes sense to chat in this state. You should choose what chat room you want in order to get back to chatting and accessing your settings.

**Comment by NBruderman** [comment]
I think the settings button can be still relevant in that case, however, you can take it to any direction you want :)

**Comment by EhsanKia** [comment]
What would be the reason to "stay" on this state rather than picking a room? And what setting would you want to change while in this state?

**Comment by dakillerclown87** [comment]
I think what hes saying is that the settings button should to be on top of them just in case. but hide everything else.
