### ISSUE TITLE
Disable new highlighted resubs/subs

### ISSUE THREAD

**Issue by nuxt** [night/BetterTTV#1335]
It seems twitch now highlights resubs / sub messages in chat in purple because of the new message system, that wasn't there 2days ago.

Just like bits, it's annoying and just distracts because it is highlighted, possible to have a feature to disable this?

![1](https://cloud.githubusercontent.com/assets/3001412/16528065/465e6e7c-3fb2-11e6-859b-3b985c138dd3.jpg)

Thanks!

**Comment by nuxt** [comment]
In fact while I'm here on this subject, is it possible to remove the resub/sub messages completely? Obviously an optional feature again.

1. Bots also post when someone subs/resubs
2. It also shows up on streams as an overlay

So all in all if I'm in liriks channel for example, I see 3 or 4 messages PER sub/resub depending if they enter a message or not. (2/3 in chat and 1 as stream overlay)

**Comment by EhsanKia** [comment]
This was added intentionally, and it's to match changes by default Twitch which we thought were good.

I personally am against removing the highlight. These people are paying 5$ and all they get is a line in a chat. I don't think it's unreasonable to have a slight highlight on that line.

If you really really want it gone, you can always get Stylish and put a custom rule for those lines. Now that we tag them with a custom class, it's easier than ever to do it yourself. But as whole feature, I don't think this is worth clogging the settings menu with.

**Comment by nuxt** [comment]
My only annoyance with it, is that it's highlighted really, I'm not bothered about the actual message being shown or not, merely a suggestion for it to be toggled on or off.

I use VLC to watch streams and just use a pop out chat so no clue on what CSS I have to change to stop it from highlighting, can you point me in the right direction of what I'd need to do to disable it being highlighted, if possible? If not then thanks anyway.

Cheers.

**Comment by EhsanKia** [comment]
BTTV is about making Twitch better but there are a other factors to consider. For example, hiding Turbo badges would not be nice, because people pay money to get that badge, and BTTV would basically be nullifying that. I think my argument with resub messages was in the same vein. There's a reason why twitch puts that message in chat, it's to celebrate an occasion. Not for it to go unnoticed in the sea of messages.

Second off, it's a fine line between making users life easiers and keeping the extension easy to use. It's something people don't realize, but if we added a setting for every single tiny tweak people want, the extension would quicky get bloated and run into a thing called "Feature Creep", where it becomes too difficult to use and configure as there's a lot of small very low impact features.

So yes, in a perfect word, websites would be configured exactly how we each want them to be, but in the real world, we need to make hard decisions like this to decide which features are worth including and add more bloat than utility. 

But that's where extensions like Stylish come in, where you can hack little changes like this yourself very easily! For the CSS, you can simply use `.chat-lines .notice {display: none;}` to hide notice messages.

**Comment by nuxt** [comment]
Thanks for the custom CSS, works a treat :)
