### ISSUE TITLE
feature request- arrangable global emotes

### ISSUE THREAD

**Issue by whywhy87** [night/BetterTTV#1338]
Hi!  -Make it so we can arrange global emotes (and maybe subbed emotes for larger channels too); so we can put the ones we like to use the most together near the top. I hate looking through the list finding one, usually when I chat, it's to say something funny (ish) so timing is important, especially w/ everyone having different delays, so the quicker the better;  sometimes I can't find the one I want until like 10-15 seconds after I thought of it.  I don't like memorizing the word form for all of them.
  -So maybe like a click and drag thing, or if necessary a 'switch' that changes it to "arrange mode" to make it easier.

   -Also, it would be cool if you added the BTTV emotes (or at least, the trending ones) to the regular global emote list, so they are just clickable... feelsbadman :)

  -or an easy way to set up hotkeys/key binds for them would be cool too.

  -also make it so you can add bttv emotes to your own global emote list.

**Comment by whywhy87** [comment]
ooooooo... one off from comment 1337... feelsbadman

**Comment by Slikrick** [comment]
Are you referring to twtich's emote menu? Because we try not to touch that, we have our own emote menu that you can enable that supports BetterTTV emotes, twitch sub emotes, twitch global/turbo emotes, and you can favorite emotes you use often, and they are just clickable. So it does most of the things you want.

![emote_menu](https://cloud.githubusercontent.com/assets/7969393/16536951/3b135658-3fc7-11e6-8647-34915a601673.png)

You can favorite by selecting the cogwheel while its opened and starring the ones you use most often.

**Comment by whywhy87** [comment]
(failfish) - i had it enabled but never noticed the second icon below until you said that,  welp, rip request, thnx!
