### ISSUE TITLE
html5 player

### ISSUE THREAD

**Issue by JimZiii** [night/BetterTTV#1438]
there's still a lot of people who don't have the option to use html5 natively, i've been able to swap out the embedded player after the old one already loaded with a greasemonkey script but i'd rather have the option through bttv.
twitch has been really choppy and laggy (i'm not talking about buffering) when i'm using firefox, streams work just fine in chrome, and still it took me ages to find this greasemonkey script so i actually think that the option to force html5 over flash in bttv would help a lot of people while we're waiting for them to roll it out to everyone.

**Comment by Brottweiler** [comment]
Isn't the HTML5 player default now? It seems to be for me.

**Comment by JimZiii** [comment]
since all streams have been choppy and laggy until i run the html5 script i assume its not.
i just tried to deactivate the html5 script and it went right back to being choppy and stuttering

**Comment by EhsanKia** [comment]
There's a lot of misinformation here.

1. What @Brottweiler is referring to is the player itself. That has been HTML5 since October, but the actual backend that decodes the video is still flash.

2. The html5 decoder that @JimZiii is getting with the userscript is the same one provided by `player.twitch.tv` using the `&html5=true` parameter. That player though is actually old and outdated.

3. There is a brand new html5 decoder that came out **for turbo users only** a few weeks back. They are going to be [rolling it out to more and more users gradually](https://blog.twitch.tv/html5-beta-access-expands-99554ea982e4#.8wi3inq99).

So while we may be able to do something, it looks like Twitch will be releasing this in the very near future anyways, and you also get it if you're turbo right now.
