### ISSUE TITLE
Filter Emote Spam Messages

### ISSUE THREAD

**Issue by NoStereo** [night/betterttv#144]
As the title says, I would like to be able to filter out all this muck. I like emotes, and removing all emotes would ruin the twitch experience a little too much, but I would like to be able to read the chat...

**Comment by arex1337** [comment]
Huge supporter of this.

**Comment by Fogest** [comment]
I'm going to chime in since this issue has not really had activity. I'd love to be able to not see chat messages that are exclusively emotes. If they have some normal text then show them, but if the chat message is purely emotes hide it. There could also be an option to just strip messages of emotes as another option. 

Some streamers chat members love their emotes and half the chat can end up being a mess of emote filth.

**Comment by EhsanKia** [comment]
@night does /localascii only get rid of emojis? I thought it got rid of emotes too in chat but I don't see it. Maybe we should change it so it does that, and also drop the message if it's only emotes.

**Comment by night** [comment]
localscii allows emotes and blocks unicode.. though i guess we might want to extend it to prevent emotes.

**Comment by zeimus** [comment]
Anyway you could have this feature cut down on spam... so if someone is spamming a long repetitive block of text it will filter it down and only display unique text once per message?

**Comment by EhsanKia** [comment]
Will considering implementing this in BTTV in the near future: https://github.com/night/BetterTTV/issues/1922

**Comment by Aloisius** [comment]
Added pull request #3649 that will filter out emote-only messages. Really cuts down on the emote spam.
