### ISSUE TITLE
API or moderator access to shared emotes

### ISSUE THREAD

**Issue by gempir** [night/BetterTTV#1467]
Several streamers are annoyed because their viewers constantly find new and good BetterTTV emotes but with the limit of 25/10 it's hard to add the best emotes and more importantly keep track of which emotes are added and which aren't used as much.
The managing is cumbersome sometimes and with many good emotes a little annoying.

My two suggestions:
- Allow your moderators (or add managers) to manage your shared emotes on your channel
- Offer an API to manage the emotes so a bot or someone could manually manage shared emotes

This could enable a lot of cool things like maybe make an emote themed day like the pepe day where every bttv emote is a variation of rare pepe.

**Comment by night** [comment]
We have no plans to offer moderator or shared access to accounts at this time, sorry. The authentication system is not sophisticated enough to support that use case, and due to the amount of caching we employ it isn't an easy fix.

We are able to grant API access, however, upon request. If you are a streamer who needs access, reach out via our [contact form](https://nightdev.com/contact) and explain how the API will be used and if we think it's appropriate use we will grant an access token for your channel.

**Comment by Civrock1** [comment]
@night 
Is this still something that is not feasible? I'd love to be able to help out on the channel(s) I moderate and keep the BTTV emotes etc up to date, without requiring full account access (which is not feasible for various reasons). 

Thanks! :)

**Comment by nevmerzhitsky** [comment]
> We have no plans to offer moderator or shared access to accounts at this time, sorry. The authentication system is not sophisticated enough to support that use case, and due to the amount of caching we employ it isn't an easy fix.

Sounds very terrible in 2016 year even. And don't have the feature in 2019 is like just a crap, sorry.

**Comment by night** [comment]
Please refer to this other open feature request: https://github.com/night/BetterTTV/issues/3114 

This is something we are working on adding in the near future.
