### ISSUE TITLE
Localized Display Names bug 

### ISSUE THREAD

**Issue by nigmaCoded** [night/BetterTTV#1471]
Bttv right now hides the original name if you use the "Localized Display Names" feature, will this be patched next update?
Also maybe add an option to only show one or the other name?

**Comment by night** [comment]
I don't think we're going to support showing original names apart from in moderator cards. They take up too much space and look horrid next to display names.

**Comment by HoratioSanchez** [comment]
This would be cool if it was optional. Thousands of people have been localizing their names to avoid moderation or cause confusion.

**Comment by zombiexm** [comment]
"We think this looks bad so we are not going to let our users make the choice" is all I read.

**Comment by jdmanring** [comment]
I don't mean to offend you, but you don't stream much do you night?  By choosing to hide the ROMANIZED version of names because you think it looks bad you are making it much harder on streamers that cannot read Korean, Chinese, or Japanese.  I have no idea what to call people sometimes when they come into the channel.  To find out that default Twitch actually has the name I can read displayed and that it was hidden because of BTTV's author thinking they look bad is very disheartening.  I love BTTV and the features of it, but this alone is enough to make me seriously struggle with continuing to use it.

I am begging you to reconsider your decisions to refuse to give us the option to display the non-localized name.  Otherwise I am on the search for something else that will darken my screen on the Dashboard so as not to reflect off of my glasses when I am streaming.

**Comment by EhsanKia** [comment]
I do agree that showing both is awesome, but I think there should at least be an option to swap the two (username in chat, localized in modcard). As mentioned above, for streamers it's not really possible to keep clicking on modcards for every localized user.

**Comment by HoratioSanchez** [comment]
Please make it an option. I know you've mentioned it you don't like it for personal tastes, but it would just be nice to have it as an option. Clicking on the modcards or individually renaming people is a pain. We have silly options like being able to change buttons from purple to blue, so why not this?

**Comment by EhsanKia** [comment]
Feature added under "Disable Localized Names"
