### ISSUE TITLE
Feature request: highlighting select users

### ISSUE THREAD

**Issue by forbidinjustice** [night/BetterTTV#1673]
As a moderator in a few fairly large channels, a couple changes would be useful.

1)  The ability to right click and temporarily 'tag' the user so that every chat they make becomes highlighted in the feed.  Sometimes I see a questionable chat and I'm not sure if they're going to start trolling, so "tagging" all their chats will be helpful so I remember which users to be on notice for.  I realise right-click will underline the instances of the username, but it of course disappears when I left-click away.

2)  The right-click "ban/purge" meter isn't very helpful or intuitive.  It could be better designed, perhaps snapping to preset values.  It's so "fine" that it's difficult to move my mouse down and select 30 minutes, for example.  I doubt anyone needs to time someone out for exactly 47 minutes.  The space could be utilised for more useful functions.

**Comment by night** [comment]
I don't see the use case for flagging potential users, unfortunately. It sounds like you're trying to profile users, when in reality you're only going to hit them with a timeout when they actually break a rule.

You are welcome to submit another issue (this is why we do not like combined issues) for the ban/purge issue, since that sounds like something we should fix.
