### ISSUE TITLE
A bunch of my messages went up to the top and out of chronological order

### ISSUE THREAD

**Issue by Biokinetica** [night/BetterTTV#1690]
I tried disabling and re-enabling the extension, and it was BetterTTV that was responsible. I'm not sure which setting might cause this, but I can't use this extension if it's going to throw my chat responses in random places.

[Screenshot](http://imgur.com/a/bZMFL)

**Comment by night** [comment]
On page load we load chat history, and it's possible for messages to be out of order on load due to race conditions that cannot be fixed at this time, sorry. Any messages sent after load are always sent in the proper order, so I don't know what you're going on about with "if it's going to throw my chat responses in random places."

**Comment by Biokinetica** [comment]
How can you not know what I'm "going on about" with the extension mismanaging my chat responses?

**Comment by night** [comment]
> Any messages sent after load are always sent in the proper order

**Comment by Biokinetica** [comment]
Did you look at the screenshot?

**Comment by night** [comment]
You can try refreshing the page and seeing if it fixes the problem.. Or disable other add-ons if it still doesn't, as another might break our onload functionality..

**Comment by Biokinetica** [comment]
Refreshing didn't help, and I had no idea how any other extension could interfere with this one, or how to determine if that's the case.
