### ISSUE TITLE
Little Black Bars at top and bottom?

### ISSUE THREAD

**Issue by nguyendex** [night/BetterTTV#1719]
I don't know why but when I have the BTTV extension enabled on Chrome and Firefox (even with no settings turned on) I get little black bars on the top and bottom of the video player.

Bars with extension:
http://i.imgur.com/37K7oMo.png

No bars without extension:
http://i.imgur.com/LnBbTrR.png

**Comment by Leifman27** [comment]
Yes can confirm. i was about to report this bug myself right now!
the "Display resolution" gets stretched to 1280x750 (instead of the usual 1280x720 or what it should be) causing this black bars up and down.
I also checked and saw it happens on firefox as well as chrome and if i load the stream without bttv it does not happen.
must have been something that happened in latest build update causing this. hopefully it can be reverted/fixed as it is killing my OCD lol.

**Comment by night** [comment]
Twitch must have modified something to cause our calculator to be off. It will get fixed.

**Comment by EhsanKia** [comment]
Yeah, I've heard of even worse cases with theater mode being really messed up. Definitely something Twitch changed because we didn't touch anything there.
