### ISSUE TITLE
Emotes bug

### ISSUE THREAD

**Issue by jicnqx** [night/BetterTTV#1842]
After I subscribed to a channel, betterTTV emotes are not showing up. For example, people in the chat typed "LUL" but I didn't see the emotes that it used to be. I should mention that betterTTV worked well for me before

**Comment by b0bbybacc** [comment]
I, too, am having this issue - but only on "docked" chat. If you popout chat BTTV Emotes show proper again. 

It is work noting that I am running the latest Chrome browser on both Windows 10 and OSX and I am only seeing this issue on OSX. From Windows 10 machine BTTV emotes load fine in "docked" chat.

**Comment by jicnqx** [comment]
Oh it worked when I choose popout chat.
I am using the OSX system as well. Please fix this issue as popout chat maybe not be comfortable to see as docked chat.

**Comment by OurFlagIsMined** [comment]
Emotes were working at this commit:
https://github.com/night/BetterTTV/commit/5db4e7818c9789576b44cc44f84d9d0efdca75c2

And if you gulp from that and manually load the older `betterttv.js` they still work. So it appears that one of the changes made after that, caused emotes to break.

Spent 2 hours this morning going through each change after that line-by-line; didn't find anything obvious. I was only looking for changes though, not typos; so its possible that a typo got added in one of them and I missed it.

Tried re-enabling `src/js/features/channel-reformat/index.js` just for the sake of it, since I didn't see any other major changes, but that didn't fix it.

Didn't have time to check the console for errors before work, so there are plenty of obvious things I may have missed.

**Comment by EhsanKia** [comment]
@OurFlagIsMined Hmm, how does that line break emotes? Are you getting an error in your console?

**Comment by OurFlagIsMined** [comment]
@EhsanKia `playerService.playerComponent.ownerView.rerender()` doesn't exist anymore, it causes an error in the console (which is probably halting the script load before it gets to the emotes).

**Comment by night** [comment]
Fixed with 495fe236a0589368a5f753e69735eb65a53b6325
