### ISSUE TITLE
A way to access peoples personal emotes lists.

### ISSUE THREAD

**Issue by gapbl4** [night/BetterTTV#1897]
Would be useful to have a way to access personal emotes lists, so people could implement personal emotes feature in their custom chat clients.

**Comment by EhsanKia** [comment]
This would go well with this issue: https://github.com/night/BetterTTV/issues/1470

Both of those would be nice to have.

**Comment by night** [comment]
We do not serve them over our API because our extension doesn't require it (as it would be more costly to pull them over HTTP). You would need to implement our websocket system for personal emote support. See https://github.com/night/BetterTTV/blob/master/src/js/ws.js#L39 for our source on it. We might expose the personal emotes publicly via the management site at some point, but for now we have no plans.
