### ISSUE TITLE
Soft hangs and chat issues

### ISSUE THREAD

**Issue by Tsukiyomaru0** [night/BetterTTV#1936]
BTTV has been, for a long time, causing up to two types of Soft Hangs and a Chat Issues on Firefox 50.1.0 for Windows 10.

The first happens when joining a chat. It hangs for something between 10 and 30 seconds and appears to relate to CDN.

The second one happens at random intervals during the stream, these being as short as 2 seconds and as long as ten seconds.

Onto chat issues, at times the chat would not display new lines upon joining a channel, forcing me and other users to refresh the tab.

At other times, BTTV would fail to load properly, which would leave me with only Franker Face Z's autocomplete functions.

And stupidly often it FORGETS to scroll automatically

All of the above except where mentioned otherwise were confirmed as BTTV's fault.

I would also like to recommend there be a way that BTTV saves resources offline to speed up loading by only checking if the client side's content are up to date (possibly by a single file that contains the version number or something), along with a way to "refresh offline content", in case something new is added or there are corrupt files.

**Comment by night** [comment]
BetterTTV has its fair share of bugs. Firefox is unfortunately very slow with computation of views, so it exasperates the race conditions we know that exist. It will be fixed eventually, but complaining on here about every issue is not conducive. You might wish to switch to Chrome instead, since it tends to be way more stable.
