### ISSUE TITLE
delay

### ISSUE THREAD

**Issue by pokeguyboss** [night/BetterTTV#1980]
adds a delay so you can see chat like the streamer

**Comment by Stoupedog** [comment]
I feel this would be pretty impractical as when you go to chat you would be replying to messages posted 7-30 seconds ago.

**Comment by EhsanKia** [comment]
This indeed feels like a awful user experience, but one feature I would consider coding is a visual line that tracks how far the streamer has red. Some sort of red line in chat that keeps coming down showing you the last message the streamer has seen. We can extract the real latency from the player so that we can keep it accurate at all times.

**Comment by night** [comment]
The truth is that we should not provide any estimation of where the streamer is reading.. it's too ambiguous to be accurate, and places us as a source of blame if the broadcaster doesn't read someone's message.
