### ISSUE TITLE
Add option to disable autoplay of video

### ISSUE THREAD

**Issue by Jonty800** [night/BetterTTV#1996]
I've noticed recently that in the past broadcasts of a channel, it will autoplay the next video after the current one has finished. This is annoying, because if I fall asleep, my laptop will continuously play videos overnight. It's also an undesired behaviour.

Could you add a toggle to disable this 'feature'?

**Comment by DAOWAce** [comment]
I tend to play videos when I go to bed and have been woken up many hours later to a video still playing, interrupting my sleep and confusing me as to how it's still playing.

Would like to see a feature added to prevent this.

**Comment by Jonty800** [comment]
I notice this issue was opened for twitch: https://twitch.uservoice.com/forums/297558-general/suggestions/18396028-enable-disable-option-for-autoplay-feature-in-past

Feel free to vote and hopefully twitch will fix it so that BTTV doesn't need to.

**Comment by Gelletti** [comment]
Nice Jonty, left 3 votes on that issue! I made a duplicate thread about this the other day. I have the exact same problem as DAOWAce. Very strange that this autoplay should be a "feature".

**Comment by akriuchk** [comment]
Implement pleeeeeeease!

**Comment by JustRegisteredToSayThis** [comment]
Twitch is obviously not interested in improving the user experience by simply offering an opt-out choice for this just because it'd potentially make them a few extra ad dollars.
It makes no sense when the average video is 6 hours long to have these autoplaying, especially  when half the world is still on some kind of datacap.
It is extremely user unfriendly and I have 0 trust in them helping us out, when implementing a dark scheme took them 6 years.

Please Night, save us!

**Comment by oilrig11** [comment]
Please implement this! Not only does it dig into my data cap, I occasionally get woken up by some high pitched screaming streamers as it plays through videos. It got to the point that I gave up on the site entirely and just continued solely using youtube as I don't do anything on twitch except run vods while I sleep.
