### ISSUE TITLE
User account switcher

### ISSUE THREAD

**Issue by Braintree0173** [night/BetterTTV#2039]
As someone who shares my PC with another user, I am often switching which user is logged in to Twitch, and I feel like a fast user switch, even if the extension was saving passwords locally, would be beneficial to me.  

At the moment, I am simply using Private Browsing in Firefox (so as to avoid signing out the other user, who often has trouble remembering passwords), and I have to import the BetterTTV settings each time I open a new Private Browsing window. While this is only a few clicks, if the implementation of a one-button user switch was possible (like the one in Reddit Enhancement Suite, which I use daily), I know for sure I would use it, and other people might too.

**Comment by EhsanKia** [comment]
Why don't you use multiple browser profiles? With firefox it's a bit more complicated but if you search online you'll find results. With chrome it's right in the settings. You can also optionally use different browsers (them Firefox, you Chrome).

This way, not only you can have your own Twitch account and BTTV settings, you can also have your own bookmarks, your own browser settings your own history and your own everything else, instead of switching back and forth manually every time.
