### ISSUE TITLE
Can't use enter to send messages. (V7 Beta)

### ISSUE THREAD

**Issue by bobotje** [night/BetterTTV#2185]
You may think, it's the same person so probably same problem. I didn't tell my problem clearly in my last issue and that's why it was quickly closed. So normally if you use enter on twitch you SEND your message and not make a new line (that's shift and enter). It doesn't send my message.

**Comment by EhsanKia** [comment]
It would help if you could give more info instead of making another thread and still not explaining anything.

What happens when you press enter? Does it make a new line? Does it clear the text box? Do you see any errors in the console when you press enter (ctrl+shift+j)? Does it always happen in every chat and every message? And so on.

The more information you can give, the better we can help you. This is obviously not happening for anyone else so it's not a common thing, or else we would've caught it already.

**Comment by night** [comment]
I do not see what the problem is. Enter sends and shift-enter new lines you in the text box (even though new lines are stripped because Twitch does not support them). If you're not seeing this behavior enable the beta in the settings.
