### ISSUE TITLE
Suggestion: Display current uptime on channels view

### ISSUE THREAD

**Issue by LunarBear** [night/betterttv#2196]
Would it be possible to add the uptime to the All Channels / Followed Channels views? I find this extremely useful so you can know at a glance what's the current uptime of the streamer, informing you on whether they've just started streaming or they're probably going to stop streaming soon. 

Super simple feature which might not seem like much but is actually very useful. See screenshot (from Streamlink Twitch GUI):

![streamlink-twitch-gui_2017-03-27_22-49-04](https://cloud.githubusercontent.com/assets/6591277/24377669/67fd257a-1340-11e7-8407-390012b81cff.jpg)

Thanks!

**Comment by night** [comment]
Due to the intricacies involved in querying additional metadata from Twitch's GQL API and having to manage numerous page renders as the directory is browsed, it seems unlikely that we could build a good UX around extending the directory view. For this reason we are unable to build a solution for this suggestion at this time.
