### ISSUE TITLE
[V7] Fullscreen Issue

### ISSUE THREAD

**Issue by iBurnz** [night/BetterTTV#2304]
Whenever I open a new tab in Chrome, then immediately go back to the tab with Twitch open, I can't seem to get into fullscreen by pressing F. It briefly goes into fullscreen, but then immediately pops out of it. Whenever I disable BetterTTV, the problem doesn't occur.

Here's what the issue looks like:
https://youtu.be/ZTlVNsKhyxU

**Comment by EhsanKia** [comment]
This is a really strange issue, and I can replicate it, but I'm not sure what the cause is.

Notice that if you open a new tab with your mouse, the issue doesn't happen, it seems to be specific to ctrl+t. Notice also that if you click "ctrl" when you're back to Twitch, it doesn't happen after that, so it seems like ctrl key gets stuck when you leave Twitch by pressing ctrl+t, and it freaks out when you try to fullscreen.

We actually do check for ctrl key though and it's not actually stuck. To make it even stranger, it only happens with f. If I change it to another key, it doesn't happen anymore.

**Comment by night** [comment]
Pressing "F" for fullscreen is our feature. Pressing "ctrl + F" is Twitch's. I suspect there's a bug with the state of ctrl being pressed when you re-enter the pages such that Twitch thinks you are still pressing "ctrl" when you re-enter. Since it's a Twitch bug we can't really fix it :/

**Comment by EhsanKia** [comment]
Err, ctrl+f is search in almost any browser, I doubt Twitch is using that for fullscreen.
