### ISSUE TITLE
 JTV Chat Badges and more

### ISSUE THREAD

**Issue by LELS555** [night/BetterTTV#2357]
1. Please bring back the "old" JTV Chat Badges, thank you!

2. The Chat Badges like the Mod symbol or the Subscriber symbol are not centered when you have split chat on

3. The timestamp is not in an 24h format anymore. Before this update it got auto detected i think?!, Please fix

Wth was wrong with V6 is was good af  - V7 makes me rage

At the end please let us decide if we want the beta and DONT FORCE IT

**Comment by night** [comment]
> Please bring back the "old" JTV Chat Badges, thank you!

It's been retired, sorry. It is not practical to readd due to how chat is now implemented.

> The Chat Badges like the Mod symbol or the Subscriber symbol are not centered when you have split chat on

They are centered on my screen. Clear your cache. If it's still happening you may have a different extension installed conflicting with out css.

> The timestamp is not in an 24h format anymore. Before this update it got auto detected i think?!, Please fix

Timestamps are controlled by Twitch now, sorry.

v7 is a complete rewrite to reduce bugs and maintenance time when Twitch changes their site. Some things are just different and cannot be fixed due to complexity.
