### ISSUE TITLE
Desktop Notifications!

### ISSUE THREAD

**Issue by DonattR** [night/BetterTTV#2400]
Since like 1 month i dont get desktop notifications anymore, if someone goes live or someone mentions me in chat like i always used to get, even the option in the bttv settings for Desktop Notifications is gone! is this a global problem or just me ?
![bttv](https://cloud.githubusercontent.com/assets/22499171/25585585/9dd0fc46-2e9b-11e7-97ab-a7850e36ef6a.png)

**Comment by Bren002** [comment]
they probably removed it in v7 update. Twitch made a notification popup

**Comment by Antzer** [comment]
I hope they do add this back, desktop notifications were very important when you were switched in other tab, now i don't get notified when our favorites comes on. Please Night.

**Comment by GamerGramma** [comment]
Just wanted to put my 2 cents in....I'm all for the desktop, and audio notifications. I don't have a smart phone, so unless I'm on twitch 24/7, I don't always know when one of my fav channels comes online. Case in point...I missed a 4 hour stream last night...normally it wouldn't really matter, but since I am this streamers ONLY active moderator.....well, I'm sure you get the point.

**Comment by Bren002** [comment]
I never really liked the desktop notifications because if you were in game and closed it you would be bombarded with the messages.

**Comment by Antzer** [comment]
> I never really liked the desktop notifications because if you were in game and closed it you would be bombarded with the messages.
I mean the system before was optional and had a really special feature where it would only notify if you had set your followed channel to be notified via twitch.

**Comment by LukeDavies367** [comment]
I just use Chatty to get live notif.

**Comment by night** [comment]
Twitch added desktop notifications natively
