### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#2419]
1. Limit chat input to 500 characters. https://github.com/night/BetterTTV/commit/1f2b97944cd83326c12c98d7046b7eaa116002a3

> ![](https://i.gyazo.com/7690ec38f9103c9a3873aa4ab0e68643.gif)

2. Hide button for recent broadcast banner.

> ![](https://cloud.githubusercontent.com/assets/7132646/25736167/d823b8a6-3135-11e7-909f-8fe0238f28d2.png)

3. There's a "host" button on your own page. Results in "A channel cannot host itself."

> ![](https://cloud.githubusercontent.com/assets/7132646/25736415/520da8c4-3137-11e7-83e7-528230acc08b.png)

4. Clicking an emote that belongs to the channel that you're currently on will link you back to that page. Seems pointless and has always annoyed me. That channel's emotes should be filtered from this functionality.

I'd make a PR, but I don't have a clue where to put these changes.

**Comment by EhsanKia** [comment]
2. The original reason why I added that feature was because Twitch was broken and half the time, the banner would stay while the stream was actually live. Can you confirm that it still happens? If not, I don't see it as a big issue. BTTV already makes it half as tall which I think is good enough.

1, 3, 4 should be easy. If you'd like to fix them I can point you towards places where you can, if not I'll do them next time I do a PR.

**Comment by AlcaDesign** [comment]
As far as 2 goes, perhaps it would be better to not move the layout down and instead just overlay on the player.

![image]( https://cloud.githubusercontent.com/assets/7132646/25777161/8bc5c9fc-329a-11e7-83ff-8ff353265b3d.png)
![image](https://cloud.githubusercontent.com/assets/7132646/25777163/a3b131fa-329a-11e7-902d-05a6422dc695.png)
