### ISSUE TITLE
/local* mode oddities

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#2427]
Messages jiggle

![](https://i.gyazo.com/251c9fa592d84e85384cf62f1ee78999.gif)

Messages get removed while under limit

![](https://i.gyazo.com/453bfdaff95714f13c91da6641944bc6.gif)

**Comment by Nareese** [comment]
Not 100% sure on the first, but the second is definitely due to the fact that bttv now uses twitch's native chat instead of essentially re-implementing the chat system locally for display purposes, including buffering/scrollback.  bttv now just hides any lines that don't match the appropriate mods/subs criteria in local mode, but they're still there in the internal buffer, whereas with the old implementation, they were completely ignored, and never added to bttv's internal buffer.  What happens then is that the native chat's relatively small (and un-increasable) scrollback buffer limit is reached, and lines are being expired.  Even though there are only 4 messages displayed on your screen, they've scrolled out of the scrollback buffer in the native chat, so one at a time, they disappear.  This is the same thing that causes chat to continue to scroll in super busy chats when you scroll up to lock the chat (even without bttv... the problem is in the native chat implementation).  I'm not smart enough to know whether anything can be done to work around this inherent weakness in twitch's native chat.

**Comment by night** [comment]
lol @ the jiggling. yeah, not sure we can fix that.. a lot of features we reimplement are hacks on default chat.. and we no longer wish to maintain a separate chat implementation because we just don't have the time anymore. We have enough time to maintain and fix bugs, but having to reimplement every single new chat feature Twitch designs on our own is a very tedious task. I think automoderation was the last straw for us, and it was at that point I was fed up enough to finish rewriting the extension.

**Comment by EhsanKia** [comment]
Maybe if we find a way to neuter Twitch's message deletion, we can handle that ourselves which would allow us to set scrollback and fix this too, but yeah the more hacks we add the more painful it becomes to maintain.

**Comment by Nareese** [comment]
As far as I can figure, there are two separate things that might need to happen here.

One issue is freezing not working generally, and that is because of scrollback expiry.  The v6 bttv scrolling implementation explicitly checked if it was frozen and prevented deletion, then trimmed it back to scrollbackAmount once it was unfrozen.  Native chat obviously doesn't do that.  It lets lines be expired while frozen and that's why it scrolls (and why freezing seems to work properly when you first load a chat, until the buffer fills and lines start expiring).  I will be really surprised if there is a way to hook their scrollback expiry process and "neuter" it from outside, but I am admittedly clueless when it comes to knowing what is possible with their internals.  How you guys find some of the stuff you do is like black magic to me.

The other issue, however, specific to the local* issue, is that non-matching new messages need to be prevented from being put into the buffer (or at least immediately removed), instead of just hidden when a local* restriction is active.  I don't know if there's some other way to do that or if it means camping privmsg like v6 did, with all the mess that comes with that, cause that's undoubtedly more hackery than is desired, if it is even possible to do it for native chat.  But that is what is needed to solve the local* disappearing lines issue, by preventing a buildup of hidden lines causing the expiry of displayed lines off the top of the buffer.  Even if there was a way to increase the scrollback size, it would just delay the inevitable unless this could be done.  Some of the busiest, spammy-est chats, the ones where you'd most want these modes, can see 1000s of messages in very short time spans, and people would never get more than a handful of filtered lines before all the lines they aren't seeing makes them disappear. "Muh chat experience", as they say.

**Comment by EhsanKia** [comment]
Well if we handle the message deletion ourselves, it would fix both of those. But yeah, it really is about if we can find a way inside the code that does it and somehow top it from working, so that we can take over.

**Comment by thinkpad4** [comment]
Just having ability to set scrollback amount again would be great

**Comment by night** [comment]
this is really a cantfix, since doing any extensive editing of chat is no longer possible without great effort.
