### ISSUE TITLE
bttv stops all streams from loading

### ISSUE THREAD

**Issue by drksx** [night/BetterTTV#2458]
bttv v7.0.6 on safari 10.1.1 on macOS 10.12.5 suddenly has started completely blocking all streams from loading.  I restarted my browser, reinstalled bttv, disabled other extensions, rebooted computer.  Still won't load a stream until I disable/uninstall bttv.  Started happening in the last hour.

**Comment by HanaanY** [comment]
I have the same issue running firefox 53.0.2 (64-bit) on linux mint 18 sarah. Only the video doesn't load. It seems to work fine in chrome.

**Comment by Inevitable** [comment]
Same issue with Waterfox 53.0.1 (64-bit) on Windows 10.  Everything loads except for the stream (both audio and video).

Tested this in isolation with a portable version of the browser and only BTTV added.

**Comment by LBUlises** [comment]
There have been a couple threads about this issue on [/r/Twitch](https://www.reddit.com/r/Twitch/comments/6bsxoj/bttv_causes_my_streams_not_to_load_firefox/). Would love an update or at least some info on the issue.

**Comment by Thornox** [comment]
I can confirm this is occuring to me on Firefox 53.0.2 (64-bit) on Windows 10 Premium 64Bit

**Comment by mountnstream** [comment]
Same issue for me.  I'm using Firefox 53.0.2 (32-bit). I opted for beta of BTTV to fix a previous issue, so I tried to do a clean uninstall and reinstall, but I'm not sure how to do that, assuming that it would be part of the problem or not.

**Comment by night** [comment]
Unfortunately we have no idea why some users are seeing this problem. Since we are unable to reproduce it, there's nothing we can do to help.

A Twitch support staff member informed me it's happening to non-BetterTTV users as well, so it's most likely a Twitch problem. From what I heard, their video team is working on figuring out the cause.

The only thing clearing cookies may do to BetterTTV is reset your BetterTTV settings, so perhaps someone can figure out if a particular setting is causing the issue. I've tested all settings which affect the video player, and none of them allow me to reproduce this issue.

Otherwise, there's some cookie Twitch may be setting (like an experiment) which is causing these issues.

**Comment by night** [comment]
i was for some reason able to reproduce this on my work computer, but not any other computers. I still think it's a Twitch experiment, but in the meantime us removing our babel polyfill fixes the issue (for whatever reason). A release is deployed. This is fixed.
