### ISSUE TITLE
Did bttv certifications changed? an issue i'm having now

### ISSUE THREAD

**Issue by Leifman27** [night/BetterTTV#2464]
Windows xp -> Chrome version i am using i suddenly noticed that chat seems different and a bunch of features aren't working.. then i clicked the "bttv settings" button on the top right and i see this : 
http://i.imgur.com/VB5pxjP.png
Thing is, this only started today'ish (yesterday and for years obviously was fine and never had a similar issue)
only happens on windows xp in Chrome (older version) while its fine on windows xp firefox 
makes me feel like something to do with ssl certifications changing (as i know it is an issue with windows xp+chrome)

**Comment by night** [comment]
upgrade to windows 10. running xp and old chrome puts you at risk

**Comment by EhsanKia** [comment]
Sadly we don't support outdated systems. If it works, then good, but we're not going out of our way to support every single old version of browsers.

**Comment by thinkpad4** [comment]
I can stay with Win 7 and latest Chrome, right?

**Comment by trmcdougle** [comment]
I am getting a problem of no on screen elements (options menu/darken/blacklist/emotes etc) on Opera 36.0.2130.80 on Windows XP 32-bit (so I cannot use a more recent browser!)
However the functions are working (hide prime/cheers etc)

I am getting errors of "r.addedNodes[Symbol.iterator] is not a function" a number of times (1, then 2, the 40) at https://cdn.betterttv.net/betterttv.js?0.1824484073733348:52, then repeating at betterttv.unmin.js:8309 and betterttv.unmin.js:8303

I was starting to post this on 2466 as requested on discord, but am putting it here due to "night" indicating that is a duplicate of this topic.

**Comment by Bfahome** [comment]
I'm having the same problem of blank "BetterTTV Settings" window (and the troubles that come with it) on Safari 10.0.3, macOS 10.12.3.

**Comment by night** [comment]
You need to upgrade Safari to 10.1

**Comment by XinoeA** [comment]
Also having the no "BetterTTV Settings" button issue. On the latest version of Chrome (58.0.3029.110), using Windows 7 64-bit. Disabled all extensions, cleared cache, uninstalled and reinstalled BTTV but it still doesn't work.

Is Windows 7 still supported? If so other suggestions to try and resolve this would be appreciated.
