### ISSUE TITLE
Dark theme rework

### ISSUE THREAD

**Issue by flowzy** [night/BetterTTV#2469]
Hey.
I've started doing a rework for the dark theme. It is not as monotone as it is now, but I feel like this fits the site better.
It's built from the ground up, is based on SASS and feels more polished than the original.
I also improved the performance of the theme's stylesheet injection.

https://github.com/flowzy/bttv-theme

**Comment by night** [comment]
Please open a PR adding it in rather than maintaining a separate repo.. one of the goals of ours was to shift to sass, so this is a leap forward

where this currently diverges is we want to shift to css per module and scope our styles to css classes which get applied on the page.. i.e. `bttv-dark` is applied to the body, which all of our css is subclassed on. for a v1 I don't think this is required.. just it being in sass makes it easier to tear down

a good way we can appease the transition to this purple-ish theme is to use css variables and compile a grey and a purple version.. programmatically darkening or lightening a single color is also an easy way to reduce the amount of custom colors we need.

anyways, i'm all for this, but it needs some work to be integrate-able

**Comment by RyanEricWell** [comment]
Would love to see the video manager/past broadcasts page properly made dark theme as well.  As it is now, the page is dark but the video items are a bright/piercing white.

**Comment by night** [comment]
oh hey, this is done on the twitch beta branch
