### ISSUE TITLE
there's no bttv emote and gif menu to turn off or on

### ISSUE THREAD

**Issue by blainkaramel** [night/BetterTTV#2504]
so when i open bttv settings i cant find the emote and gif menu how do i fix this?

**Comment by Nareese** [comment]
I don't understand what you're asking.  The settings to enable BetterTTV emotes and gif emotes are "BetterTTV Emotes" and "BetterTTV GIF Emotes" respectively.  The setting to enable BetterTTV's enhanced emote menu is "Emote Menu".  All of these settings are present and working for me.  Please explain what you think is not working in more detail.

**Comment by thundermourne** [comment]
Same problem. those setting you are talking about @Nareese , they are not on the list somehow :/


![capturar](https://user-images.githubusercontent.com/29287748/26947032-1f8dc4ca-4c89-11e7-98f4-a650dc445fd7.JPG)

**Comment by Nareese** [comment]
Hmmm.  Still can't reproduce here with latest Chrome.  All the above settings show up for me.  Can you open the console and see if there are any errors there that would be relevant/helpful?  Also, just to make sure, if you are using any other twitch modifying addons or things like ad blockers, can you disable them and test to see if that makes any difference.

**Comment by thundermourne** [comment]
i tried on firefox and it works like a charm. on chrome i get  "Sorry, we were unable to connect to chat. Reconnecting in 16 seconds." and when it finaly connects not only do emotes not show in chat but also when i try to type in chat and press enter to send the message, it doesnt work and i have to manualy click CHAT to send it. no adblocker. as for console errors i dont know how i go about finding that out :/

**Comment by Nareese** [comment]
You can open the console by pressing ctrl-shift-J and selecting the console tab.  It has to be something weird with your Chrome install though, because if it was network related, it wouldn't work in Firefox either.  Just for testing, try to disable as many other extensions as possible in your Chrome (Menu->More Tools->Extensions, and turn off as many other things other than BTTV that you can) and see if that makes any difference.  Also of course make sure your Chrome is fully up to date (go to Menu->Help->About Google Chrome to force an update check), current version is 59.0.3071.86 (although mine was working fine with the previous version  58.0.3029.110 as well).

**Comment by thundermourne** [comment]
i was running the same version as you. Updated it. and now its good(check if that was your issue as well @blainkaramel  ), Still takes 1 minute to load the chat for some reason... the enter to send messages issue got solved by updating as well. the delay on getting in chat though is still bugging me.
got 33 errors and 1 warning on the console.

**Comment by Nareese** [comment]
A number of errors and warnings is normal, twitch's own code throws plenty of them.  As long as none of them says betterttv.net or betterttv.js, you should be fine.

**Comment by night** [comment]
If you're still having issues, one of your other installed extensions is likely conflicting with ours.
