### ISSUE TITLE
BTTV - theater mode, chromecast and whisper button

### ISSUE THREAD

**Issue by crehbein** [night/BetterTTV#2517]
The floating whisper button blocks the theater mode icon when in theater mode, making it impossible to return to non-theater mode.  This only occurs when the PC is configured with a Chromecast (Chromecast adds an additional icon to the video icons in the bottom right).  A refresh into non-theater mode is required.

Steps to reproduce:
- Install BTTV on a computer that is also a Chromecast receiver
- Launch a stream
- Change to theater mode
- Theater mode swap button is now blocked by the whisper icon

**Comment by crehbein** [comment]
![image](https://user-images.githubusercontent.com/9352448/27087908-428d6cfc-5024-11e7-9735-bbb3d22fa9c9.png)

**Comment by night** [comment]
I think you have your page zoomed, which is throwing off a lot of the element sizes. Try resetting your zoom to 100% by pressing ctrl+0.

Additionally, you can hide the whisper icon when it's not active in the BetterTTV settings.

**Comment by dansa** [comment]
I actually have the same issue at the moment, player controls are hidden behind the whisper window(s) while in Theatre Mode, both on chrome and FF, not sure what the issue is though?

![image](https://user-images.githubusercontent.com/5786317/27099855-836b141a-507c-11e7-91b2-ddc577218073.png)

Simply moving the whole bar up with padding works out but I'm not sure if the best solution to be honest,
`.app-main.theatre .player-controls-bottom {
    padding-bottom: 4.2rem; 
}`

![image](https://user-images.githubusercontent.com/5786317/27099866-893c732a-507c-11e7-8756-a4dd86c59551.png)

**Comment by crehbein** [comment]
Reset zoom, problem still exists.  Hiding the whisper button isn't a solution.
