### ISSUE TITLE
Firefox 57+ / Webextension version

### ISSUE THREAD

**Issue by Timmyfox** [night/BetterTTV#2552]
As per https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing it appears that any addons not updated for the new webextension standard will end up incompatible starting at Firefox version 57.

Unfortunately, the Firefox version of this appears to still be using the old addon model and therefore needs to be updated to maintain compatibility with version 57 and up.

**Comment by night** [comment]
we are well aware and will get around to it. it's pretty annoying that firefox keeps changing its extension system. this is the third iteration in a few years.. xul -> jetpack -> addon sdk -> web extensions.. it's really quite a shame what a hassle it is building extensions for firefox. not to mention we're not allowed in their addon store because they don't like how we modify twitch's page. i have zero love for firefox at this point. it really is the IE of the current generation.

**Comment by night** [comment]
We've published a v7.0.. if you check for updates in firefox it will update to the web extension if you're on ff 48+.
