### ISSUE TITLE
My BTTV Emotes are not showing, here's the Javascript errors

### ISSUE THREAD

**Issue by Reynolds95** [night/BetterTTV#2553]
I have not had any of the emotes in the BTTV tab show up for a week or so.  Only my sub emotes, Twitch Prime, and Global emotes appear.  There were 3 red errors related to BTTV: 

api.betterttv.net/2/changelog Failed to load resource: the server responded with a status of 500 ()

api.betterttv.net/2/emotes/channel_tip/wish Failed to load resource: the server responded with a status of 500 ()

betterttv.unmin.js:4920 WebSocket connection to 'wss://emotes.gamewisp.com/' failed: Error during WebSocket handshake: Unexpected response code: 503

**Comment by Nareese** [comment]
Did you install anything a week ago that might be interfering with those connections?  Anti-virus/anti-malware?  Ad blocker?  VPN?  Other "security" related extensions?

Also what browser and version, and OS and version are you using?

I can't speak to the gamewisp websocket, because I don't use gamewisp for anything, but after enabling it to test, it does appear that their web socket server is disconnecting immediately on connect.  I don't know if that's an issue for you, but if it is, you'll probably have to take that up with them.   The BTTV api server and web socket server, however, are both currently up and accessible, so something is interfering with those connections on your end (or somewhere between you and the server).

**Comment by Reynolds95** [comment]
Nothing I am aware of was installed. And I'm running Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by Nareese** [comment]
OK, so, can you try going to https://api.betterttv.net/2/changelog directly in your Chrome.

1 of 2 things will happen.
1/ you'll get an error of some kind (hopefully with a helpful error message).
2/ you'll see a bunch of badly formatted plain text (JSON code for the changes in the changelog).

If you get an error, try the same thing again, using a different browser.. Firefox, or IE/Edge, or whatever.  Do you also get an error there?  If you do get an error there as well, then it is not specific to Chrome, and something at the network level on your machine, or between your machine and the BTTV servers, is interfering with the connection.  We can't really help you diagnose this.  If you do not get an error in another browser, but do in Chrome, then it is something specific to Chrome.  Try disabling all other addons/extensions, or running in incognito mode and setting only BetterTTV to "Allow in Incognito" on the Menu->More tools->Extensions page.  If that works, you can try enabling other extensions one at a time until you figure out which one is the culprit.

**Comment by Reynolds95** [comment]
It appears to be fixed now.  I did not get the error in the changelog link.  So I started disabling other extensions and Tampermonkey was the first one I disabled and now they appear in my emote list again.  Thanks for all your help
