### ISSUE TITLE
Disable host mode is on but its still showing hosts

### ISSUE THREAD

**Issue by jermeister6** [night/BetterTTV#2556]
Don't know how much better to explain it other than i have the disable host mode turned on and host still goes on and is shown. I have also tried turning it on and off again which works until i completely close out of twitch but it bugs me that i have to redo that every time.

**Comment by Xev67** [comment]
Same issue here, must be a recent change as disable host mode was working fine as of Thursday.

**Comment by night** [comment]
i cannot reproduce this. provide valid reproduction steps or there's nothing we can do to fix.

**Comment by Xev67** [comment]
For me to reproduce this all I have to do is close the Firefox process with a twitch tab open that is hosting somebody. When I restart Firefox and it loads the twitch tab the hosted streamer is loaded instead of the offline screen for the page. I am running adblock plus, and no-script. The only scripts I am allowing on the twitch page are Twitch.tv, betterttv.net ,ttvnw.net, and gstatic.com. Firefox 54.0.1. To disable host mode I have to turn disable host mode off, turn it back on and re-load the tab.

**Comment by night** [comment]
that seems like it's a race condition then.. due to how the disable host mode works it's not likely we can fix it.. we simply toggle twitch's setting for it, we dont build it ourselves
