### ISSUE TITLE
Twitch Desktop App bttv

### ISSUE THREAD

**Issue by santiago555** [night/betterttv#2613]
Can you please make and bttv extension for the new twitch desktop app?

**Comment by larsstream** [comment]
^ Was about to write that as well
Please add it!

**Comment by Minkafighter** [comment]
Yes please, add it

**Comment by jkantr** [comment]
fwiw, the desktop app appears to really be just electron with some custom mojo around it. If BTTV is API compatible with `BrowserWindow.addDevToolsExtension`, this is a 1 button fix. Otherwise should just requires some elbow grease.

**Comment by Cerus13** [comment]
Please make an extension/addon for the Twitch Desktop App!  I use the web version quite a bit and this would top off the Twitch app.  Knight, your projects are great and loved by the masses!  Thank you!

**Comment by inscaped** [comment]
Would be awesome.

**Comment by CowPunk** [comment]
I just wanted to +1 this idea.  I'm a huge fan of the Twitch desktop app.  It just runs so much more smoothly than a browser does for Twitch for several hours at a time.  I didn't realize how much I loved BTTV until I wasn't able to use it anymore.  I'd love for it to be integrated into the app. I would even be willing to pay for the addon.

**Comment by Pepsuliini** [comment]
I was thinking about this the second I downloaded the new App

**Comment by BennettDams** [comment]
Would love to see BTTV for the Twitch app!

**Comment by Aven0x** [comment]
+1 If this could happen. Totally missing the emotes and being able to see deleted messages.

**Comment by gnatdagnat** [comment]
Since the desktop app is now more full-featured than the web version, we definitely could use this.

**Comment by Nimja1** [comment]
+1 on bttv for app, its easier on my cpu to run twitch and play games at the same time.

**Comment by dloiko** [comment]
@Nimja1 I was using it for the same reason (watching twitch in chrome made my computer fans go crazy everytime) - until I turned off hardware acceleration in the browser. Now the performance in the twitch app and browser are almost the same. Just FYI in case you have the same issue I did!

**Comment by Dddsasul** [comment]
yup, I need it!

**Comment by onjisan** [comment]
Add my vote as well. The first thing I was looking for was how to get BTTV working in the desktop app. :(

**Comment by MarkMonga** [comment]
+ 1

The only thing stopping me from using the Desktop App is lack of BTTV.

Hopefully Twitch themselves can make it easy to incorporate third party extensions in their app.

**Comment by skambli** [comment]
FeelsBadMan we need BTTV for desktop app

**Comment by wassereimer86** [comment]
+1

**Comment by Chooockie** [comment]
Yes, please!!

**Comment by brianj64** [comment]
It really seems like Twitch wants to shut down apps like BTTV and FFZ, and make them switch to their API's because it gives them bigger control. I really hope you find a work-around for when they do make the full switch to an app-based experience :/

**Comment by Fokusrite** [comment]
yes plz :D FeelsGoodMan

**Comment by Fokusrite** [comment]
by the way, is it just going to be like a mod you install for WoW for example? or will you have to contact twitch devs for implementing it?

**Comment by majorthorn** [comment]
+1

**Comment by brianj64** [comment]
If this is going to happen, it's more going to be like Better Discord, injecting javascript into the browser wrapper of the twitch app.

**Comment by thedude0101** [comment]
+1 FeelsGoodMan

**Comment by Rasiterita** [comment]
I would also love bttv for the twitch app. The app is itself is great, but twitch isn't quite the same thing without bttv.

**Comment by Zardium** [comment]
Yes, this would be great! I don't know about the logistics of doing it but it would be excellent if you could get it to work

**Comment by Wiblz** [comment]
Would be nice feature.

**Comment by Minkafighter** [comment]
Yes please!

**Comment by Soldiercolur** [comment]
Would love this.

**Comment by djtran** [comment]
+1

**Comment by eco999** [comment]
Love this idea. Browser lags the stream for me.

**Comment by imDED** [comment]
+1

**Comment by pinasu** [comment]
TwitchApp is ok, I guess. The only thing tht's really missing is the BTTV estension.

**Comment by kratoshakan** [comment]
+1 FeelsGoodMan Clap

**Comment by kyototeam** [comment]
+1

**Comment by Hazstic** [comment]
+1

**Comment by goodson345** [comment]
+1

**Comment by clarkycal** [comment]
+1

**Comment by aihe** [comment]
+1

**Comment by chrisEsk** [comment]
+1

**Comment by tsndr** [comment]
+1

**Comment by TheRealDannyyy** [comment]
+1

**Comment by ChrisM-Rogers** [comment]
+1

**Comment by lamblj** [comment]
+1

**Comment by TheRealDannyyy** [comment]
+1

@night I know you're probably very busy with fixing bugs and doing other important stuff but would you mind giving us a general statement about this please? 
- Is it possible to support BTTV in the Twitch Desktop App? 
- Is this feature actively being worked on or is it currently stalled by something? 
- Can the community somehow help in order to speed up the development of this feature?

I'd really appreciate a response,
_Cheers!_

**Comment by TheRealDannyyy** [comment]
Since this seems to go nowhere, would anyone be interested in an Electron based custom _Twitch Desktop App_ with BTTV, Adblock and Frankerfacez support? It's basically the same as running Twitch in your Browser but with faster loading times and other improvements and enhancements.

**If you would be interested in using something like that, please show your support by reacting below!**
(Prototype is already in the works but currently private for testing only.)

**Comment by inscaped** [comment]
@TheRealDannyyy I'm totally in if the app would use less RAM than FF/Chrome.

**Comment by TheRealDannyyy** [comment]
@inscaped Electron cuts down on some RAM usage by default and we are implementing a similar memory unloading system like the Official Twitch App already has (basically unloading memory on demand and not when the browser "feels" like it).

**Comment by inscaped** [comment]
@TheRealDannyyy Well, sounds great so far, totally will look forward.

**Comment by Astram00n** [comment]
+1

**Comment by GorillaxJax** [comment]
+1

**Comment by TheBaconSpace** [comment]
+1

**Comment by antyone** [comment]
@TheRealDannyyy yes please, the main factor behind considering twitch app instead of watching streams tradionally through web browsers is basically its RAM usage, the twitch app uses a lot less resources than my fully loaded web browser, be it chrome or firefox. 

Quite frankly, twitch app actually 'refreshes' correctly as well, sometimes when I'm on firefox watching streams over a longer period of time, the followed channels part on the left side of the website will stop updating, one of the things that isn't an issue on twitch app. 

I'd be very interested in something that could offer the 'twitch experience' outside of the web browser, it is basically a 'RAM thing' more than anything, the web browsers after a longer period of time can take a good 1.5GB of RAM, very inneficient.

**Comment by TheRealDannyyy** [comment]
@antyone I think the high RAM usage happens when watching VoDs right? That's unfortunately something that neither a native app nor a web browser could fix. This would require a complete, manually rewritten video player and that's something we're not planning to do anytime soon.

The main goal for of our Twitch App (current name: _Twitchy Desktop Lite_) is to provide a close to "Twitch App" experience but with VoD, 3rd party addon support, performance improvements and other features. Later down the line we would also allow feature suggestions, once we're done with the current list of features.

**Comment by antyone** [comment]
@TheRealDannyyy no, I'm talking about live streams.

The RAM usage in web browsers is just higher in general. Just for comparison, right this moment I have twitch app running video stream for 2 hours now and it only uses 400mb. My firefox browser with gmail and this website opened uses 800mb. 

Basically all I'd want is to watch streams with addons support that uses RAM efficiently.

**Comment by TheRealDannyyy** [comment]
> Basically all I'd want is to watch streams with addons support on something that uses RAM efficiently.

That's what we're trying to achieve with _Twitchy_ and hopefully we'll have a beta release available soon.

**Comment by TheRealDannyyy** [comment]
@clarkycal The full name is "Twitchy Desktop Lite" and we added the "Y" in order to prevent copyright issues (mainly with Twitch) from happening, nontheless if you guys got better name suggestions, feel free to suggest them.

**Comment by night** [comment]
our repo isn't the place for advertising external projects. we are still exploring this for the future.

**Comment by night** [comment]
As Twitch killed its desktop app, this feature request no longer appears possible.
