### ISSUE TITLE
Change LuL to some other casing

### ISSUE THREAD

**Issue by KauzDs** [night/BetterTTV#2660]
Can you guys add a toggle button to disable the new "LUL" twitch emote? Or make the old "LUL" lul instead of LuL

**Comment by rand0MPrecisi0n** [comment]
I second this, but instead make a button to overwrite all new LUL with the old one AND make the old one 'lul'

**Comment by TyroneSama** [comment]
Wouldn't it make more sense to override the appearance of the "official" LUL instead of creating a new emote entirely?

**Comment by TheRealDannyyy** [comment]
Adding to the suggestions above I would like to suggest adding a button in the settings menu in order to switch between the current mode (2 separate emotes) and the old mode (1 original emote).

This way users that like the existing mode with 2 emotes can keep using it and everyone else can simply switch to the classic emote which is being used by both "LuL" and "LUL".

![examplelul](https://user-images.githubusercontent.com/15656049/32472608-b5be0d14-c363-11e7-98a3-79ff064893ce.PNG)
*_This is not an actual feature (yet). Just a quick photoshop by me._
