### ISSUE TITLE
[Suggestion] Hide User Badges in Chat

### ISSUE THREAD

**Issue by CodyMKW** [night/BetterTTV#270]
I think it would be nice if BTTV had a option to hide the user badges (broadcaster,admin,mod,sub,ffz,etc.) in chats I just think it makes the chat look a lot cleaner :)

**Comment by DTittel** [comment]
Will not happen.

Hiding Admin/Staff badges would cause issues. FFZ is part of their
extension we don't officially support it. Why would you want to hide
broadcaster and mod tags allow for people who are mods to handle issues in
chat. Basically all your left with is Subs, considering subs contribute to
a channel I think it would be rude to undermine the minimal reward they
receive.

**Comment by CodyMKW** [comment]
not like it would affect everyone but oh well at least theres now a userstyle for Stylish to add this feature

**Comment by night** [comment]
> not like it would affect everyone

BetterTTV services a lot of Twitch users--so much so that we have to be careful with what features we choose to implement. I feel it would be in everyone's best interest to let tags remain visible. It could cause much confusion for staff members, admins, global moderators, or moderators who try to speak in channels if such a feature was in existence. You're welcome to use Stylish to apply custom CSS fixes on top of BetterTTV if you do so wish.
