### ISSUE TITLE
<message deleted> PROBLEM 

### ISSUE THREAD

**Issue by yamcam** [night/BetterTTV#2717]
I have BTTV for twitch , when someone got timed out / banned  the message turns to < message deleted > . i USED to be able to 'click it' to see what the person chatted . NOW   when someone gets timed out the message turns to < message deleted > but in normal font like everyone elses and i cannot 'click it'.... If anyone has had the same problem please help.

**Comment by sparcut** [comment]
@yamcam Are you trying to click `<message deleted>` in VOD chat? 

I am still able to reveal deleted messages in live chat.

**Comment by yamcam** [comment]
No , while I'm in live chat .. 'someones timed out' .. and the <messsage deleted >  shows, it is same text as before and I cannot view it. I wondering if some resent bttv update or twitch update might have changed it to that

**Comment by sparcut** [comment]
@yamcam Have you tried to see if this happens when you disable BTTV?

![2017-10-08_21-23-13](https://user-images.githubusercontent.com/16233822/31315954-f951287e-ac6e-11e7-89ac-2da348a9d5ac.gif)

There is a `chat_deleted_message` module, haven't read through it. But it's at the link below if you want to take a look.

 https://github.com/night/BetterTTV/blob/16b793a80d9f8cd075d76dd6a37c189ca517a02c/src/modules/chat_deleted_messages/index.js

**Comment by yamcam** [comment]
hahah that mod has no idea why someone told him fucku . thanks for the help
dude

**Comment by night** [comment]
#2605
