### ISSUE TITLE
an object-fit: fill for video in fullscreen mode option for non 16:9 resolutions

### ISSUE THREAD

**Issue by iamoverit** [night/betterttv#2891]
if it possible, to have an option that includes to video css style "object-fit: fill;" to have a real fullscreen on non 16:9 resolutions

**Comment by night** [comment]
Thanks for the request. This has been open for a while, but hasn't really had any traction since then. Most PC monitors tend to be 16:9, with exception to laptops. In addition, users are likely accustomed already to having black bars on full screen with every other site they watch content on. Adding a feature like this might honestly lead to bloat, so I'd recommend using an extension like Stylish to add custom CSS for this on your own if it's still an issue.
