### ISSUE TITLE
Can the follow button be added back to the mod cards?

### ISSUE THREAD

**Issue by thinkpad4** [night/betterttv#2910]
Could the follow button be re-added to mod cards, please?  It makes it easy for those of us that have whispers set to only people that we follow can whisper us.  Thanks

**Comment by EmilyPerrimon** [comment]
I'd like to up this, but to extend it to everyone, since a lot of streamers do shoutouts, it'd be nice for viewers to be able to click on someone's name and hit follow in the viewer card instead of opening the shouted out channel to then follow, it'd be more efficient and better for everyone.
I should point out that this suggestion has been shared on the Twitch Feedback website as well: https://twitch.uservoice.com/forums/297558-general/suggestions/35980528-add-a-follow-button-in-viewer-card

**Comment by night** [comment]
It looks like Twitch re-added the button back to moderator cards, making this request obsolete.
