### ISSUE TITLE
Dashboard Chat issue

### ISSUE THREAD

**Issue by ballerbandman** [night/BetterTTV#2938]
Out of no where, BetterTTV settings have stopped working on my chat but only in my dashboard. The dark theme does not apply, nor do any of the other chat settings I have enabled. I have tried basically everything I can think of and it still does not work. 
![image](https://user-images.githubusercontent.com/35845148/35449434-fb2f9dc0-028a-11e8-958c-2b6893cdf285.png)

**Comment by MinyaSylvanas** [comment]
Same problem, happened on Friday, or sometime between my previous stream end 4pm CET Thursday and 8am CET Friday, before my next stream started.
Everything works perfectly with BTTV on the entire Twitch pages, but on the dashboard, nothing from BTTV worked at all. The settings wasn't even showing up on the cogwheel.
 And just to be extra weird, the text size on the dashboard chat went from Twitch normal size to 6 or 8p, which made me squint like crazy to be able to read it. Ctrl+scrollwheel only made the chatwindow smaller, so there was room for way less text, yes, the text got bigger as well, but five lines of text to be able to read chat is not exactly ideal...
Restarting Firefox didn't work, restarting the computer didn't work, disabling and enabling BTTV didn't work, removing and reinstalling the newest version didn't work, so I'm convinced it's something in the code between BTTV and Twitch that is not playing nice together for some reason all of a sudden.

My solution at the time was going into my own channel, make sure the BTTV settings was on there, pop out the chat and just hover that window over the dashboard chat.
Not a perfect solution, but at least I could read chat and whenever my name was dropped it highlighted.
I hope this issue is worked out soon, not being able to read chat while you're streaming is kind of a big deal....

**Comment by night** [comment]
this is happening because twitch is embedding the chat component from their new site on the old site.. they used to use an iframe, which would work just fine

**Comment by MinyaSylvanas** [comment]
This is a reply that makes absolutely no sense.
What Twich used to use which would work fine, has obviously changed and does no longer work. What Twich used to use, is obviously not interesting atm, since they are apparantly no longer using it.
Will you be able to make BTTV work with this change? 
Why is it happening only on Dashboard and not on the channel chats if Twitch "used to use" an iframe, whatever the hell that is?

I'm not using legacy site, as that is impossible as of sometime last year, so embedding chat from new site to old site makes no sense to me at all.

**Comment by night** [comment]
this should be fixed now
