### ISSUE TITLE
Left side chat not working in theater mode when using firefox

### ISSUE THREAD

**Issue by 2a747** [night/BetterTTV#2971]
It looks like this: https://user-images.githubusercontent.com/35966048/35574920-64fade9c-05db-11e8-9018-bffd03f15fb5.png

Browser: Firefox 58.0.1 (64-bit)

**Comment by Rakuryo** [comment]
i posted the same issue but it got removed because it was not "reproducable" if i remember correctly. This problem still persists and i made a more detailed post about it on reddit

https://www.reddit.com/r/Twitch/comments/7wkw9p/left_side_chat_not_working_in_theater_mode_with/

Please fix this it's really annoying!

**Comment by night** [comment]
unfortunately without reproduction steps that work for me im unable to investigate and fix this issue.

**Comment by Rakuryo** [comment]
I also wouldn't know how to do that, the only thing i know that i had adblock plus installed first when i installed bttv at home. I thought it was an issue on my end and tried it with the same firefox version on a school computer but there the same thing happened (adblock plus was installed firet

**Comment by 2a747** [comment]
@Rakuryo It's not a problem caused by an add-on. I've tested it on Windows 8, Windows 10, Ubuntu 17.10, Debian 9.3 and with extensions disabled/enabled. It doesn't work on any of them.

**Comment by Kevin-Mok** [comment]
Same issue with Firefox 59.0.2 (64-bit) for Arch.
