### ISSUE TITLE
Emote menu problem

### ISSUE THREAD

**Issue by Nikksukka** [night/BetterTTV#2987]
When clicking on an emote from the bttv emote menu, the text appears in the twitch chat box but soon dissappears. Writing the emote text works fine.

**Comment by Nareese** [comment]
OK, I can reproduce this, and the specific circumstances of when it happens are very weird.  I'm pretty certain that the trigger for the text disappearing is someone who has not previously spoken in chat saying something, and the emote text will disappear as soon as their line appears.  Thereafter, if that person speaks, their line appearing will not delete the emote text.  Any emote text generated by the menu will be deleted, even in a line of mixed manual input and a clicked emote, but only if the emote text is at the end of the line.  The manually typed text remains, and the emote text disappears.  If you type additional manual text after the clicked emote, that emote text will no longer disappear.

If you test this in an inactive channel, the text will never disappear, because no one is speaking.  If you test this in a relatively quiet channel with only a handful of viewers, the text will disappear a few times until all the few active chatters have spoken once, and then the text will no longer disappear.  If you test this in a super busy, active channel of a large streamer, the text will be constantly disappearing as numerous new people are speaking all the time.

**Comment by Nikksukka** [comment]
I also have the frankerfacez extension and this problem first showed after I installed it so maybe the two somehow interfere with each other but since you were able to reproduce this with just bttv installed it's not neccesarily the reason. I'll try to uninstall the other addon and see if it does anything.

Any suggestions on how to fix this on my end other than uninstalling frankerfacez?

**Comment by Nareese** [comment]
I do not have any suggestions for fixes.  You can try uninstalling FFZ, but I doubt that's it.  It showing up just recently is just a co-incidence, as twitch, FFZ and BTTV all had major updates yesterday to account for twitch's unexpected change to React 16.  I'm not entirely sure that this is even a BTTV/emote menu problem, and that it isn't something in twitch's code, and the only time you see it is with a third party extension like emote menu or BTTV's tab completion, which obviously you'll never see if you don't have BTTV installed.

**Comment by Nikksukka** [comment]
Well thanks for the info anyway. :)
