### ISSUE TITLE
Subscribe message in chat

### ISSUE THREAD

**Issue by Matzen1337** [night/BetterTTV#3071]
Hello there, i've got a bug in like a week now, where i can't see the sub message in chat, when people are resubbing/subbing, i dont know if you have a fix on this, could be nice.

**- Matzen**

**Comment by d3xless** [comment]
Can confirm, disabled BTTV and started seeing the subs again.

**Comment by Nareese** [comment]
Unfortunately, a fix put in a couple of days ago to fix Twitch breaking the feature that allowed hiding the "New viewer greeting" messages has also affected other system messages like subscriptions.  To be able to see subscriptions again, you can disable the `Hide New Viewer Greeting` option in BetterTTV Settings.  Unfortunately, this means that you will see both the subscription messages and the greetings.  There is no longer any way to differentiate between them, which is why this broke.

**Comment by night** [comment]
fixed by 3e01972283bc911a11871f4f16c42faabf5e6818
