### ISSUE TITLE
Disable host button not working properly

### ISSUE THREAD

**Issue by Trysten-Asher** [night/BetterTTV#3116]
I have hoped it was a temporary bug but alas, I have been unable to permanately disable host mode. When I first load up a stream, I must open better twitch tv settings and turn off, then back on the disable host mode. This is quite inconvenient. I have limited bandwidth available and thus prefer to only leave tabs open for the streamers in particular that I want to watch, as other streams bandwidth requirements sometimes exceed what my current internet speed can handle.

**Comment by Blochead** [comment]
I have the same problem. I find that if I open and close the viewer list then the hosting gets disabled correctly for that channel.

**Comment by night** [comment]
this appears to work on the latest code in master

**Comment by Blochead** [comment]
Which version is being referred to as the latest code in master when this issue was closed?

I have v7.2.26 installed for Chrome and this is still and issue for me. It is 100% repeatable.

I have a channel pinned in a tab. When I refresh that tab it initially shows the offline channel but then updates to the hosted channel. If I open and close the viewer list it initially displays the hosted channel but then updates to the offline channel.

I have tested with the same channel and other channels in an unpinned tab and the behaviour is the same.

**Comment by Trysten-Asher** [comment]
I could understand if it was only one person experiencing this, but there are at least two known cases, if not more, of the same issue. It used to work fine at first, so there is most definitely a bug of some sort causing this issue.

**Comment by SirWeltschmerz** [comment]
I am still experiencing this issue as well.

**Comment by dustball** [comment]
Still happens for me.  Latest Chrome.
