### ISSUE TITLE
Disable host mode does not disable hosting

### ISSUE THREAD

**Issue by AliffanI** [night/BetterTTV#3129]
I have been having this issue since about a couple of weeks ago. Even though disable host mode is on, when a twitch page loads (or a stream ended), the player stops for a bit then plays the hosted channel anyway. I have to reenable disable host mode to make it stop playing. This happens on Chrome, sometimes on Edge, but not on Firefox. I could post a screen recording if my explanation is unclear. Thanks in advance.

**Comment by Nareese** [comment]
Can confirm this is currently an issue still.  It has been reported several times, but unfortunately, it is somewhat inconsistent and difficult to reliably reproduce, and every time night has tried it, it's worked OK for him.  

The current behavior I am seeing is that if you open a channel that is hosting, the channel will load and immediately switch to the hosted channel.  The player will then stop, as if hosting blocking was working correctly (this is also the behavior I see when it is working correctly, it will briefly play the hosted channel before stopping it), and it will display the offline screen, if any, of the offline channel, but then a few seconds later, the player will once against switch to the hosted stream and start playing.  The same thing will happen if the stream is live, and then goes offline with a host, although it happens much less often for me, even in Chrome, than it does on a fresh open of a page, or it will stop the stream offline for a longer period before switching to the hosted stream and playing it, sometimes a minute+, vs the few seconds for a freshly opened stream.

This is almost certainly timing sensitive, and it seems plausible that the reason it doesn't happen to the OP in Firefox is because FF is slower, and the timing matters.  As usual, latest Chrome with no other extensions loaded except for Ublock Origin, and I tried a page load with ublock both enabled and disabled, with identical results.
