### ISSUE TITLE
Sub buttons gone

### ISSUE THREAD

**Issue by janxer** [night/BetterTTV#3185]
my sub buttons are gone when betterTTV is loaded. when i disable betterTTV, all the buttons show up again
![missing](https://user-images.githubusercontent.com/41654282/43171490-1dc7c536-8f5f-11e8-8eaf-78af9d30f3b0.jpg)

**Comment by thinkpad4** [comment]
It seems that this is caused by the Hide Bits option being turned ON in BTTV settings.  With Hide Bits ON 
![yg18kgr](https://user-images.githubusercontent.com/6820014/43242443-1967d0b0-906f-11e8-8349-b334d0ec67f8.jpg)

With Hide Bits OFF 
![unknown](https://user-images.githubusercontent.com/6820014/43242451-27af51b6-906f-11e8-89e6-293cfa59ba5b.png)

**Comment by Nareese** [comment]
Additional info, removing the selector

`.channel-header__right div.tw-mg-l-1:last-child button:not([data-test-selector="subscribe-button__dropdown"])`

from modules/hide_bits/style.css resolves this issue.  I am not sure what that selector was originally intended to hide, so I'm not sure what to offer as a replacement, or if a replacement is even still necessary, but hopefully that provides a helpful starting point.
