### ISSUE TITLE
BTTV Emotes not showing

### ISSUE THREAD

**Issue by eikeschott** [night/BetterTTV#3194]
Hey there,
have the issue for a while now, that the BTTV emotes menu right next to the settings and filter option is not showing up. 
I defently have the BTTV emotes enabled in the settings. Tried firefox instead of chrome and reinstalled the extentions on both browsers without success. 
I'm on Chrome 68 and firefox 61. 

Here is a picture of my settings and the problem.
https://imgur.com/a/ImqJ0pI

**Comment by Levelleor** [comment]
I have the same issue. Emotes/gif emotes are on. Chrome Version 68.0.3440.84 (Official Build) (64-bit). Console log attached to this message. Only recently I had another PC, like 4 days ago where emotes worked, but on this laptop they don't, I can't verify that right now but seems others also are having this issue. Clearing cache and hard refresh did nothing. 
![image](https://user-images.githubusercontent.com/11915185/43662992-862ef96e-9770-11e8-8ace-b576a58f435f.png)

**Comment by night** [comment]
what other browser extensions are you using? have you tried disabling all other browser extensions and trying again?

**Comment by Levelleor** [comment]
@night Hello again. I know you closed this thread but I have to provide more info about the issue. 
1) I got back to my main PC and this addon broke here too after it was working for so long before. 
2) I am talking about it working in VODs, I usually watch VODs instead of streams. 
3) In the screenshot, there is only adblock active, but I tried disabling every extension too. No luck so far. 

It is 2 different computers and both broke at the same time, something is wrong here, too much coincidence.
