### ISSUE TITLE
multiple chat functionality problems

### ISSUE THREAD

**Issue by Nareese** [night/BetterTTV#3233]
Update Again:  As of 1800 Eastern 8/28, all of these issues appear to have returned.  Twitch must have rolled out yesterday's changes again.

Following an update today, there are currently a number of chat functionality problems.  Things I have seen reported so far:

- ~~Twitch emote tab completion not working~~ (fixed)
- / commands not working (/uptime reported, but they're all not there)
- ~~mod card enhancements missing (join date, views, mod presets, keybinds)~~ (fixed)
- show/hide deleted message handling is not working (always shows `<message deleted>`, clickable if mod)
- ritual hiding (chat events hiding) is not working
- anon chat not working
- host button
- various onSendMessage handlers (recording/recalling messageHistory, etc)

Probably more.  I traced the tab completion to twitch.getChatController() returning null, so that may be a root cause or there may be others.  There's probably watcher initialization issues related to this that may be influencing the other issues.  The selector that is being used to find CHAT_CONTAINER appears to still be there with the same name, but searchReactParents looking for n.statenode.chatBuffer is not returning anything.  I'm still digging, but I'm not enough of a React expert to search for this stuff and find where its gone.  Hopefully that minimal digging provides a helpful start.  I'll update the issue if I can find anything else.

Update:  Added some additional items.  Apparently, some users have emote completion still working.  Also a user reported that modcard enhancements work when clicking on a user in the viewer list, just not chat, so seems likely to be something .click() binding related.

**Comment by kilroych** [comment]
Have the same issues.

**Comment by night** [comment]
Twitch rebuilt their chat system internals so chatBuffer is no longer exposed. They seem to shield it and expose only public methods on the class. Unfortunately this means that fixing the broken functionality is non-trivial since I need to rewrite all of the logic these features are built on to not rely on chat buffer. I'm not sure which of the features relying on it can be repaired. I'm very busy atm so no ETA.

I fixed two of the issues though, moderator cards + tab completion, since both don't rely on chat buffer.

**Comment by night** [comment]
this is now fixed
