### ISSUE TITLE
Several chat channels

### ISSUE THREAD

**Issue by jaa121** [night/BetterTTV#333]
Hello!
What you think about the possibility of adding a few chats on one page? Like this (i know it is ugly but I have only paint ;p):

![cc](https://cloud.githubusercontent.com/assets/11669792/7102385/56936272-e07f-11e4-9cd8-b31ba6f535f5.png)

**Comment by DTittel** [comment]
If all chats remained loaded at the same time I would back this "Tabbed Look" and was actually going to look into it when the feature first came out. Because each chat reloads every time you switch chats with the current Twitch implementation doing this and having it acceptably functional would require basically rewriting and overriding the entire Twitch feature.

**Comment by night** [comment]
Unfortunately while BetterTTV already has support for being in multiple rooms, Twitch's internal API doesn't support multiple channel rooms being joined at the same time (they only support multiple group chat rooms).
