### ISSUE TITLE
new Twitch update broke BTTV to not show up or work

### ISSUE THREAD

**Issue by Gamerbiomek2** [night/BetterTTV#3412]
new Twitch update broke BTTV to not show up or work
no emote menu either
just nothing is working

**Comment by Oxize** [comment]
Same. Gone since today.

**Comment by ThaScientist** [comment]
I've got the same issue, went through the normal steps, reinstalled it several times, cleared cookies and cache, disabled other add-ons and restarted my pc, If I read the console right it seems like it keeps on stopping it loading because another instance is already running, maybe it shuts itself down somehow. 
If some1 can tell me what part of the console to post, I can

**Comment by dddavo** [comment]
Same here on vivaldi and chrome

**Comment by Maihel** [comment]
Same here, noticed that when I wanted to have the chat on the left side that my settings options for BTTV were gone.

**Comment by Nowlyy** [comment]
enable the chat popup, this resolve

**Comment by quietconundrum** [comment]
> enable the chat popup, this resolve
this is only a temporary remedy for the chat-related symptoms, not for the rest of what BTTV controls on the site.

**Comment by DonBongJohn** [comment]
Well at least it's something. Can confirm that it does work. ;)
