### ISSUE TITLE
anon chat and local sub

### ISSUE THREAD

**Issue by faucetsoftware** [night/BetterTTV#3420]
when you are in anon chat and enable local sub the chat acts very strange deleting messages and spamming info messages

**Comment by Nareese** [comment]
I am not able to replicate any unusual behavior related to using localsub mode and anon chat together.

That said, you should be aware that in the current implementation, localsub mode merely hides non-subscriber messages.  The underlying non-subscriber messages are still being received by the chat, and they will still cause the chat to scroll and therefore earlier messages will expire from the chat's extremely small buffer.  When the lines expire from the buffer, they are removed from the chat window.  Because of this, it is possible, especially in a very busy chat with limited numbers of subscribers and many non-subscriber chatters, for subscriber messages to expire from the chat window when the window does not appear even close to full, or even for the chat window to be left completely empty (there are no subscriber messages in the buffer).  There is nothing that can be done to fix this behavior with the current implementation.  It is also worth noting that this behavior is exactly the same regardless of whether anon chat is enabled or not.

As for "spamming info messages", I did not see anything like that.  Please provide more details and/or a screenshot.

**Comment by faucetsoftware** [comment]
![123123123](https://user-images.githubusercontent.com/26048779/54885037-2794f580-4e4e-11e9-9341-2330614590c0.png)

Please note I am not complaining I am just providing feedback.

**Comment by Nareese** [comment]
I noticed that there is one of those messages sent when you do any / command except /join (which is probably technically a bug, although maybe not one that's worth a lot of effort to fix, it's just cosmetic), so are you typing / commands in chat when those appear, like toggling localsub on and off or something, or are they just appearing on their own?

**Comment by night** [comment]
i am not able to replicate any odd behavior personally. we disable all commands, including local ones except `/join`, when in anon mode.
