### ISSUE TITLE
Chat gets minimized when messages are timed out

### ISSUE THREAD

**Issue by Civrock1** [night/BetterTTV#3444]
I only noticed this a few hours ago and it appears to be related to the "Show Deleted Messages" setting in BTTV. When this setting is set to "Off", chat does not minimize when a user gets timed out (be it by a bot or another mod). 
It also appears to be limited to non-embedded Twitch chats, such as on the actual website or popout chat; chat on sites such as multistre.am is unaffected.

The affected div class appears to be "chat-list". Screenshot of the behavior below (not mine, this is from another user with the same issue on [/r/twitch](https://www.reddit.com/r/Twitch/comments/bdwx8m/twitch_chat_disappearing_completely/).

![be5d273ff1b54a0ffff677bce665454a](https://user-images.githubusercontent.com/19143373/56250389-45d0c880-607d-11e9-8f9d-02f9f80cc289.png)

EDIT: Appears to be related to this: https://twitter.com/TwitchSupport/status/1118292025852485632

**Comment by ThunderSn1per** [comment]
The "Show Deleted Messages" seems to be made superfluous by the new addition to the mod tools linked above. Currently the fix is to turn off "Show Deleted Messages" and instead set Deleted Messages  under Mod Tools (accessible in stream chat via the cog) to 'Detailed'. The conflict between Mod Tools and BTTV showing the message causes the deletion of the div that contains the chat. Unsure why, but so far this has solved the issue for myself and my mod team. [https://cdn.discordapp.com/attachments/385734454502621184/568920866872754191/unknown.png](Mod Tools > Deleted Messages Setting)

**Comment by night** [comment]
i am not able to reproduce chat getting "minimized." other issues specifically with showing deleted messages are covered by other open issues.

**Comment by Civrock1** [comment]
Myself and other moderators I know can still reproduce this issue. Below are the criteria with which I'm experiencing it:

- BTTV: "Show Deleted Messages" must be enabled.
- Twitch: "Deleted Messages" must be set to 'Detailed'.
- A message gets timed out by a moderator or bot (i.e. Moobot; links or other triggers).

During the third step, the "chat-list" div class gets "minimized", if that's the appropriate word for it. See screenshot in my initial comment for this issue. I'm using Chrome, not sure if other browsers are affected,

**Comment by ThunderSn1per** [comment]
Just as a correction to Civrock1's last comment, I can't see the "minimised" chat-list div, for myself on Chrome the div is completely deleted. As stated, BTTV "Show Deleted Messages" should be set to "On" and "Deleted Messages" in Mod Tools set to "Detailed". There then appears to come a conflict on a semi-rare occurrence that causes the div to be deleted instead.

My comment above has proven to be effective as none of my mods have said anything about their chat "disappearing". Since the mod tools section now has native support for this specific function as I said, BTTV's "Show Deleted Messages" are superfluous?

**Comment by night** [comment]
Twitch's mod tool overrides our deleted messages functionality. Ours is only active when you're a non-mod now.

**Comment by Civrock1** [comment]
> Since the mod tools section now has native support for this specific function as I said, BTTV's "Show Deleted Messages" are superfluous?

A lot of people use it to be able to see deleted messages, while not being a mod, instead of it being replaced with the "Deleted by a moderator" blurp. I'm not sure if that was the original intent of this BTTV option.

> Twitch's mod tool overrides our deleted messages functionality. Ours is only active when you're a non-mod now.

Is this new with 7.2.56 which was released earlier today? Meaning I should be able to enable "Show Deleted Messages" in BTTV again without it minimizing chat in channels that I'm moderating when something is timed out?
