### ISSUE TITLE
bttv dosent work on firefox

### ISSUE THREAD

**Issue by fislysandi** [night/BetterTTV#3461]
its just doesn't install or run on firefox chrome is fine. here can provide more screen shots if more information needed. https://imgur.com/a/X9NHkry

**Comment by Nareese** [comment]
This is not an issue with BTTV, it's a well known issue with Firefox.  If you google for the second error message, you'll find the same thing happening to a wide variety of firefox addons over many years.  It's been around for a long time.

The only viable solution we are aware of is to download the file (https://nightdev.com/betterttv/firefox/betterttv.xpi) to your PC manually, using a different browser if necessary, and then open your firefox and drag and drop the downloaded file onto your firefox window.  That works in the vast majority of cases.  If it doesn't, the only other solution is to completely delete/rest your firefox profile, but that will lose everything... other addons, bookmarks, settings, etc, so it's a last resort, and you'll want to back up as much as you can before you do that, if you have to.

Also, just to check, but make sure that your Firefox is updated to the latest version as well, because of their signing certificate issues earlier this month.

**Comment by fislysandi** [comment]
oh thanks!
