### ISSUE TITLE
85% of the features just broke

### ISSUE THREAD

**Issue by NismoGraphics** [night/BetterTTV#3479]
Literally nothing but a few features work.
Left Side Chat works as the only thing I can see.

Even the emotes is gone. Wut?

**Comment by sharkbound** [comment]
happening to me as well, firefox quantum, version: 67.0.1 (64-bit)

**Comment by theyuvalshor** [comment]
same here, bttv just doesn't work all of a sudden.

**Comment by Nareese** [comment]
Additional info for night (or other interested parties who know more about digging through the innards of React looking for stuff than I do):

watcher.js initialization is failing getting a null result back from twitch.getRouter().  I have tried the obvious easy fixes of searching parents instead of children, and increasing the search depth of both, and nothing finds anything, so they've changed the naming or structure.  Right now getRouter() searches children for looking for a structure that matches node.stateNode.context.router and that is failing.

**Comment by chffUA** [comment]
Same here. Chrome with no other extensions enabled, BTTV doesn't work.

**Comment by ancapgamer** [comment]
![betterttv](https://user-images.githubusercontent.com/42419336/59069419-482cf300-8874-11e9-9bac-d24056c969dc.png)

Same happened to me. Worked fine yesterday, Today NOPE!  
Google Chrome is up to date
Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nycacorp** [comment]
Closed my other issue as its a duplicate from a few others that were created at same time:


Most of the current issues that are open are probably all for this issue.
Lastest version of Chrome; no extension enabled except BTTV
No antivirus or Windows network protection enabled.

DEVTOOLS -> Console -> Javascript errors

ErrorHandling.js:38 Error: apstag has already loaded - preventing duplicate load
at Object. (VM5719 apstag.js:2)
at r (VM5719 apstag.js:2)
at Object. (VM5719 apstag.js:2)
at r (VM5719 apstag.js:2)
at VM5719 apstag.js:2
at VM5719 apstag.js:2
p @ ErrorHandling.js:38
(anonymous) @ apstag.js:74
r @ bootstrap:19
(anonymous) @ Networking.js:125
r @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
27Refused to load the font '' because it violates the following Content Security Policy directive: "font-src ".

component.html:1 Access to fetch at 'https://science-output.s3.amazonaws.com/spade-uri' from origin 'https://d4uvtfdr04uq6raoenvj7m86gdk16v.ext-twitch.tv' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Store.js:243 Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://mslfr4spx7byj1zchkhjvsuc5f4362.ext-twitch.tv https://extension-files.twitch.tv https://www.google-analytics.com".

**Comment by NismoGraphics** [comment]
NIGHT! It happened again, please...
