### ISSUE TITLE
Switching between squad members more than once breaks chat on Chrome

### ISSUE THREAD

**Issue by jasswolf** [night/BetterTTV#3502]
Basically attempting to switch back to any channel while viewing in squad mode results in breaking chat, either by chat ceasing to update, or all chats being shown as one (complete with uniform subscriber badges, and message only sent to that corresponding channel).

Have tried clearing Twitch cache in full (and thus BTTV) with no effect. Disabling BTTV removes the issue, and have not tested for the issue on another browser.

**Comment by night** [comment]
I'm not able to reproduce any issues, and this honestly sounds more like a Twitch bug since we don't manage chat itself. All BetterTTV does is mutate chat as it is posted to the screen. We don't print chat ourselves. If you're still having this issue please make sure you have no other browser extensions installed and otherwise post a video so we can properly reproduce and fix this.

**Comment by jasswolf** [comment]
I understand you've closed this issue, but I've recreated it since on Edge (Chromium version) with no other plugins enabled and a clear cache, and have found it to be the cause of the issue on Chrome as well.

To clarify what the issue is: you enter squad stream mode, chat functions as normal, then you can move into each stream in the squad, chat operates as normal.

Once you switch back to the original chat you started in, all the other stream chats stop being parsed in their individual panes, and instead group into one pane, the original stream your started on as your primary.

Disabling BTTV completely fixes the issue, and I believe that your plugin may be the direct cause of a lack of popularity with squad mode (i.e. stream regulars see their chat completely break). Anecdotally I've seen others report on this, and it's BTTV every time.
