### ISSUE TITLE
Possibility to see capitalization of usernames in chat

### ISSUE THREAD

**Issue by Immortalizd** [night/BetterTTV#352]
Say that the username is 'userName'. The chat shows it as 'Username'. What about having an option where you can enable capitalization so that 'Username' becomes 'userName'?

**Comment by night** [comment]
BetterTTV already capitalizes usernames, but unfortunately due to cost restraints we cannot scale our socket server to support the amount of traffic we receive. We can only support up to 120,000 connections at a single time. Twitch is working to bring display names to chat, but we don't know when that will happen.
