### ISSUE TITLE
Default to Live Channels - Extremely Slow

### ISSUE THREAD

**Issue by Seksl** [night/BetterTTV#3521]
It takes about 15 seconds to automatically go from the "Overview" tab to the "Channels" tab when "Default to Live Channels" is on.

**Comment by Nareese** [comment]
I have no idea why this would take 15 seconds for you, as opposed to completely not working at all, which is what it does for me at the moment.  This is being caused by the watcher on `load.directory.following` failing to fire, because its predicate uses `$('.following__header-tabs')` which apparently no longer exists.  As is so often the case these days, there is now no unique identifying class on the tabs container, so I'm not sure how best to resolve this.
