### ISSUE TITLE
[Feature Request] Disable twitch-font / switch to non-eyestraining fonts

### ISSUE THREAD

**Issue by marttinen** [night/BetterTTV#3596]
I would love to see a feature to switch out the 'new' twitch.tv font with a font that is actually decently readable. Maybe by just removing that custom font at all and just use the systems/browsers fallback normal font.

**Comment by SM1ThaYe** [comment]
Agreed.
An option to use a normal non-bold font especially for 'Followed Channels' as it really cuts down on the smaller channels I follow that are visible in a no-frills compact format. Also, you can only select font options for chat and would like this extended globally if possible.

**Comment by Scrxtchy** [comment]
If you're using ublock origin, you can add this rule to block Roobert (and all other custom fonts)
`twitch.tv https://static.twitchcdn.net/assets/ font block`

Twitch currently use Helvetica as the fall-back if roobert is unavailable, which is the old glitch font

**Comment by night** [comment]
We support the use of any font and size you'd like inside of chat (since this is the surface most users spend time reading), but to replace the font for the entire Twitch site sounds like overkill tbqh. The font isn't all that bad, though the font sizes in some spots (like headers) are questionable.
