### ISSUE TITLE
GIF Emotes

### ISSUE THREAD

**Issue by Prahdo** [night/BetterTTV#3613]
Hi my name is David, I emailing you because for the past couple of weeks my GIF emote option has been turning off on its own and I have to switch it on every time I log onto Twitch.

**Comment by Nareese** [comment]
Options don't just "switch off on their own".  Something about how you have configured or are using your browser is causing this problem.  Either you are watching Twitch in a "Private browsing" or "Incognito" window, in which case, settings are not and will not be saved when you close that window, or you are using some sort of browser "clean up" feature or extension, which is deliberately deleting your cookies and locally stored information when you close your browser.  Some browsers have this feature built-in (Chrome:  Clear cookies and site data when you quit Chrome), and most if not all browsers have 3rd party extensions that do the same thing, some of which will allow you to configure exceptions, which you will have to do if you want to use that feature and not have it affect your twitch/BTTV settings.

The fact that you say you have to do this "every time I log onto Twitch" is another clue that you have such a feature enabled, because under normal circumstances, you should log into Twitch once, and you should stay logged in more or less forever, even if you close your browser.  If you have to login every time you open your browser, that means that the same "clean up" feature is also deleting your Twitch cookies/local data.

**Comment by Prahdo** [comment]
Well, I don't use Twitch in a private browser or in incognito mode. And to
correct myself I meant switching the option back on when opening the Twitch
website, I am always logged in and I have no chrome extensions. And I'm
sure my cookies are being deleted and the option still turns off on it own.

**Comment by Nareese** [comment]
Please check the setting in Chrome at Settings -> Advanced -> Privacy and Security -> Site Settings -> Cookies and site data -> "Clear cookies and site data when you quit Chrome".  What is the state of that setting?  If it is on, turn it off.  If it is off, then I have nothing further to help you.  I can tell you that if this was a general issue with BTTV, this issues board would be flooded with reports, and there have been none. This is some sort of issue with your browser, and if the above does not help you, then I don'y have any other advice.  Sorry.

**Comment by night** [comment]
As Nareese said there's something atypical of your setup, and something is eating your settings.
