### ISSUE TITLE
Collapse chat button is over chat textbox

### ISSUE THREAD

**Issue by Evolvedruid** [night/BetterTTV#3679]
Please put the button elsewhere so it's not hiding chat. It's annoying me since the Twitch new design. Thanks.

**Comment by whitecrownclown** [comment]
@Evolvedruid Dont know what you mean by that. Could you provide a screenshot of before & after as well? Thanks.

<img width="283" alt="Screenshot 2019-12-07 at 23 01 30" src="https://user-images.githubusercontent.com/8309417/70380533-87ccb880-1945-11ea-8f8e-3cea33fcc757.png">

This is what i understand by collapse chat button and it's nowhere near the chat box.

**Comment by Evolvedruid** [comment]
Hello, sure thing here's the screenshot. Thanks for the help!

**Comment by Nareese** [comment]
This appears to be related to the `Hide Chat Header` option.  I don't have any immediate suggestions for how to resolve this in the absence of that container, since removing that container allows chat to touch the top of the enclosing container that contains all of chat, leaving nowhere to put that button that wouldn't be over top of chat lines.  The only option I can think of would be to hide it completely. 
 It's unfortunate that unlike the user list button, that button is not actually contained within the chat header container, and doesn't disappear with it.  If you want an "interim fix", I would recommend turning the `Hide Chat Header` option off.  Yes, it "wastes" a handful of pixels at the top of chat, but that's better than having random elements floating over chat and obscuring it.

In the event that hiding it is the chosen solution, the fix for that is to add the container for the collapse button to hide_room_selector/style.css as:

`.room-selector .rooms-header, .right-column__toggle-visibility`

**Comment by Evolvedruid** [comment]
Thanks for your reply. I actually found a fix, i got inspired by your idea... I can easily hide it with my adblock and it still is functional. A permanent fix idea would be to put the button besides the "subscribe" button, like it is when the chat is collapsed. Cheers!

**Comment by night** [comment]
fixed by 0b8d7bf89514ef6e1564032031991c873a6719d2
