### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by BodieGaming** [night/BetterTTV#3698]
for some reason starting today when I turned on my pc BTTV chat settings are not being saved and I have to reset all of them every time I log in to twitch now this has never happened before

**Comment by Nareese** [comment]
The most common cause of this is that you have activated some sort of "browser cleanup" feature or extension that deletes cookies and local storage data when you close the browser.  This is further supported by you needing to do this "every time I log in to twitch", because you should never, on a regular basis, need to log in to twitch, you should login once, and you should stay logged in more or less forever, even across browser sessions or even reboots.  This is additional indication that your cookies (including your twitch login) are being deleted.

In Chrome you can find this option under Settings -> Advanced -> Privacy and Security -> Cookies and Site Data -> Clear cookies and site data when you quit Chrome

In Firefox you can find this option under Options -> Privacy & Security -> Cookies and Site Data -> Delete cookies and site data when Firefox is closed.

Other browsers may have similar options, and third party extensions of course exist that do the same kinds of things.
