### ISSUE TITLE
The Channel emotes endpoint stopped working? 

### ISSUE THREAD

**Issue by S0und** [night/BetterTTV#3708]
Hi

I used this endpoint, and since yesterday, i get an empty array

https://api.betterttv.net/2/channels/{channel name}

{
    "bots": [],
    "emotes": []
}

Although the global endpoint still works: 

https://api.betterttv.net/2/emotes

exp:

https://betterttv.com/users/58f72adfa18fc4365deb6424

vs

https://api.betterttv.net/2/channels/dafran

which returns:

{
    "bots": [],
    "emotes": []
}

**Comment by Nareese** [comment]
The betterttv API is not officially supported for external use, is subject to change or removal without notice, and the v2 API has been deprecated for quite some time now (since the release of the new website).  night made some fairly major internal changes to the website and API last night, so it is quite possible that he has removed all support for those endpoints on the v2 API.  See issue #3593 for additional details.  Unfortunately, since the extension doesn't use that endpoint, there is no immediately obvious example you can use for the syntax of that endpoint on v3, but maybe night can comment further.

**Comment by night** [comment]
Names are non-unique in our system now, so if multiple users have the name `dafran` it will just pick the first it finds. Please migrate to v3 of our API to fix this, as v2 will not be fixed.

**Comment by night** [comment]
update: looks like shared emotes were not being handled properly. this should be fixed now.
