### ISSUE TITLE
Picture in Picture

### ISSUE THREAD

**Issue by Rikunda** [night/BetterTTV#3724]
I cannot disable it, and the button ends up exactly where "Fullscreen" was.  Can we get an option to disable this "feature"?

**Comment by Nareese** [comment]
IMO, the better solution here is not to provide an option to disable it, but simply move the button to the other end of that button row, to the left of the settings cog, instead of to the right of fullscreen, breaking people's UX familiarity.

In the interim, you can install a CSS override extension like Stylus if you don't already have it, create a new ruleset for www.twitch.tv and add the following rule to it:
```
#bttv-picture-in-picture {
    display: none !important;
}
```

**Comment by Rikunda** [comment]
Why not both?

**Comment by Nareese** [comment]
Historically, night has been leery of "option clutter"... if there is no downside or the vast majority of people would never need or want to disable something, it doesn't need an option making the settings screen even more cluttered than it already is.  The only reason why someone would need to disable this feature is because it's current positioning breaks a long established UX for where the fullscreen button should be.  If the button is moved somewhere that it doesn't break people's UX habits, there is really no need to disable it... if you don't want to use the feature, just ignore the button.  If you really want to completely disable it (presumably permanently), feel free to use the workaround above.

There is a long standing intention to someday redo the settings screen and options handling, to allow for a greater variety of settings customization than just simple on/off, and also to allow settings to be grouped and categorized, which will help with the clutter.  If and when that redo ever happens, then the environment may be better to allow for more things to have options settings.

Obviously, I don't speak for night or for the project officially in any way, so he may feel differently in this case, and be willing to implement such an option... but I wouldn't bet on it, and hence why I supplied the workaround until the positioning can be fixed.

**Comment by schoerg** [comment]
Another problem: if you enable PIP and then go fullscreen, the PIP window will stay and the main window will be black.

**Comment by Nareese** [comment]
Of course.  The current positioning is definitely a UX issue and needs addressing.  I was just commenting on the issue having an option to disable it.  Until the positioning is dealt with, people can use the Stylus workaround above to hide the button.

**Comment by Tinchox17** [comment]
any news on this?

is really annoying clicking the picture in picture by accident everytime.

**Comment by whitecrownclown** [comment]
@Tinchox17 There is a PR open for changes on this. We're waiting on a review from the owner.
