### ISSUE TITLE
Translate double click not working

### ISSUE THREAD

**Issue by shortnproud** [night/BetterTTV#373]
When double clicking a message in twitch it is not translating. I asked a fellow mod/friend and theirs isnt either.

**Comment by voloshink** [comment]
The translate feature was removed

**Comment by shortnproud** [comment]
Any plan for it to return? As an English speaking mod we get random comments that are foreign and don’t know what it says.

 

Thank You,

 

John

**Comment by night** [comment]
Since we'd have to pay Google to offer translations now, we are not offering translations any longer. It's possible if we were to add a subscription model to BetterTTV we might make that part of the subscription, since we could then afford its cost. We are not sure when or if a subscription model might be added, however.
