### ISSUE TITLE
Messages containing @(My Username) Are not appearing Highlighted Red.

### ISSUE THREAD

**Issue by TJOxbow** [night/BetterTTV#3804]
About a month ago, I noticed that out of nowhere messages containing @(My User Name) were not appearing highlighted red. I didn't think much of it, but now it's getting quite annoying. I've tried uninstalling Bttv Extention and reinstalling. I even Factory reset Google Chrome. Neither one of those worked. I've looked through the setting in Bttv twitch and can't find anything that would cause the messages not to highlight. I do not want to add my user name to Set Highlighted Keywords because I have the setting on that makes a sound when a Keyword is said, and so every time I would talk it would make that noise.

**Comment by Nareese** [comment]
Sorry, but this is not possible.  Highlight Keywords IS what highlights your username.  When you initially install BTTV, before you have set any highlight keywords, your username is added to the list automatically to enable that highlighting.  If you manually add keywords to the list, it no longer automatically adds your username, and you must add it yourself if you want it to continue to be highlighted.  Obviously, because of this, there is no way to have notification sounds for other keywords and not for your username.  Note that uninstalling and reinstalling has no effect on this, as uninstalling does not remove your settings and keyword configurations.

**Comment by night** [comment]
We default the value of highlighted keywords to your username. If you changed your Twitch name you need to update this value to your new name. If you place parentheses around your name it will highlight when you speak and make the noise, so just place your username itself in the list without parentheses and it should work fine.
