### ISSUE TITLE
Add Hosted Chat to Hosted Channels

### ISSUE THREAD

**Issue by Shadowbandit** [night/betterttv#383]
When a channel hosts another have a function where the chat cuts in half with the Host and the hosted channel chats together or their chat on the other side of the page.

**Comment by night** [comment]
While we could add an additional chat in an iframe, I'm not sure how well this would work.

**Comment by Yrlish** [comment]
I see the potential here with seeing both chats, but wouldn't it look bad on smaller screens for example: we split the current chat's height in half and puts the two chats there.

But yea, I like the idea because I am missing that thing myself when watch channels that hosts other channels. But the thing is, how to implement it in a good way.

**Comment by moistmann** [comment]
maybe add something like a delayed auto change to the new channels chat with the timer being shown with an x somewhere on it to cancel the change as well as a change now button and maybe add the new chat to the the group chat menu so we can change between them at ease if need be? I know that at least for all the channels I watch after like 30 seconds to a minute almost all chat has ceased so the only real place worth chatting would be the new channel. not sure how feasible or used these would be just adding my 2 cents

**Comment by id1740** [comment]
this will be the best feature

**Comment by Codonbyte** [comment]
You could just use tabs the way multitwitch.tv does. This would be super convenient for raids.

**Comment by night** [comment]
Hosting is being removed on Oct. 3, making this feature request obsolete.
