### ISSUE TITLE
Unable to Adjust Font Size

### ISSUE THREAD

**Issue by MaHoDy** [night/betterttv#3877]
I'm using the betterTTV chat feature which is "Set Font Size" for twitch chat, and this feature is not working anymore no matter if I changed the font size in that option or not. Please, fix this bug, because, I'm having a problem right now with reading twitch chat at the moment.

Thank you.

**Comment by Nareese** [comment]
This bug has been fixed in the latest version released last night (7.2.79).  If you are using Chrome, however, you will have to wait for Google to approve and release this new version, which can take up to 2-3 days.  If you are using any other browser, it should already have updated, and if not, you can force an update check.
