### ISSUE TITLE
Error on Host button

### ISSUE THREAD

**Issue by faudinha** [night/betterttv#3880]
I have encountered a problem regarding the host button, since even after turning it on, the button doesn't appear even after refreshing the page multiple times..

![image](https://user-images.githubusercontent.com/65304791/81844123-8469d880-9546-11ea-921a-8cfe0f444ed6.png)

**Comment by Nareese** [comment]
This bug has been fixed in the latest version released last night (7.2.79). If you are using Chrome, however, you will have to wait for Google to approve and release this new version, which can take up to 2-3 days. If you are using any other browser, it should already have updated, and if not, you can force an update check.
