### ISSUE TITLE
BetterTTV timeout wheel stops working from time to time

### ISSUE THREAD

**Issue by lyniakk** [night/betterttv#3907]
After Twitch redesign, I have a problem with BetterTTV, when I moderate chat and I want to use timeout menu, it doesn't show up and I have to F5. Sometimes it doesn't work even after F5. 

Thanks

**Comment by night** [comment]
I assume this is related to the Twitch channel redesign. Unfortunately since my account is not in the experiment I cannot fully test the redesign, but it is working reliably from what I am able to test. Until I'm able to reproduce this it's not able to be fixed.

**Comment by xgerhard** [comment]
Some additional info, I can reproduce this, the timeout selector is positioned far outside the window.

Not sure exactly what changed in the new design, BTTV calculates the CSS left property, now this left property is applied from the chat window, instead of the left side of the window (hope this make sense lol).

This change fixes the position for me:
```js
$customTimeout.css({
    top: $target.offset().top + ($target.height() / 2) - ($customTimeout.height() / 2),
    // left: $chat.offset().left - $customTimeout.width() + $chat.width() - 20
    left: $chat.width() - $customTimeout.width() - 20
});
```
