### ISSUE TITLE
New Channel Layout Breaking Disable Host Mode

### ISSUE THREAD

**Issue by OreoCupcakes** [night/betterttv#3933]
Twitch has a new layout that it's slowly rolling out to users.

It breaks auto host mode and probably some more features that I don't use.

Windows 10 18363.778
Chrome 83.0.4103.61

**Comment by deniz87** [comment]
please fix this

**Comment by Harlecorn** [comment]
They keep closing bug reports about this without actually fixing it. Disable hosting still isn't working and it's extremely frustrating.

**Comment by lucasramosoviedo** [comment]
having the same problem

**Comment by deniz87** [comment]
@Harlecorn they are probably closing them because they are duplicates of this report. But yeah same for me.. its very frustrating to not have this feature working yet...

**Comment by night** [comment]
Unfortunately because Twitch's new channel page uses React hooks, it's unclear how to resolve this issue at present. I have spent hours looking into this over the span of a few weeks but haven't found a good way to detect this behavior and prevent it without making destructive changes to Twitch's components (which goes against our extension development philosophy). It might just be that this can no longer be supported.

**Comment by deniz87** [comment]
There is always a way. There must be :(

**Comment by Px05119** [comment]
Disable host mode used to work, even with the redesign, on the Mod View page. It no longer works as of 4 August. Did Twitch change the mod view, or was the code removed since it no longer worked for the majority of users?
