### ISSUE TITLE
Multiple issues with emotes menu lazy loading

### ISSUE THREAD

**Issue by Timsonrobl** [night/betterttv#3998]
I've been investigating the problems I'm having with emote menu similar to this issues:
#3002
#2941
The problem manifests when channel have relativity large amount of emotes and some of them are getting stuck in unloaded state and it looks like this:
![2020-06-25 153924](https://user-images.githubusercontent.com/9917883/85721504-17776000-b6fa-11ea-8adc-4615cd980ad8.png)
(testing channel - https://www.twitch.tv/guit88man )
Note that all not rendered icons in this screenshot have undefined scr attribute like this:
![2020-06-25 154043](https://user-images.githubusercontent.com/9917883/85721686-4392e100-b6fa-11ea-8d46-718451f90427.png)
So it is not problem with resource loading but rather plugin logic.

Scrolling up and down the menu will sometimes get icons to "unstuck" if you move them completely out of viewport and then return. Usually you have to get them in a few goes so my guess is firing too many IntersectionObserver events at the same time causes them to be not handled properly.

The second issue is related to this problem - closing and reopening emote menu will cause all already loaded and rendered emote img elements outside of viewport to have their src attribute unset. When returning to viewport by scrolling they may or may not regain src attribute as per the original issue. This means that at this point lazy load IntersectionObserver listeners are either not destroyed properly or recreated at some point needlessly firing every time the menu is reopened.

Reproducible in Chrome 83 on Win10 x64

**Comment by aleksandrpnshkn** [comment]
Same kind of problem sometimes (I don't know exact cause) occured in Firefox (now) and in Chrome (long before). In half the cases when you first open the panel after loading the page, only some emotes (in my case favorites) are properly loaded. Can be fixed by reopening the panel or scrolling emotes.

Firefox 77.0.1 Ubuntu 18.04

![снимок_14](https://user-images.githubusercontent.com/40536746/85734689-3e3f9180-b70e-11ea-86d9-7724e30a3c09.png)

**Comment by night** [comment]
The emote menu works reliably for my machine, so I'm unsure why you are experiencing this issue. When the emote menu is opened we do load all emotes in the view: https://github.com/night/twitch-chat-emotes/blob/master/src/plugins/lazyload.js#L90

If you have reliable repro steps I can take a closer look, but otherwise this really can't be fixed as it cannot be reproduced.

**Comment by Timsonrobl** [comment]
This is some kind of race condition or performance related issue as if I experiment in small window I cannot reproduce it but in maximized 1080p windows I can get it constantly. In most cases is happens if you scroll the menu while emotes are in the process of loading or it happen on the last row on emotes that were partially visible before scroll and won;t load after scroll.

At least you can reliably reproduce the fact that all emotes outside viewport gets unloaded even if they were already loaded during the previous time menu was opened. This cannot be correct logic.

**Comment by sensor** [comment]
I'm having this issue as well. Only on one computer. One potential fix would be to add loading="lazy" attribute in the src/templates/emote.html <img/> tag. That way those browsers which support the integrated lazy loading would load the image. I'm willing to test a developer build if someone makes this change.

**Comment by Timsonrobl** [comment]
@night maybe you can reproduce this issue using Chrome DevTools CPU throttling if it's performance related? It still persist for me and many other people.
