### ISSUE TITLE
Auto-Theatre Mode does not consistently work

### ISSUE THREAD

**Issue by FlynnChurch** [night/betterttv#4005]
As said in the title: going to a stream player page with Auto Theatre Mode on works perhaps one out of five times; most often it never engages at all.  Speculating, I would guess changes to the stream player page to accommodate the new info block under the player (and anything else, I don't claim to know intimate details) have made whatever method BTTV uses for ATM non-viable.

Chrome Version 83.0.4103.97 (Official Build) (64-bit), though this has persisted through Chrome updates; Windows 10 Pro; BTTV extension 7.2.82.

**Comment by night** [comment]
We do a best effort enable of automatic theater mode, but because Twitch "reloads" the page to enable the redesign the enabling to theater mode can be canceled. BetterTTV does attempt to enable it multiple times over the span of 3 seconds, but if your computer is slower than that to load the page, it may fail.
