### ISSUE TITLE
DarkenTTV Extra Feature Idea 

### ISSUE THREAD

**Issue by risey** [night/BetterTTV#402]
I love the dark mode that BTTV incorporates into its features, but It would be nice If I could have the option to darken just the chat and not the rest of the site, and vise versa. I would love to use the rest of the site in "dark mode" but have chat still be the default Twitch color.

**Comment by night** [comment]
Unfortunately BetterTTV's darkened CSS for the chat is too intertwined with the rest of the site's theme in order to split the two up. In other words, splitting chat and the rest of the site would be a long and daunting task for us to accomplish. Since most users seem to enjoy the entire site dark, those are our target users for the darken feature.
