### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by cariposadar** [night/betterttv#4053]
When I try to sign on to BTTV I get this error message

{"status":401,"message":"invalid csrf token"}

**Comment by Nareese** [comment]
This error is caused by Twitch, not us (as you can see by the url of the page where this error appears, which is on `id.twitch.com`).  You can usually resolve this by clearing your twitch cookies and logging in again, or by using an incognito/private browsing window, which will ignore your existing cookie.  If that doesn't resolve it, however, there's nothing we can do about it, and you'll have to contact twitch for further help.
