### ISSUE TITLE
[Feature Request] Setting your own buffer per stream

### ISSUE THREAD

**Issue by StoneColeQ** [night/betterttv#4078]
There are extensions out there that can speed up the player slightly to reduce the buffer over time so we know that's possible. I'm asking for a feature where you set the delay to say 5.33s and it will speed up and slow the player down to match this. Why? For when you're watching multiple streams and need them to be sync'd.

The buffer changes every second so it might be a bit tricky. Maybe average buffer over 5s?

**Comment by night** [comment]
it's not possible to configure the buffer as this happens within the native player code itself.

**Comment by StoneColeQ** [comment]
The way I worded it was confusing. I meant if it was possible to read the buffer that it shows and change the speed of the player around that. Regular html5 video speed controllers work so I don't think messing with the player directly is necessary.

**Comment by night** [comment]
Playback rate cannot be configured for Twitch's live video player. You're welcome to attempt this yourself, but since the video chunks are <2s and Twitch forcibly loads chunks into the video element, we cannot control this without being able to control the custom video player Twitch built around HLS.
