### ISSUE TITLE
BetterTTV 7.2.86 only partially working in Firefox 80.0

### ISSUE THREAD

**Issue by LigH-de** [night/betterttv#4122]
Add-on is installed and configurable. I am logged in to Twitch. BetterTTV entry does not appear in my Twitch account menu, so I am unable to customize it. Previous customizations (e.g. hiding Prime Loots or Recommended Channels) are not working in stream list pages (e.g. currently live followed channels), only when I watch a stream.

**Comment by Nareese** [comment]
7.2..86 saw a fairly major reworking of a number of components under the hood of BTTV, and there were some bugs.  You should be able to access the BetterTTV Settings panel from the "gear" menu of any chat.  Some features not being functional on non-channel pages has already been fixed for the next release.  Additionally, once you have visited a channel page, all of the previously non-functional features on other pages should start working. including the BetterTTV Settings entry on your account menu, unless you refresh on a non-channel page, so that's a workaround for the moment.  All of these will be fixed with the next release.

**Comment by night** [comment]
fixed via 496679dbf4d088b99a258d19be5418853223eea7
