### ISSUE TITLE
Ability to change the chat box height

### ISSUE THREAD

**Issue by Maxhype** [night/BetterTTV#416]
I would like to change the chat box height, because creating commands with bigger chat box would be so much easier, I know I can change the width be using mouse to drag the chat window but it makes the video smaller.

I tried to use Stylish also and I managed to make it bigger but then the buttons below chat goes top of the chat box. I can not find Stylish command to move the chat box little higher.

**Comment by night** [comment]
You can widen the chat on channel pages, which increases the textarea size. We will not, however, add the ability to change the height of the textarea, since multiple of the items on top of the chat input area are height dependent (making it a less than simple CSS change). If you use a bot like Nightbot or Moobot, commands can be added from the bot's control panel.
