### ISSUE TITLE
Reverse Chat Message Direction broken

### ISSUE THREAD

**Issue by MatuTiemersma** [night/betterttv#4166]
Hello my BetterTTV stopped working both on Chrome and Edge suddenly, I already followed all the BetterTTV debugging steps. I think it has to do with me using the Reverse Chat Message Direction option, but now I can't even access the BetterTTV options cause they don't show. I'll send a screenshot of my JavaScript Console. I hope someone can help, thank you for your time!

![image](https://user-images.githubusercontent.com/66216163/94853812-51938480-0402-11eb-814e-8b35d38a5035.png)

**Comment by Nareese** [comment]
I can confirm that your speculation that this is related to reverse chat direction is correct.  As you noticed, unfortunately, this error is causing BTTV to completely fail to load, so fixing it is actually rather tricky.  I can give you some steps to follow to manually fix Chrome, but I'm not sure what to do about Edge for you.  

BetterTTV stores its settings in browser LocalStorage, so to fix this, we need to manually examine and edit local storage.  In Chrome, you can start by pressing F12 to bring up the Developer Tools console.  On the top menu bar, if the item "Application" is not visible, hit the >> icon at the right end, and select Application from that menu.  On the Application page, go down to Storage -> Local Storage and select https://www.twitch.tv inside there.  A bunch of data will appear on the right side panel, and at the top is a "Filter" box.  Type in "bttv_rev" in there, and you should see the key for bttv_reverseChatDirection, value "true".  You can either double click on the value and change it to "false", or you can right click on the key and choose Delete, since the default value for the key is also false.

This will at least get the rest of your BTTV working again in Chrome until this bug can get looked at.  You would need to do something similar in Edge, editing local storage and changing that key, but I have not used Edge much at all and do not know what tools are available for that on Edge, or the steps to do it.

Thanks for the report.

**Comment by MatuTiemersma** [comment]
Thank you for the information! Hopefully it gets fixed soon!

Take care!
