### ISSUE TITLE
Feature Requeset: Hiding Popular Channels

### ISSUE THREAD

**Issue by Zetta269** [night/betterttv#4251]
Would be awesome to be able to hide the Popular Channels section. See link that has a screenshot to explain it better.

https://community.nightdev.com/t/hide-popular-channels/28654/3

Thank you.

**Comment by Nareese** [comment]
Unfortunately, this feature is currently (and has been for a long while now) a Twitch "experiment" that is rolled out to only a small number of users, which doesn't (currently) include any of the developers.  Since we can't see it, we can't fix it.  When this feature was first released mid last year, I had this section for a brief time, and at the time, it did not contain any id or class information that would make it uniquely identifiable, thus making it very difficult to hide, except with fragile, non-unique CSS selectors.  You can find my issue for that at #3484 along with the fragile selector I used at the time.  I have no idea whether it would still work, or whether a more robust solution is possible now, because as mentioned, none of the devs are seeing that section right now.

**Comment by night** [comment]
handled via e523c4e3b71b0c690ec4c2f45212407ed3729b89
