### ISSUE TITLE
[Feature Request] Always enable timestamps

### ISSUE THREAD

**Issue by bottleblue** [night/betterttv#4295]
Can we have an option to always enable timestamps? I always have to manually enable it.

**Comment by Nareese** [comment]
There should never be a need to "always enable" timestamps.  Timestamps are a Twitch feature, not a BTTV feature, and if you enable them, Twitch will remember you enabled them.  If it does not, it is likely because you are deliberately deleting site data/local storage and that is preventing Twitch from remembering it.  So check your browser for settings/extensions that delete or "clean up" that data. (Chrome, for example, has the setting "Clear cookies and site data when you quit Chrome")

**Comment by bottleblue** [comment]
Yes I am deleting site data/local storage through Firefox's offline website data option because other websites leave junk in it that never goes away unless I do that. Otherwise I would have to go into Firefox's folder and look through the subfolders to find out what to delete and what to keep which is a pain.

I don't know what you mean by "not a BTTV feature". BTTV enhances many of Twitch's existing features. For example automatically claiming bonus channel points. Channel points are a Twitch feature also right? 

Anyway is it possible to do this?

**Comment by Nareese** [comment]
Is it possible?  Yes, in theory, anyway.  Is it something that we are likely to do?  No, because it is not an issue that affects even a tiny handful of users.  Additionally, even if we were to add such a setting, the default setting would be off, so you would have to turn it on, and we would have to save that setting.  We save it the same way twitch does, in the local storage that's going to get deleted.  So you would have to reset it every time in BTTV too.  All that's doing is kicking the problem up a level.

The reason it matters that it is a Twitch feature and not a BTTV feature, is that night is not likely to add additional complexity and code to maintain to BTTV to do something that Twitch's website already does.  Twitch's website has a timestamp setting.  Twitch's website remembers that setting. The issue here is that you've chosen to use settings that prevent your browser from remembering your Twitch settings.  It doesn't make a lot of sense to then complain that it doesn't remember your settings.  The solution to this problem is to allow your browser to save your settings.

**Comment by bottleblue** [comment]
I have a backup file of BTTV's settings I could just load that so if the timestamp feature was in there it would be fine. 
I don't see a way to block all site data/local storage by default and whitelist only in Firefox so I don't have a choice but to delete all of it periodically. It would solve everything if BTTV saved its settings in the extensions folder.

**Comment by night** [comment]
BetterTTV stores settings in the same place as Twitch, so if your Twitch settings are being wiped so would ours. You will unfortunately need to change how your browser is configured to keep settings on close.
