### ISSUE TITLE
emotes not working

### ISSUE THREAD

**Issue by Bu88er** [night/betterttv#4377]
so i have checked on gifs and exstra emotes BUT  KEKW Sadge omegalul etc etc etc dosent work i only see the text of them not the emote itself

**Comment by Abrams-ZiZi** [comment]
I'm having the exact same issue.
Windows 10
Chrome 88.0.4324.190
BetterTTV v7.2.91

**Comment by Abrams-ZiZi** [comment]
I figured out what my issue was, in the Chrome extension I had BetterTTV emotes enabled but FrankerFaceZ disabled.
Enabling FrankerFaceZ got me KEKW, and all those other emotes.
Hope this helps!

**Comment by Bu88er** [comment]
cheers worked also it worked getting another extension with twitch emotes,
but when hover over them you don't see the text just the emote, but guess
its better than nothing :)

Den søn. 28. feb. 2021 kl. 20.29 skrev Abrams-ZiZi <notifications@github.com

**Comment by xgerhard** [comment]
Using multiple Twitch extensions will most likely result in unwanted behaviour, since they will conflict.
You can enable all the emotes in your settings, theres 3 different settings. 
If you enable the BTTV emote menu setting, you can check which emotes are available in the channel.

If your issue is resolved you can close the issue :)
