### ISSUE TITLE
Disable autoplay of past stream on non-live channel homepage

### ISSUE THREAD

**Issue by bbcmpc** [night/betterttv#4405]
Request to add an option to disable autoplay of video when visiting a non-live channel's homepage (e.g., visiting https://www.twitch.tv/[USERCHANNEL] while user is offline displays message "OFFLINE Check out this Just Chatting stream from X days ago" and begins automatically playing the referenced video).

**Comment by Numerok** [comment]
this is bothering me as well, also when the channel is live it overlays the stream and no way to pause it until you go to the stream page and press pause there. Also it automatically redirects to hosted channels while in background. I hate to always back out of them.
Hateful, hateful changes!

**Comment by sguergachi** [comment]
Yes please, would like to see this feature too!

**Comment by yrogerg77** [comment]
I just installed this add-on on both Firefox and Chrome, and this issue is precisely why I installed BetterTTV in the first place... are you guys trying to tell me that NONE of those auto-play toggles in the settings cover the video at the top of a channel's videos page? What are they for then? The VOD page is the only page on Twitch that I typically visit, and while I appreciate that other people might like the various other features of this add-on, I currently see it as broken and almost useless without being able to disable ALL autoplaying videos on the site. Please PLEASE add this feature. Otherwise I really don't see the point in keeping this add-on installed.

**Comment by Musouka42** [comment]
I know making an addon like this takes loads of time and effort, and I very much appreciate the work put into it.  But this issue has been open for over a year at this point.  Is there any ETA on when this feature may be implemented?
