### ISSUE TITLE
Hide community highlights not working

### ISSUE THREAD

**Issue by Oracidrep** [night/betterttv#4482]
I find that often that switching "hide community highlights" to on does not hide them, instead it just pushes them up over the gift sub/ bits leaderboard. Additionally, I find that the feature just flat out does not work on predictions.

**Comment by night** [comment]
I am not able to reproduce any misbehavior with the hide community highlights feature. We do not block all types of community highlights. Predictions, polls, and some other kinds of highlights we explicitly allow due to user feedback. We may offer more flexibility for configuring types of highlights to hide in the future.
