### ISSUE TITLE
BTTV only watchable stream in theater mode

### ISSUE THREAD

**Issue by CFTiffers** [night/betterttv#4516]
Hi,

I have had this problem for sometime where if I do not have the twitch stream in theatre mode I get something like this.

My BTTV is up to date I have tried to uninstall reinstall previously, the issue does not happen if BTTV is disabled extension.
![image](https://user-images.githubusercontent.com/57853073/118277907-3ec94e00-b4c1-11eb-9169-79984654aebe.png)

**Comment by Nareese** [comment]
I am unable to reproduce this behavior in either Chrome or Firefox, however one other user reported this issue, and he indicated that the problem is related to the `Left Side Chat` feature.  It is likely that you either have some other conflicting Twitch extension that is messing up BTTV's left side chat, or possibly Twitch is giving you a testing version of the site that messes it up.  Disable any other Twitch modifying extensions, and if that's not it, then your only choice is probably to disable left side chat, and that should resolve it for you.  Unless we can reproduce it, however, it is unlikely we will be able to make a general fix.

**Comment by CFTiffers** [comment]
Yes I have the left side chat on as well - the issue does not happen with standard, I will try and see what other extensions can be disabled.
