### ISSUE TITLE
Unable to view BetterTTV Settings

### ISSUE THREAD

**Issue by Pomerschen** [night/betterttv#4534]
I'm currently unable to view BetterTTV's settings on twitch. There is no button for BTTV settings on the dropdown.
I'm still able to view animated emotes in chat, but the emote menu is twitch's default now and I see no BTTV emotes in the emote menu.
I've cleared my cache, disabled other extensions, and re-downloaded BTTV, but the issue was not fixed

Firefox Version 88.0.1 BTTV Version 7.2.96
_https://cdn.betterttv.net/cdn-cgi/trace loads and result is below_
fl=27f212
h=cdn.betterttv.net
ip=2601:cb:427f:834e:9016:ea5e:c1ae:988f
ts=1621286324.294
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
colo=ATL
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off

**Comment by Nareese** [comment]
The profile dropdown menu BetterTTV Settings entry is indeed broken due to some CSS changes made today by Twitch.  You can still access the BetterTTV Settings menu from the "gear" menu button in any channel's chat.

BetterTTV has not ever modified or put its emotes on Twitch's emote menu.  That is why we supply our own menu with the BetterTTV Emote Menu option.  If you had BTTV emotes on that menu previously, some other extension was doing that.

Note for night:  tw-full-width and tw-relative have been replaced with obfuscated class names on the parent div.  parent() alone or parent('div') works, but I assume you more narrowly qualified it for a reason, so I'm not sure how you'd want to address that. https://github.com/night/betterttv/blob/7b7171d9e378e533866ce1c338483299d77f17b3/src/modules/settings/index.js#L206

**Comment by Pomerschen** [comment]
> The profile dropdown menu BetterTTV Settings entry is indeed broken due to some CSS changes made today by Twitch. You can still access the BetterTTV Settings menu from the "gear" menu button in any channel's chat.
Thank you
