### ISSUE TITLE
Auto-Claim Drops

### ISSUE THREAD

**Issue by Tunami52** [night/betterttv#4588]
A feature to auto-claim completed twitch drops as some drops require previous ones to be claimed.

**Comment by Ricardogwz** [comment]
I just have an ideia for the auto-claim bonus points, add a feature that enable us to select what streams we want to activate the auto-claim, because at least for is better activate just in some streams ,i don't know how hard it is, but would be so good for me.

**Comment by JaseYANG** [comment]
Is this enhancement  coming soon?

**Comment by OnlyStevie** [comment]
Definitely agree that this would be an amazing tool, particularly for Marbles on Stream/Call of Duty. There is a tab that pops up above the chat text box when you hit the required timing, so I'd hope this could be made possible!

**Comment by juanca** [comment]
I made a bookmark for this during the EFT drops but would prefer to see it in this extension:

```
javascript: setInterval(() => {   e = Array.from(document.querySelectorAll('[data-a-target="tw-core-button-label-text"]')).find(e => e.innerText === 'Claim'), e && e.click() }, 5000), undefined
```

That works for the actual stream. It kinda works on the drops inventory page but it requires a refresh which misses the point on a bookmark.

Hope it helps!

Otherwise, I can try to make a PR later this month.
