### ISSUE TITLE
Personal emotes not working

### ISSUE THREAD

**Issue by KCVoorhees** [night/betterttv#4646]
My personal emotes are not working in any twitch channel but my own. Ran a traceroute and got Unable to resolve target system name http://cdn.betterttv.net/.

**Comment by Nareese** [comment]
You can't run a traceroute to `http://cdn.betterttv.net/`.  That is a web URL, not a DNS name.  If you want to traceroute to something, traceroute to just `cdn.betterttv.net` (which definitely does exist and is a valid DNS name).  It is, however, extremely unlikely that the CDN is you issue.  If you were unable to reach the CDN, you would not see *any* BTTV emotes, not just personal emotes.  More likely, something is blocking your access to the web socket that BTTV uses to propagate channel joins and broadcast emote sets for BTTV Pro users.  See the debugging information in this issue if you would like to investigate that possibility.  #4381

**Comment by DorCoMaNdO** [comment]
Both my friend and I are connected to the socket according to the console logs, we don't get disconnected, their emotes still don't appear correctly.

**Comment by Nareese** [comment]
In that case, I have no idea how that can be.  Please provide as much detail as possible... your channel names, the name of the channels you're in while testing, the emote codes for the personal emotes you're testing with, screenshots, etc, and maybe night can figure something out from that.   There have been a few people report this recently, so obviously something is going on, but it's a tiny subset of people who have Pro, so there must be some other factor.  Unless we can somehow figure out what's different for the people having this issue, it will be pretty much impossible to say why it's happening.

**Comment by DorCoMaNdO** [comment]
My channel is `DorCoMaNdO`, my friend's is `theamandashow`, the emote code is [shLove](https://betterttv.com/emotes/60b70f4bf8b3f62601c372e9), uploaded by my friend, the emote previously appeared in a few of the channels we watch together and still appears in her channel (since it's an uploaded emote there).
The channels we view and chat on are `KYR_SP33DY` where I moderate and use mod view, `TheDeluxe4` where she moderates and uses mod view, we also watch `TheG18` and `SideArms4Reason` among others, with normal views, the emote doesn't appear anywhere, it previously appeared in all these channels, though initially it didn't work in the channel she moderates unless she opened another instance of the channel or chat outside of mod view (suspected to potentially be caused by the errors I reported in #4587), this workaround no longer works for at least a week now.

**Comment by night** [comment]
in general as long as you're connected to the socket you should be broadcasting your emotes when you send messages to chat. I am unable to reproduce any issues with that functionality. If problems persist please provide explicit reproduction steps and perhaps we can reproduce it using them.
