### ISSUE TITLE
hide "streamer's follower also watch..."

### ISSUE THREAD

**Issue by Monkey151546** [night/betterttv#4673]
So as the title says, there is a new feature on twitch, that is "X followers also watch" (X being the streamer's name) on the left side, below your followed channels, I'm wondering if it's possible to have a setting to hide it. 

![image](https://user-images.githubusercontent.com/11801179/125639817-ceb75a27-38b2-4111-8a51-6edf18daaa23.png)

**Comment by Nareese** [comment]
I am not seeing this section.  It is likely that this is a Twitch "experiment" that is rolled out to only a limited subset of users.  Unfortunately, unless the feature is fully rolled out to all users, so that the developers can see the code and hopefully identify something unique in it that can be used to hide it, we probably won't be able to do so.

**Comment by MartijnWelker** [comment]
This section is already hidden by the `Featured Channels` sidebar settings. Does it make sense to give it its own setting?
![image](https://user-images.githubusercontent.com/6674662/193623978-20c449a1-c326-4236-bb66-4e31ee4ddf7c.png)

**Comment by night** [comment]
It looks like this was added to the featured channels sidebar option earlier this year. If you're still seeing these with this setting enabled, please let us know.
