### ISSUE TITLE
Spoiler markdown

### ISSUE THREAD

**Issue by Barmem** [night/betterttv#4687]
I would really love to have spoiler markdown, if you want to send message that could be a spoiler for streamer or audience it would be perfect

**Comment by night** [comment]
Thanks for the request. Unfortunately because markdown like this only benefits users with BetterTTV, the text may end up getting spoiled for users without the extension. For this reason it might not be a great feature to add as it can ruin the experience for users not using the extension. We like to focus on value adds features which don't negatively affect non-users.

**Comment by Barmem** [comment]
it could be easily solved by encrypting messages

**Comment by Barmem** [comment]
@night i guess it wont be reopened?

**Comment by night** [comment]
@Barmem Thanks for following up, as your reply got lost in a sea of emails. I think encrypting the messages is something that could work, but we could simply encode the message differently rather than using encryption. The problem with doing that is it still ruins the experience for users not using the extension. Folks on native chat or third party chat apps won't be able to see the contents of the message at all.

**Comment by Barmem** [comment]
@night alright, thanks for your reply, it's so frustrating that twitch doesnt have that functionality natively.
