### ISSUE TITLE
Issue with Highlight Keywords

### ISSUE THREAD

**Issue by Lyviq** [night/betterttv#4688]
I turn off this option in the settings, that is, I delete my name, but every time I renew the twitch or enter twitch again, my name appears in that option again. This option makes you appear red when someone tags you in the chat. I'm turning this off because I don't want it. I'm tired of doing this all the time. It was the same in the previous setting menu. Can you please fix it?
I also tried to download the settings and then import them, even if the other options are loaded correctly, my name is still displayed in this Highlight Keywords option.
Sample video:

https://user-images.githubusercontent.com/65573658/126541536-f8910323-85d7-41ef-ae82-414994124cce.mp4

**Comment by Nareese** [comment]
There is a fix for this in a pending patch.  Currently, when the list is empty, it automatically adds your name back in.  This is done because the vast majority of people expect their name mentions to be highlighted out of the box, so it configures it that way any time the list is completely blank.  In the new version, it will only do this when the list is completely unset, ie. on first installation.  

In the mean time, you can work around the problem by deleting your name, and then adding a string of meaningless letters that will never be matched (like "kjhfalskdjhfsadf" or something).  This will prevent the list from being empty and your name automatically added back in.  Once the next version releases, you can delete the nonsense string, and it should continue to leave the list completely empty.

**Comment by night** [comment]
fixed via dbe1dcb5bbf7760c2f4bb8635bf72f3047e3eb42
