### ISSUE TITLE
Move Import/Export Settings

### ISSUE THREAD

**Issue by v1rx** [night/betterttv#4725]
Should either have its own tab or anywhere else than in the "About" tab.

**Comment by night** [comment]
Thanks for the suggestion, however we are comfortable with where they ended up based on usage history. There's a bit of a learning curve with any change, but now you know where it is.

**Comment by hendycholl** [comment]
I agree, it's not intuitive at all. I literally had to google this

**Comment by catDcat** [comment]
I have my browser on private mode, so my add-ons data are automatically cleared every time I quit the browser.  I used to change BetterTTV settings manually every single time I close and reopen my browser because I thought the `export settings` feature does _not_ exist in BetterTTV. After 6 months, I have now just found out about it. In other words: I agree with OP and the comments, its current placement is not intuitive at all. I don't see how exporting/importing the settings are relevant to a tab that is typically reserved for information about the app and its publisher.
