### ISSUE TITLE
Store settings natively instead of via browser cookies

### ISSUE THREAD

**Issue by You-Schmuck** [night/BetterTTV#473]
Tried Googling and searching the forums but couldn't really see any answers. Would it be possible in future to have the Chrome extension store settings natively in the extension like most do rather than using cookies? 

I'm in a situation where the browser has to delete cookies on exit. (Shared computer) So any accounts that just so happen to still be logged in get logged out.

But sadly this has the side effect of constantly needing to import BTTV's settings back in every time with a few refreshes to make sure they all work right. I read on another ticket that settings were going to be looked into being revamped. Would it be possible to have this as a welcomed addition? Thanks for reading.

**Comment by vendethiel** [comment]
They're stored in localStorage, not cookies IIRC. Though that probably gets cleaned as well

**Comment by night** [comment]
In order to avoid writing support for [multiple](https://developer.mozilla.org/en-US/docs/Adding_preferences_to_an_extension) [storage](https://developer.chrome.com/extensions/options) [handlers](https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/ExtensionSettings/ExtensionSettings.html) and maintaining these settings lists for extensions on every single browser we want to support, we use localStorage (which is easily cross-platform) instead.

With that said, we wish clearing cookies didn't clear localStorage, but that's not something we have control over. In this day and age, there's not really a point to clearing cookies. Both Chrome and Firefox support multiple user profiles, and on your computer you can use multiple accounts to further segment user sessions. Personally, anything I care to remove instantly on window close I use private/incognito mode for.

We are planning to sync settings server-side (you could then just login to BetterTTV, and it will load your settings), but I do not have exact an ETA of when that will happen (it's dependent on the settings interface rewrite which is underway).
