### ISSUE TITLE
blocking /clear command on twitch

### ISSUE THREAD

**Issue by FascFlamejante** [night/betterttv#4744]
Whenever I try to do the /clear command in chat on twitch betterttv blocks, how can I solve this problem?

Chat was cleared by a moderator (Prevented by BetterTTV)

![image](https://user-images.githubusercontent.com/88822258/129157314-0f97b83d-ffa9-496c-adac-169b2a296e23.png)

**Comment by lhocke** [comment]
it's built in to bttv and can't be overridden. It desperately needs to be updated to allow chat to be cleared though

**Comment by EmbitiousDev** [comment]
It was put in place to prevent censorship, likely won't be changed.

**Comment by night** [comment]
There was never a setting added for it, but we did intentionally add it to prevent censorship. People tend to forget the early days of Twitch, but mods were (in my opinion) censor-happy back then. We did change the default for showing deleted messages in order to reduce the likelihood of phishing related to spam messages over time, but for mass clearing chat I'm not sure I understand the use case enough for why these messages cannot be individually moderated by bots. Why do we need to censor the legitimate chatters?

**Comment by lhocke** [comment]
because there's a huge problem with people who aren't legitimate chatters bombarding the streams of marginalized creators with messages that are designed to evade bot detection. hate raids have gotten especially bad over the last couple months and being unable to clear chat when its being drowned out by accounts posting threats and slurs is a problem.

**Comment by FascFlamejante** [comment]
exactly and with that I can only clear chat via BTTv and not via twitch chat which is a very big nuisance
