### ISSUE TITLE
switching to dark mode results different panel order

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#478]
Example: http://www.twitch.tv/taniauncensored/
To reproduce, switch to dark mode AND refresh page.
![dark](https://cloud.githubusercontent.com/assets/11561641/8042593/91898afe-0e20-11e5-884a-f156cb5e6c23.png)
![light](https://cloud.githubusercontent.com/assets/11561641/8042596/990046c4-0e20-11e5-8365-b617f89b1750.png)

**Comment by night** [comment]
We don't reorder panels, but Twitch's panel code automatically shifts things based on height and width. Since the style adds borders, it's probable that Twitch is moving a panel to a new line and offsets the position of each subsequent panel. This is not something we can fix, and it's not really a concerning problem (panels are never guaranteed a certain position on the page, only the order from left to right and top to bottom is guaranteed).
