### ISSUE TITLE
[Suggestion] Highlight deleted messages

### ISSUE THREAD

**Issue by VasilePintilie** [night/betterttv#5060]
Hello.

Even though we can choose to see the deleted messages, it would be nice to be able mark / highlight the deleted message.

Right now, even if a message is deleted, it's impossible to know that because it acts like any other message in the chat.

**Comment by Nareese** [comment]
We already do add a class that adds "opacity: 0.5;" to shown deleted messages.  This will cause the deleted message to appear "faded".  Admittedly, this is harder to see in light mode, where the text is slightly grey and the name is a faded color, but in dark mode the grey text instead of white against the dark background shows up pretty clearly.  It's supposed to be unobtrusive, since if you're asking for deleted messages to be shown, you are saying you don't want them treated differently than any other message.  The class we add to the line for the opacity is `.bttv-chat-line-deleted`, so if you're comfortable with user CSS tools like Stylus, you can add whatever CSS attributes you like, such as a different background or text color, to that class.

**Comment by VasilePintilie** [comment]
Thank you.
