### ISSUE TITLE
Would Love To Clear Chat With My Stream Deck Button | BTTV Prevents It

### ISSUE THREAD

**Issue by JoJoStarFire** [night/betterttv#5180]
Each time I try to clear chat with a press of my Stream Deck. BTTV blocks that ability and this is stated "Chat was cleared by a moderator (Prevented by BetterTTV)" I would love that I was given the option to either use BTTV or to have my Stream Deck do it. It's kind of an inconvenience for me, to click on the cog and clear my chat.

**Comment by Nareese** [comment]
BetterTTV blocks the Twitch "Clear Chat" (in red on the menu) command regardless of where you do it from. BetterTTV provides a chat gear menu option for "Clear My Chat" in addition to the default Twitch "Clear Chat" command.  The BetterTTV option clears only your chat, while the Twitch option attempts to clear everyone's chat, which is what BetterTTV (and various other extensions) blocks.  Your Stream Deck probably sends the command "/clear", which is the command line equivalent to the Twitch option.  There is unfortunately no /command for the BetterTTV clear only your chat command, so that's probably not possible with your Stream Deck.
