### ISSUE TITLE
Tab completion doesn't work mid-sentence

### ISSUE THREAD

**Issue by metarmask** [night/BetterTTV#519]
It would be useful if you want to whisper something you've already written.

**Comment by night** [comment]
Cannot reproduce.

**Comment by metarmask** [comment]
What I mean by the title is that if I type "I think he is awesome." and then go back in the sentence and replace "he" with the start of a username and hit tab it doesn't work. Here's a video of what I mean: http://www.youtube.com/watch?v=j4cHJ-R7aEE

**Comment by night** [comment]
Due to how we handle tab completion, fixing this is far too complicated and would require a full rewrite. It's probably not going to happen because of that. You or others are welcome to submit a pull request if you wish, but since the use case is low for this (most people do not go backwards in a sentence to edit it with tab completion) I doubt this will get fixed anytime soon, if ever.

**Comment by metarmask** [comment]
Ok, I understand.
