### ISSUE TITLE
Disable the /clear preventer or as option

### ISSUE THREAD

**Issue by GeneralUltra758** [night/BetterTTV#524]
i see a BIG PRIVACY ISHUE in that feature!!!

what if the broadcaster or someone accidently poste valiable private information??!! /clear wont help Thanks to betterTTV!

i suggest a option in betterTTV for the broadcaster to disable that feature in his channel!

**Comment by vendethiel** [comment]
No

**Comment by GeneralUltra758** [comment]
why no?!

**Comment by cletusc** [comment]
If someone posts private information, it is now public information and should be treated as such. Just because it gets cleared doesn't mean someone didn't already grab it. If it was a password for example, you should change the password--assume it's already been taken.

Twitch messages also go into IRC and chat clears don't affect IRC so disabling this wouldn't help security at all.
