### ISSUE TITLE
Emote Autofill Bug Disables chatting function

### ISSUE THREAD

**Issue by Vafarien** [night/betterttv#5260]
Browser: Chrome (Version 99.0.4844.51 Official Build 64-bit) (Windows)
BTTV: Version 7.4.22

steps to reproduce:
1. typing colon, then emote, then clicking to mouse over to select emote from selection
2. hovering and clicking the emote from the list selection
3. repeating emote selection, infrequently  at random fast pace
4. sending emote by autofill and pressing enter
5. chat sending function gets blocked by some strange ghost thing, that i usually see when twitch fails to load an emote?
6. chatting function only returns on refreshing entire page, waiting doesn't work.

Attached image of what the blocked chat looks like:
![image](https://user-images.githubusercontent.com/2349950/158017557-0723ddc6-2c8b-4a3a-87e0-ffd16c21df9b.png)
Inspect element reveals some sort of 'container' error?:
![image](https://user-images.githubusercontent.com/2349950/158017622-df027d8e-b99e-4a45-aead-9179d5b9a6ab.png)
![image](https://user-images.githubusercontent.com/2349950/158017686-00b8cc4f-83b3-46f8-bfa3-da84582cc44f.png)
![image](https://user-images.githubusercontent.com/2349950/158017697-79e4e0b7-6b8d-4ff3-ade3-f6516522d035.png)
After refreshing the page and console, errors from BTTV.js no long appear, but still happen randomly sometimes i dont know how its so random how one time i try using an emote it breaks my chatting function somehow?
bttv.js screenshot after refreshing to fix the chatting function:
![image](https://user-images.githubusercontent.com/2349950/158017937-60063324-149e-45ec-a768-8b5c5ac3cd68.png)

**Comment by Vafarien** [comment]
it happened to me again.
i sent a @ in chat to a user tagging them and replying with an emote.
then while having another users profile card open, a tag at me notified me in red at the top that they tagged me in chat, while i was looking at another users namecard profile thingy.
then my chatting reply area box turned into the ghost thingy, while the namecard thingy was up, all at the same time

at the time of error:
bundle.js is at over 500+errors
and bttv.js is at 14 new errors
something something about 'missing field: display name & id' 'error cannot find descendant path' 

pretty much the same errors as in my screenshots posted above.

**Comment by Nareese** [comment]
"Emote autofill" is not a BetterTTV function.  This is new functionality that Twitch themselves have recently added.  If it's broken, that's on Twitch, in spite of what filenames you might see in the console log.  Console logs are notorious for mis-identifying the file that is actually throwing the errors.

Bundle.js is not a BetterTTV file.  I don't know if it is a Twitch file or some other extension, but it isn't BetterTTV.

Looking at the stack backtraces on the errors, none of the functions and almost none of the filenames shown are BetterTTV files or functions (core-*, features.chat*, and vendor-* are all Twitch files, and account for 99.9% of the functions shown in the backtraces in your images).

BetterTTV has no ability to "disable the chat box with a ghost image".  Only Twitch can do that. 

You can probably verify this by either disabling or uninstalling BetterTTV, and trying to reproduce these issues.  I expect you will continue to have them, and you will see all the same errors, but with a different filename instead of betterttv.js.  

Regardless, this isn't our breakage, and there is nothing we can do to fix it.
