### ISSUE TITLE
Auto Hide Chat feature

### ISSUE THREAD

**Issue by IBIubbleTea** [night/BetterTTV#553]
Hey,  I was just wondering if you guys could add a setting where I could hide the chat automatically without having to do it manually when watching streams, I find it quite distracting sometimes and annoying with the spam.

I'm not quite sure how the hide feature works but I was wondering if it would use less bandwidth when it is on hide.

Thanks!

**Comment by night** [comment]
To hide chat, click this button near the top left of chat:

![hide chat button](https://nightdev.com/i/ss-05BdJlB75RrWgz55aUxxcF65o.png)

**Comment by IBIubbleTea** [comment]
I'm aware but then I would get the black bars which I dislike and is also unpleasant to have. I'm just asking for an auto hide feature in the menu. 

I like the concept of hide button in the gear icon but I have to do it manually each time.
http://i.imgur.com/OtjWjuG.jpg

**Comment by night** [comment]
I would think it's more distracting to have an empty 320px column down the side of the page rather than having black bars along the sides of a video player.

Unfortunately there's nothing we are willing to do in the instance. There's already numerous ways to hide the chat, so making another separate option that does the same thing doesn't make much sense at all.

You can either choose to close the right sidebar, disable chat how you have been doing, or popout the video player.

**Comment by IBIubbleTea** [comment]
Well whatever then. Thanks for your help and support for this program
