### ISSUE TITLE
BetterTTV Browser Extension Needs To Save Settings Between Browser Sessions

### ISSUE THREAD

**Issue by xryanx555** [night/betterttv#5707]
The BetterTTV Browser extension is not currently saving settings between browser sessions for browsers that are set to clear the cache between sessions, even if betterttv.com is set as an exception. Other browser extensions work fine and keep their settings even with this security precaution in place, and it is a very common security selection.

**Comment by purrincessMirri** [comment]
Seconding this, i have both betterttv.com and twitch.com set as exceptions and all settings revert to default every time i start a new session. Its driving me crazy

**Comment by night** [comment]
you may need to add `www.twitch.tv` or `twitch.tv` as an exception, since those are twitch's domains.

**Comment by xryanx555** [comment]
They are already added so that it keeps my Twitch logged in.

**Comment by purrincessMirri** [comment]
@night whoops, i mistyped. I did mean .tv, that's the one i have listed as an exception

**Comment by night** [comment]
Unfortunately because BetterTTV stores settings in browser local storage we are not able to fix the underlying browser issue. If your browser is not respecting your configuration not to clear the cookies/storage, you may need to reach out to the browser's support team to find out why. You might also try a different browser or turning off the setting which is deleting the data. We may add support for setting sync via #766 in the future, which could maybe assist you with the loss of your settings.

**Comment by xryanx555** [comment]
These settings need to be stored somewhere that does not get cleared out. Like I say, my other browser extensions keep their settings just fine. It's a coding issue with the app. Just fix it instead of making excuses.

**Comment by dclstn** [comment]
Wanted to share here, we've added a new feature "Cloud Backups" which will sync setting state between sessions that have it enabled. You can find the setting in the BetterTTV Settings Menu -> User Settings -> Enable Cloud Backups.

Though this feature is only available to users subscribed to BetterTTV Pro.
