### ISSUE TITLE
Suggestion: Clickable scroll wheel for viewer list

### ISSUE THREAD

**Issue by MattUnderscore** [night/BetterTTV#602]
In channels with large amount of viewers, it can be tedious to scroll near the bottom to find a name. A clickable scroll bar would resolve this.

**Comment by night** [comment]
Because user lists can be extremely long, Twitch does not parse the entire list and print it. Instead, they partially render the list and fake the scrollbar/scrollwheel actions. Because it's not a legitimate scrollable entity, it cannot be scrolled as you normally would be able to. There's nothing we can do about it, unfortunately.
