### ISSUE TITLE
Possible memory leak BTTV

### ISSUE THREAD

**Issue by OJoo0oohn** [night/betterttv#6424]
### Describe the bug

If i have BTTV extension in my browser, twitch chat uses over 1.5GB of RAM, increases a lot when I'm watching the stream.

### Steps to reproduce

Download the BTTV extension and watch some big streamer

### Expected behavior

Watch a stream withou crashing my browser, because I only have 8GB RAM

### Screenshots

![image](https://github.com/night/betterttv/assets/141842194/c1a9a9c5-c218-4650-9897-53c085bfaf6b)

### Device information

Windows 10
A520M-H
GTX 1050 Ti
Ryzen 5 3600
DDRY 8GB RAM 3200MHz

**Comment by night** [comment]
Chrome and other Chromium based applications cache page resources in memory for performance. Chrome will garbage collect these items in memory as-needed by your operating system, but since you have 25% memory available it does not. You may see slightly higher usage over time with BetterTTV running because it loads many types of GIF emotes, which tend to use more resources. If you'd like to see less memory usage with BetterTTV, you could disable BetterTTV emotes in the BetterTTV settings.
