### ISSUE TITLE
Follower Distinguishment (Highlighting, Marking, etc) in Twitch Chat :)

### ISSUE THREAD

**Issue by angrygamebros** [night/BetterTTV#646]
It'd be wonderful if there was an option in BetterTTV that highlighted/marked/etc any chatters that are also Following the channel. It'd help the streamer to memorize names, and it'd be incredibly useful  when holding events, such as giveaways that apply to followers.

**Comment by night** [comment]
We have no means to know who is following in real time, and we are not going to massively poll the Twitch API for this data.

**Comment by angrygamebros** [comment]
Well, with a response like that to a seemingly-simplistic request, I'm definitely getting rid of BetterTTV, and absolutely not suggesting it to anyone else. I'd thank you for your time, but I took none.

Date: Thu, 13 Aug 2015 09:49:11 -0700

**Comment by night** [comment]
I'm not sure how you'd like me to respond to a request that is simply not possible and most likely never will be. There's nothing we can do to make this possible, since it all depends on the APIs Twitch provides. If Twitch doesn't emit this data to chat, then we can't provide it without polling their API. We were already pestered for the amount of requests we used to use for display name lookups (so much so that Twitch implemented it in chat), and since BetterTTV has grown to about 1 million users, that's double the amount of requests we were using prior. This is not even mentioning that Twitch has increased the caching on its following endpoints because of the amount of requests people already throw at it for follower alerts. They even limited the follower list to the first and last 1600 because they can't handle the abuse.

**Comment by angrygamebros** [comment]
My apologies. I guess I just misinterpreted the reply. I tend to do that, (conveying tone through text is impossible, and I assume the worst. Lol). I understand what you mean. It's kind of a shame, but what can you do, I guess. I just figured there'd be a way to refer to the channel's follower list in order to mark an active chat user. Now I know, thanks!

Date: Fri, 14 Aug 2015 13:29:23 -0700
