### ISSUE TITLE
Reverse Chat Direction is unusable

### ISSUE THREAD

**Issue by AriiaLux** [night/betterttv#6511]
### Describe the bug

When Reverse Chat direction is enabled and a chat notification is up on the screen, i.e. a outgoing raid, pinned message, hype train etc, it appears on top of new messages.

### Steps to reproduce

1. Enable Reverse Chat Direction
2. Pin a message to chat
3. Enter new messages in chat, you will see that they are blocked by the chat notification.

### Expected behavior

The chat notification box should be moved down to the bottom of chat, and then it ideally needs to collapse in reverse too.  Also would make more sense for the chat input box to be at the top but then channel point redeems menu and the emote picker also need to be reversed accordingly.  The chat paused due to scroll notification should be moved to the top of chat too.

### Screenshots

![image](https://github.com/night/betterttv/assets/153413544/68724da4-bfa7-454c-b5c0-ec9c3fe5686c)
![image](https://github.com/night/betterttv/assets/153413544/03c0a3ff-dbf2-4c61-8d54-4a5e32bb29d7)

### Device information

Doesn't appear to be device or browser specific but here are the main
- Device: Mac Mini M1
- OS: MacOS Sonoma 14.1.2
- Browser: Opera GX 105.0.4970.37

**Comment by night** [comment]
Thanks for the report. Any sort of community highlights that pop up currently go above the chat. Due to the positioning of the element it's actually non-trivial to reposition it (Twitch uses absolute positioning and lets it layer on top of the chat with unbounded vertical dimensions). The good news is you can hide these by toggling off "Community Highlights" in the Chat settings section of the BetterTTV settings.
