### ISSUE TITLE
bttv blacklist

### ISSUE THREAD

**Issue by Jon77u** [night/betterttv#6522]
### Describe the bug

Term blacklist feature is dysfunctional, doesn't remove any of the terms added from the chat, has been this way for me for about over a year now. Also the BTTV settings menu is heeellla laggy, takes like 30sec to get the menu opened.

### Steps to reproduce

literally normally opening the settings from the cog icon below the chat box 

### Expected behavior

for the blacklisted terms to not show up ':D

### Screenshots

![bttv blacklist not working](https://github.com/night/betterttv/assets/153653798/c3c3eb54-ad54-42f8-a193-31921729d405)

### Device information

- Device: PC
- OS: Windows 10 Pro
- Version: 22H2 
- Browser: Google Chrome
- Version: 120.0.6099.71

**Comment by night** [comment]
I just tested the blacklist locally and was not able to reproduce any issues. If items are not being removed, you may have another extension installed that conflicts with BetterTTV. Try disabling other browser extensions that affect Twitch and see if that helps.

As for the setting menu "lagging," it seems to be loading quick on my end. That could be due to the number of blacklist or highlight terms stored. Can you share more information about what you have on your lists?

**Comment by Jon77u** [comment]
I had just those 3 to test it. Though it seems that disabling ffz & 7tv fixed both of the issues :D thanks!
