### ISSUE TITLE
Chat input randomly changes cursor to the left while typing

### ISSUE THREAD

**Issue by makedir** [night/betterttv#6687]
### Describe the bug

There is an issue since some time while using betterttv Chrome addon, that when you type in the chat input box on twitch, the cursor switches to the left side resulting in something like this:

instead if typing "this is a test"

the cursor randomly flips to the left while typing and you get something like this

"s is a testthi

### Steps to reproduce

start typing in chat box on twitch channel

### Expected behavior

normal input

### Screenshots

-

### Device information

-

**Comment by night** [comment]
I'm not able to reproduce this issue. Are you sure this is caused by BetterTTV? We don't change your input selection unless you perform an input related to BetterTTV's features. This would be if you use tab completion, up arrow, or down arrow in chat. Inserting an emote from our emote picker, interacting with moderator cards, or double clicking on user names in chat can also trigger input changes.

**Comment by night** [comment]
I would recommend disabling browser extensions one by one to see which, if any, affect Twitch. If all else fails, you may need to file a bug report to Twitch as it could be a platform bug they need to address.

**Comment by makedir** [comment]
I am really annoyed right now, I tried to record the issue live with OBS for you, but I could not reproduce it. I typed for 10 minutes, didnt happen, then I stopped OBS, went afk for 5 minutes, came back, typed in the chat and issue was there again. Now I cant reproduce again recording it trying to get it on video.
