### ISSUE TITLE
Exact Match Keywords

### ISSUE THREAD

**Issue by night** [night/BetterTTV#67]
Basically a reversed wildcard. A simple example follows. The example uses a blacklist word of 'a', what I suggest is it to only block lines that only contain the letter 'a'

**Blacklisting 'a'**
- Chat_Guy1: Hi there!
- Chat_Guy2: a
- Chat_Guy2: a
- Chat_Guy2: a
- Chat_Guy1: What's up
- Chat_Guy3: Nothing...

What happens is that the outcome is that lines _2_,_3_,_4_ and _5_ is blocked with the filter, this is why exact match is required. The only thing I want blocked in this case are lines _2_,_3_ and _4_ that contains only the letter "a". Line _5_ was a legit line that I want displayed. 

Why can't [a] or similar block specifically only lines with just 'a'

**Comment by Codonbyte** [comment]
This would be great for channels that use those stupid chat-game bots (I think it's called DeepBot?) that encourage viewers to spam !guncheck, !bankheist, !points, !partoufs, !cheese !guncheck etc. all the time. I of course already block these bots, since they typically run on accounts that are tied to the channel they're in, but being able to block lines that only contain !guncheck or !bankheist would be awesome. 

Honestly, I **hate** those chat-game bots, more than Nightbot even.

**Comment by voloshink** [comment]
and why can't your issue be solved with the blacklist function?

**Comment by Codonbyte** [comment]
Wait, I didn't mean to unassign anybody! How did that happen? I just meant to post a comment agreeing that this would be really useful for spammy chat-game bots (!bankheist). How do I reassign him?
