### ISSUE TITLE
In Regards to Emote Rejection

### ISSUE THREAD

**Issue by oOYourdadOo** [night/BetterTTV#671]
Hi. I uploaded an emote last night that was rejected pretty quickly, with a rejection message that stated "Emotes must have a transparent background." Now it's a clear and understandable reason, but my issue with that is I've seen several emotes get approved that did not have a transparent background. Please, I was hoping to get a bit more clarification on this 'transparent background' issue if you don't mind. I would like to know: For emotes that have a background, what's an acceptable non-transparent background, for BetterTTV, or what classified as a transparent/non-transparent background when creating an emote?

I would have to do more research and search through many pages to see all of the emotes uploaded in the past, but I definitely know of at least one emote for sure that has a rainbow background, but was approved and allowed to be uploaded/shared through BetterTTV. If I'm a lot to post links, I'd like to link my emote, and the other emote that I have in mind, and another emotes that have what appears to be non-transparent backgrounds to compare to. 

Thanks for taking the time to read all of this, and sorry for the trouble. :(

**Comment by night** [comment]
From our rules:

> All submissions must not have a background (unless it proves necessary) and must be in PNG or GIF format. Emotes uploaded must also be visible on both the light and dark BetterTTV themes. Emotes must be properly trimmed (no jagged edges).

If your emote's background is not necessary and is the result of laziness, we will not approve your emote. We enforce restrictions to enforce a standard quality that all emotes must live up to, thus improving user experience.

Unfortunately since I do not approve emotes and we have a team that approves emotes, I have no way of knowing what emote you uploaded nor why it was rejected. You can always reupload and place comments in the "justification" field, and the approver can refer to them.
