### ISSUE TITLE
Long Turbo Badge

### ISSUE THREAD

**Issue by Jessica-0** [night/BetterTTV#679]
A long turbo badge, similar to the Justin TV mod badge that just says 'Turbo'. 

Little thing that I'd like :)

**Comment by voloshink** [comment]
This would make mod turbo and broadcaster turbo combos take up a lot of extra space.

**Comment by Jessica-0** [comment]
As I'm aware. It would be purely aesthetic. It was just a thought.

**Comment by night** [comment]
Since turbo was never a JTV product, we do not have a tag for it. JTV chat tags only replace badges that existed during JTV's operation. I have no intention to extend the support to badges post-JTV, unfortunately. Concurring with what @voloshink said, the width of extra badges is a large issue and is why things like grandfathered custom chat tags are inevitably being removed.
