### ISSUE TITLE
Gif Emotes issue

### ISSUE THREAD

**Issue by ArchangelTS** [night/BetterTTV#682]
My Gif emotes like RareParrot and (ditto) only seem to work in a few streams like RareParrot works in SodaPoppins stream but doesn't seem to work in any other stream.Other than that BetterTTV seems to be working fine and i eally like its addons.

**Comment by conceptionals** [comment]
This is because both RareParrot and (ditto) are not global BetterTTV emotes, therefore the channel owner must manually [add them to their channel](https://manage.betterttv.net/emotes) as Shared Emotes before the emote can be used in their channel. For example, if they wanted to add (ditto) to their channel they would simply have to go [here](https://manage.betterttv.net/emotes/554da1a289d53f2d12781907) and click the green "Use in my Channel" button. Side note, here is a list of all the global BetterTTV emotes: https://nightdev.com/betterttv/faces.php
