### ISSUE TITLE
Change Twitch Sword Color

### ISSUE THREAD

**Issue by TecMyIT** [night/BetterTTV#695]
It Would be awesome if you can guys can implement that we can change the sword colors to what ever color we want :D of course its the mod sword it would be amazing to have that feature :D

**Comment by DTittel** [comment]
Locally or for everyone who has BTTV installed?

**Comment by TecMyIT** [comment]
to everyone that has BTTV installed

**Comment by DTittel** [comment]
That kind of kills the intention of having colored badges. 

This would mean admins, and staff messages may get missed because people can't tell anymore.

**Comment by TecMyIT** [comment]
how about locally?

**Comment by DTittel** [comment]
I'll leave the request open if someone wants to fill this as a local feature, not sure why you'd want this personally.

**Comment by night** [comment]
I think the colors need to remain standardized to not confuse users what permissions a person actually holds. Since you've been the only one to ever request this feature, you may consider setting custom CSS using Stylish to recolor the badges: https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en

We may revisit this in the future if it becomes something a majority wants, but for now I do not think we will consider this as a feature.
