### ISSUE TITLE
Can no longer see deleted messages from the moderator

### ISSUE THREAD

**Issue by hajo808** [night/betterttv#7069]
### Describe the bug

Highlight deleted messages : Changes “Message deleted by moderator” back to the user's original message and highlights it. 

This is switched on. But you can only see, message deleted. Without content.

### Steps to reproduce

-

### Expected behavior

-

### Screenshots

-

### Device information

Firefox 131, Win10

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by imheinrichlunge** [comment]
Same behavior here, I tried reinstalling the add-on (in Firefox), double checked that the `Highlight Deleted Messages` option was checked, it was, but it doesn't work either.

**Comment by Thomas-R-dev** [comment]
> Same behavior here, I tried reinstalling the add-on (in Firefox), double checked that the `Highlight Deleted Messages` option was checked, it was, but it doesn't work either.

same issue and emotes tab not works

**Comment by Beerman-pixel** [comment]
Same issue here

**Comment by Seb-Solon** [comment]
It's fixed already since a couple of day the issue is that the version on https://addons.mozilla.org/en-CA/firefox/addon/betterttv/ is not up to date. I should be `7.6.7`. It usually takes a couple days, but this time it looks like it is taking longer.

Maybe @night could elaborate on the process on having the extension uploaded :+1:

**Comment by Seb-Solon** [comment]
Looks like the addons just got updated !
