### ISSUE TITLE
Please, urgently add a "Flash Video Player"

### ISSUE THREAD

**Issue by justarandomuser1** [night/BetterTTV#733]
Lost over 50% of the FPS, delay increased by 20% and RAM abuse went up by 200% ever since Twitch forced us to use HTML5 player. Could you please add a choice to return us to the glorious Flash player?

**Comment by Fugiman** [comment]
:-1:

**Comment by justarandomuser1** [comment]
So you'd rather force everyone to experience the same hell simply because you are against Flash? Google drone detected!

**Comment by night** [comment]
The resource usage should be about the same or next to nothing, since it at most uses the same old flash player with HTML5 player controls. If you're using Microsoft Edge or Safari, you're using native HLS.

**Comment by justarandomuser1** [comment]
Trust me, night, it is not the same and it is making a huge difference. And this is no Firefox, without browser Hardware Acceleration on. Besides there's this issue that you can't break out of buffer by pause-play sometimes (something we could do in Flash just fine.

**Comment by night** [comment]
It's unfortunate that you are not enjoying the change, as I would imagine most welcome the change. Rather than rejecting the reality that is the new player's permanence, perhaps you can work with Twitch to debug issues you are having. You can reach out to their support at http://help.twitch.tv 

Worse performance would be quite abnormal, since Twitch has been experimenting with the new player on-site for a while with ~20% of its users enrolled in the new player (and even some who wanted us to force enable it for them in BetterTTV). Nobody on our team has had subpar performance from the new player.

> Google drone detected!

It's funny you should mention this, since Apple led the revolution by killing flash on iOS years ago: https://en.wikipedia.org/wiki/Apple_and_Adobe_Flash_controversy

Flash's death is imminent, since it is inefficient and power hungry. HTML5 is more native to browsers and takes better advantage of hardware for decoding video. While Twitch still uses flash for its HTML5 player, they are working to making it completely HTML5 by Q2 next year.

**Comment by justarandomuser1** [comment]
I have no choice, really! Flash's ineffeciency and power hunger, I believe, is a myth. If it were so it would have died before Java, it wouldn't even have dedicated sites (Kongregate, Newgrounds, Armor Games). Security issues are patched as they are found, but everything has secutiry issues, even PNG, JPEG, GIF. And the only two browsers I know of are either poorly optimized for HTML5 (FireFox, embedded vines and twitter videos won't play) or resource hogs (Chrome does this to RAM), and those are top two.

**Comment by night** [comment]
> Flash's ineffeciency and power hunger, I believe, is a myth.

This is just incorrect. This is actually the reason why Chrome ended up manufacturing its own plugin API called Pepper: https://en.wikipedia.org/wiki/Google_Native_Client#Pepper

Java and Flash are one in the 

Sincle Mozilla has not adopted this API, it is probably just another reason performance is worse in Firefox.

I just tested myself, and I get 25-30 fps on Firefox in both the old and new players from Twitch. On the same players in Chrome, I get the full 60fps of the content I was playing. If you want a better browsing experience with flash player, I highly suggest swapping to Chrome. If you choose not to swap, you will probably not see improvements in performance until the full HTML5 switch next year. There's nothing we or Twitch can really do to improve flash performance on Firefox, and since both the old and new players are flash there's little, if anything, to gain by offering an option to use the old player.

You can also try Microsoft Edge, which has native HLS support (meaning no flash needed at all), but since it does not support browser extensions yet you'd have to manually load BetterTTV until they do: https://community.nightdev.com/t/how-to-manually-load-bttv-on-microsoft-edge-browser/4695

> If Flash ever dies, the greatest crash of the internet will happen. Sites like Kongregate, Armor Games, Newgrounds, Deviant Art, Internet Wayback Archive and many, MANY others will have to discard ALL Flash content. In the case of the three first, they will be left with nothing but Unity, Java and HTML5 games, most of which are Cookie Clicker , Flappy Bird or 2048 clones!

It will be dead in the sense that it is not going to be used prevalently, just like Unity and Java are used almost nowhere these days. Flash, Unity, and Java are one in the same: third party plugins, whereas HTML5 is implemented in the browser.

**Comment by justarandomuser1** [comment]
Remember, not everyone can afford superb computers, some can't even afford a 5 years old one. Try using any HTML5 Player with 3+3ghz CPU, 3Gb Ram and a Geforce Series 9.

There's this other computer here, even worse than this one, that uses Chrome... And is crap. No, seriously, freezes a lot, its Ad Blocker is crap and can do nothing to stop ads and slows the computer to a crawl.

My situation is so bad that I can't even upgrade to Windows 7. I'm stuck with XP because of hardware.

**Comment by cletusc** [comment]
Just my own opinion here and not representative of BTTV's staff in any way (I'm not staff) nor intended to be run in any way: if you are still using XP, due to hardware reasons, you may have bigger problems than Flash/HTML5 (security vulnerabilities mainly). If your hardware is so bad that you can't upgrade Windows itself, Flash or HTML5 will run like crap regardless. Software can only squeeze so much out of bad hardware. Poop is still poop no matter which polish you use to make it look pretty.

My vote: :-1: Allow Twitch to improve HTML5 rather than clinging to Flash for dear life. AFAIK, at this time, the video still runs through Flash. It's only the interface that's HTML5.

**Comment by EhsanKia** [comment]
At the end of the day, you'd be delaying the problem by a few months. Want it or not, the transition to HTML5 is happening, and the Flash player will be deprecated and keep falling behind. You'll have to move over soon, so you may as well figure it out now and try to pin point the actual bug causing poor performance rather than trying to avoid it by sticking with old technology.
