### ISSUE TITLE
Safari AirPlay

### ISSUE THREAD

**Issue by Wataaah** [night/betterttv#741]
Hi, I saw you added the Chromecast option in the latest realease of BTTV, so I wondererd if you could do the same with Safari and Airplay. The latest version of safari (OS X El Captain) includes native AirPlay support for Youtube, so I guess it's possible to include this on twitch? 
Thanks

**Comment by night** [comment]
Chromecast is built into Twitch's player, not added by us. If you are referring to the legacy TwitchCast feature in BetterTTV, we will be phasing it out of BetterTTV soon (but it can still be accessed via our site). 

As for Safari AirPlay support, it appears this may be possible at first glance with Twitch's new player since Twitch supports native HLS support in Safari. The only problem is Twitch's player only uses native HLS if flash is not installed, and given that so many people use flash and there's no way to force HLS otherwise, we do not really have a way to implement this currently. I'll leave this open in case anything changes, but for now it's not exactly practical to integrate.

**Comment by dominiklohmann** [comment]
Temporary workaround: In Safari, right-click the video player and select "Open Video in New Window". This will open the video using Safaris native HLS video player, which has an option for Airplay.

**Comment by Wataaah** [comment]
I'm looking for that "Open Video in New Window" option for like 10 minutes, but there is no such thing when I right click the Video.

![par dofaut 2015-10-30 a 17 44 16](https://cloud.githubusercontent.com/assets/14958126/10851904/fe9eda12-7f2d-11e5-9ee1-398e4e83fca3.png)

It's in french but there is not the option. I tried popping out the video in the player option, which opens it in  another player, but I still can't Airplay it. If you managed to do so, can you tell me how you did it? I'm using Safari 9.0.1 on OSX 10.11.1 El Captain.

**Comment by dominiklohmann** [comment]
![Screenshot](http://d.pr/r9Y4+.png)

Works for me, same Safari, same OS. Don't know why it's not there for you.

**Comment by Wataaah** [comment]
It seems we haven't the same player. I don't know why, thanks though. I since managed to watch Twitch on the Apple TV with the highest resolution with Plex Connect.

**Comment by night** [comment]
As of 2022 Twitch no longer appears to be using native HLS playback in Safari. Because of this, implementing AirPlay support is not likely possible.
