### ISSUE TITLE
Feature Request For the 'Following Sidebar'

### ISSUE THREAD

**Issue by dhuyd** [night/BetterTTV#758]
For those that the user has 'followed' that are 'Currently Live' have the option to list how long they've currently been live for. For those that are 'Currently Offline' list how long it's been since they were last live.

Hope the staff at BetterTTV sees this! :D
Keep up the awesome work!!

**Comment by night** [comment]
It's not possible to list the time a stream has been offline because that data is not available. Additionally, adding stream uptime adds unneeded clutter to the right sidebar. How long a stream has been live shouldn't be a factor for watching it, and the only use case for knowing how long a stream has been live is making highlights.
