### ISSUE TITLE
Login issues and dark css

### ISSUE THREAD

**Issue by vasive** [night/BetterTTV#759]
Login css seems to be broken with dark css

http://i.imgur.com/3VETt0V.png

I'm not sure if it's causing new issues logging in to twitch, but I keep getting 
"We're sorry, we encountered an error logging you in (error code: mismatched_nonce_salt_pair)."

**Comment by night** [comment]
Thanks for the bug report. This is caused by Twitch's login popup now being an iframe. We're still evaluating how to handle this use-case, since we do not want to theme the entire login page.

The error you're getting should only happen when you've opened a newer Twitch window and try to login with an older one. If this is not the case, I suggest reaching out to Twitch support: http://help.twitch.tv
