### ISSUE TITLE
Better Moderation Options

### ISSUE THREAD

**Issue by GeneralTango** [night/BetterTTV#760]
Is it possible to add some simple options for twitch chat moderators and broadcasters like:
"OFF/Purge/Timeout/Ban Links/blacklisted words or sentences"
This could be a seperate option window with a bunch of options just for mods and admins.

ALso underneath this main option could be the options to differentiate between subscribers and non subribers posting links, as some channels only let subs post links in chat but dont have it in their dashboard settings.
Then have it so repeat offenders get higher penalties which you can select in maybe 5 stages so have 5 empty boxes next to the timeout option to put the timeout times into them so the 1st timeout might only be a 5 second one whereas the 3rd would be a permanent ban or whatever.

Its just something I think could be really useful when you are trying to moderate large numbers of people and not having to worry about timing out a link and repeating "please dont post links unless subscribed" or whatever every 5 seconds.
Thank you

**Comment by night** [comment]
Thanks for your feedback.

I'm not sure if you thought through your idea in entirety, since it seems like you're wanting us to replicate the use-case of channel moderator bots. Bots already have filters for links and blacklisted items (as well as other useful filters), and also usually tell the user what they did wrong with preconfigured messages. If the channel you're moderating does not yet have a bot, check out Nightbot, Moobot, and/or Xanbot (sometimes multiple bots can be helpful for larger channels).

As for allowing moderators using BetterTTV more versatility over timeouts (purges and other lengths of timeouts), we already enable you to select any amount of time individually per user with a timeout slider. You can right-click on a user's name in chat to open the timeout slider (you can also change this to a shift+click in the BetterTTV settings).

Cheers
