### ISSUE TITLE
Global Ban Protection

### ISSUE THREAD

**Issue by bufutda** [night/betterttv#761]
A feature where BTTV doesn't let you send a chat message if that message would breach Twitch's rate limit and give you a global ban. This would be toggle-able, and off by default.

**Comment by th0mk** [comment]
I'm not a 100% sure, but i think mods can spam up to 60 messages in 30 secs before getting globally banned. Might be an idea to change it for mods of a channel.

**Comment by LeotomasMC** [comment]
This would possibly be hard to do, because BTTV has no way of knowing close you are to the limit, as far as I know, its easy to manage this when working with chat bots, because you usually only have one instance of a chat bot running, and the chat bot can keep track itself. However, BTTV just changes the Twitch website on a local level, so if you send messages on 2 clients (eg. 1 channel on your computer with BTTV, and one on a phone), if you send enough messages, on the non-BTTV client, the client with BTTV will be unable to know that you've sent too many. Either way, if your encountering this on one client, your probably spamming, or at least doing something very wrong. The client on twitch also has a built in thing so you dont send messages too fast, but that might be on the API's end as well (you can see this if you copy something on your clipboard, then send a messages, then immediately paste your clipboard contents, then press enter)

**Comment by night** [comment]
While this may have been useful in the past, Twitch's chat prevents you from sending too quickly these days. This avoids the possibility of receiving a chat ban.
