### ISSUE TITLE
Deleted Link setting being ignored.

### ISSUE THREAD

**Issue by AlmightyZing** [night/BetterTTV#797]
Hello,

I want to re-open the following bug that was closed: https://community.nightdev.com/t/bug-native-twitch-delete-links-in-chat-is-ignored/3462/3

Essentially we have the option selected in vanilla Twitch to automatically delete links posted in chat by non-moderators. Better Twitch TV shows anyone who has it installed those links anyway and as a streamer we have no control over who installs BTT.

In the thread I have linked above, you have basically said to get a bot to handle this. We do run NightBot, but we don't want to be forced to time anyone out who posts links.

My request can be handled in 2 different ways.

If you are adamant that BTT will never delete links, please add an option within Nightbot to delete links without timeouts.

If not, please modify whichever part of this add-on is over-ruling the native Twitch setting.

The "I fail to see how this is insecure" comment was a little ridiculous in my opinion. I read this as "I fail to see how overriding Twitch channel settings could be insecure". Lately our channel has been victims to a bunch of spam bots coming and posting links. Links that I can almost guarantee are malicious. If any of our viewers have this plugin installed and click on that link before our moderators have a chance to ban the user it poses a major security risk to them. Please see this from a cyber security perspective and recognize this 'feature' as the risk that it is and make adjustments accordingly.

Thank you.

**Comment by night** [comment]
The reason you'd want a bot to timeout links is because it gives users the option to request access from moderators to post and share a link. With Twitch's deleted links option, it's not possible to grant someone permission to post a link at all. Additionally, bots allow you to define whitelisted links, so you could let your viewers link things like twitter, imgur, oddshot, and youtube links if desired. The added benefits of a bot far outweighs Twitch's link protection.

Additionally, BetterTTV already filters bad links from spam bots automatically, but you can't see them being filtered as a mod (because of complaints by mods seeing "<spam deleted>"). We do this to protect users against harmful links containing viruses regardless of the channel settings.

**Comment by AlmightyZing** [comment]
Can you elaborate or provide documentation on how BetterTTV determines what links are spam? Does it use blacklists of known spam links, or does it run the site through a detection program in real-time? I work in the computer security field, so this is extremely important to me.

I would also like to note that we have turned on Nightbot's link timeout feature, but non-mod users running BetterTTV are still able to see the links. What is the point of having Nightbot hide the link if everyone running your other add-on can see it anyway? The link appears crossed out and is not click-able, but they are still able to copy and paste the link if they wanted to. Is there a setting that fixes this conflict?

**Comment by night** [comment]
> Can you elaborate or provide documentation on how BetterTTV determines what links are spam? Does it use blacklists of known spam links, or does it run the site through a detection program in real-time? I work in the computer security field, so this is extremely important to me.

We monitor Twitch channels for cross-channel spam using an algorithm. Apart from that it's not public knowledge since spam bot authors might read these posts. You can see an example of spam caught via our undocumented API: https://api.betterttv.net/2/spammers The algorithm we use is constantly being modified to fight changes from spammers.

> I would also like to note that we have turned on Nightbot's link timeout feature, but non-mod users running BetterTTV are still able to see the links. What is the point of having Nightbot hide the link if everyone running your other add-on can see it anyway? The link appears crossed out and is not click-able, but they are still able to copy and paste the link if they wanted to. Is there a setting that fixes this conflict?

BetterTTV defaults to not showing deleted messages. It is the user's choice whether or not they want to see deleted messages, not ours. As a safe guard, we do de-link on timeout. I grew up with IRC communities, and BetterTTV is how I envision improving the onsite chat to be more like a standard IRC client (this includes the inability for a server to remove messages, preventing censoring). While we have safe guards in place, what people do with the tools we provide is not our concern. You can't always protect people from themselves, and we're not going to completely "baby" our users.

**Comment by AlmightyZing** [comment]
"Remove Deleted Messages" and "Show Deleted Messages are both defaulted to "Off". I have not changed any settings since I installed the add-on.

**Comment by night** [comment]
Then I'm not sure what point you're getting at. Deleted messages are removed by default. Any timeouts Nightbot issues result in a "&lt;message deleted>" replacement: https://github.com/night/BetterTTV/blob/master/src/chat/handlers.js#L190

**Comment by AlmightyZing** [comment]
http://imgur.com/a/hyyP3

There are some screenshots. Nightbot catches the links, marks them as <message deleted>, but the viewers are able to click on <message deleted> and see the link, which is 100% click-able. I had my non-mod account and one other user account try to post links just to make sure I wasn't just able to see my own links. No settings have been changed on BetterTTV.

Let me know if you still don't understand my concern.

**Comment by night** [comment]
If you check default Twitch, we mimic their functionality.

**Comment by AlmightyZing** [comment]
I am well aware of Twitch's default functionality. Their link protection deletes links and you are NOT able to click on the "deleted link" message to view the link that was deleted.

**Comment by night** [comment]
Clearly not.. Why don't you disable deleted links, try it out, and then get back to me. We match their functionality, but don't support deleted links....

**Comment by AlmightyZing** [comment]
http://imgur.com/2lCTHxA

This is how Twitch handles deleted links. That is not click-able in any way. There is no possible way to get the underlying link out of that message. Are we not talking about the same functionality in this case?

**Comment by jayman032487** [comment]
Hey there Night,

It seems you're having trouble understanding our concern, so I'll try explaining my point of view. Up until today my channel has just been using native twitch setting to delete links automatically within my chat. This was the setting I chose for how I wanted my channel's chat to operate. Today however, I discover that users of Better Twitch TV do not have these links deleted. This means that without my knowledge you have circumvented my authority over my own channel. So I'm sure there exist other streams that have no idea that their settings do not apply to users of a specific add-on.

**Comment by night** [comment]
We do not care about the Twitch deleted links option, nor will we begin to care about it. The fact was stated earlier:

>  I grew up with IRC communities, and BetterTTV is how I envision improving the onsite chat to be more like a standard IRC client (this includes the inability for a server to remove messages, preventing censoring).

Users are not required to use BetterTTV, and it should not be your concern if users are using it. It's the same difference as users using an IRC client like mIRC. Are you going to go complain over every IRC client because they don't clear chat links?

**Comment by night** [comment]
Also, since you guys don't seem to get that we do match default Twitch functionality with the exception of deleted links:

> Why don't you disable deleted links, try it out, and then get back to me. We match their functionality, but don't support deleted links....

> http://imgur.com/2lCTHxA

Here is Twitch's default functionality:

![](https://nightdev.com/i/ss-8mPZfNqpacI494JdXw2fjW5ie.png)
![](https://nightdev.com/i/ss-hqjK558QWUXvsrE5TtVGs6ezS.png)
clicking "&lt;message deleted>"
![](https://nightdev.com/i/ss-O4qpkPcKs6ZFai6T0cnTOeJnE.png)

It's the same as what BetterTTV does. As was stated, we just don't support Twitch's deleted links functionality.

**Comment by jayman032487** [comment]
"We just don't support Twitch's deleted links functionality."

Well, that's exactly my problem. You don't care that you are letting people bypass a channel owners chosen settings. Channel owners like myself (prior to today) think that is all we need to do to prevent the sharing of unapproved links. We think that we are covered in the event of some troll posting something horribly inappropriate (I have a lot of young viewers...). Now I find out that you provide ways to undermine our authority just because that's what you want to do. That's your vision. Well far be it for me to decide how links should be handled on my channel through native on site settings, Night grew up with IRC and obviously knows best.

I know I can just use bots to moderate for links, and quite frankly I'm now going to have to, but I still question the ethics here as you are providing a back door around a native Twitch setting. How many streamers do you think out there have no idea that their chat is not as secure as they thought it was?

As for complaining about other IRCs, no... I'm not going to complain about other IRCs because they are built to be IRCs. You however are making an add-on specifically targeted at Twitch and have chosen not to support certain aspects of Twitch. Your add-on does improve a lot of things but you break one thing and just don't care. But whatever, "deal with it", right?

**Comment by night** [comment]
> I know I can just use bots to moderate for links, and quite frankly I'm now going to have to, but I still question the ethics here as you are providing a back door around a native Twitch setting.

Ethics does not apply here. If Twitch wanted links filtered from every client regardless of implementation, they would filter them server-side instead of client side (which they already do for their banned words list). Since they are filtered server side, it makes it a client issue on whether or not they should be filtered. And since we don't believe in censorship (except in cases of spam bots), we don't want to support such a terrible feature.

> How many streamers do you think out there have no idea that their chat is not as secure as they thought it was?

What security? [Security by obscurity is not security at all](https://en.wikipedia.org/wiki/Security_through_obscurity). Any user using an IRC client sees the links too. This lack of deleted links is not just for BetterTTV. As was stated already, BetterTTV is an option add-on that users choose to install. Read my previous reply: https://github.com/night/BetterTTV/issues/797#issuecomment-152353454

> As for complaining about other IRCs, no... I'm not going to complain about other IRCs because they are built to be IRCs. You however are making an add-on specifically targeted at Twitch and have chosen not to support certain aspects of Twitch. Your add-on does improve a lot of things but you break one thing and just don't care. But whatever, "deal with it", right?

Nothing is being broken by us not supporting the feature. Most channels on Twitch use bots to filter links. The links still get deleted by properly configured bots. The "deleted links" feature is superfluous in 99% of cases, and the feature itself is terrible and (in my opinion) should be removed in favor of chat bots. You can read my previous reply for why it is so: https://github.com/night/BetterTTV/issues/797#issuecomment-152341007
