### ISSUE TITLE
Notification when someone says something in chat

### ISSUE THREAD

**Issue by anders1122** [night/BetterTTV#808]
Maybe make it auto disable when too many people are there. A notification at the bottom right corner of your screen when you're not on the twitch window.

**Comment by night** [comment]
This isn't something that makes sense to add. It would be incredibly annoying to be notified for every single message. If you want, you can add keywords like "hello" or "hi" to your highlights list in the chat settings if your broadcasting and want to quickly notice people saying hello. Otherwise, it's a better practice to check chat yourself every so often.
