### ISSUE TITLE
Suggestions about Whisper box

### ISSUE THREAD

**Issue by ImJustAnnoyed** [night/BetterTTV#870]
Suggestions for Twitch.tv 's chat section

BTTV emotes to be usable in the new whisper box.

Option to have back the old whisper option in the main chat box. (Mostly because myself and a small portion of people dislike this new box option)

Thanks if you ever consider these (or already have)

**Comment by night** [comment]
> BTTV emotes to be usable in the new whisper box.

We had support for these until Twitch inadvertently broke our implementation, making it now impossible to implement without modifying Twitch's functions (which is against what we're willing to do). We are trying to get support for them again, but I do not have an eta at this time.

> Option to have back the old whisper option in the main chat box. (Mostly because myself and a small portion of people dislike this new box option)

The new implementation is a lot better and brings on-site messaging closer to Facebook-style chat. I believe this is a good direction for Twitch and we support their direction with whispers. My recommendation is to get used to the new system, since the old one will be ripped out by Twitch sometime in the future. The new system is actually a lot more usable, so I'm not particularly sure why people have a distaste for it (unless they are just being resistant to progressive change).

**Comment by ImJustAnnoyed** [comment]
I understand and respect your replies, thanks for reviewing them anyhow!
