### ISSUE TITLE
Can't See Gif Emotes

### ISSUE THREAD

**Issue by jtp5** [night/BetterTTV#911]
For some reason I cannot see the bttv gif emotes. I am sure that the emotes are available in the channel because other people can see them and I do have both bttv emotes and bttv gif emotes enabled in the bttv settings.

**Comment by voloshink** [comment]
what browser are you using and what other addons do you have installed

**Comment by jtp5** [comment]
I am using chrome and I only have bttv, adblock, and oddshot. However I dont think that other addons are the problem because I can see the normal emotes just not the gifs. @voloshink

**Comment by voloshink** [comment]
try without the addons just to make sure?

**Comment by jtp5** [comment]
@voloshink just tried withouth them and it still doesnt work.

**Comment by jtp5** [comment]
any other ides? @voloshink

**Comment by voloshink** [comment]
any bttv related errors you see in the browser console?

**Comment by jtp5** [comment]
@voloshink I dont think so but I cant really tell. You can look at the four "extension" related errors right here http://imgur.com/MjJebkC

**Comment by voloshink** [comment]
Don't see anything bttv related, is the issue happening just in one place?

**Comment by jtp5** [comment]
@voloshink no, they don't work in any channel.

**Comment by voloshink** [comment]
have you tried clearing your cache/cookies?

**Comment by jtp5** [comment]
@voloshink just tried it and of course it made me re enable the gif emotes but it still didnt work :(

**Comment by night** [comment]
If I had to guess, this is because you have the settings set properly on SSL or non-SSL, but not on the other.

Ensure you have the settings for BetterTTV toggled as pictured at both https://www.twitch.tv/jtp5 and http://www.twitch.tv/jtp5: https://nightdev.com/i/ss-YitZuYrgVCQ7MY9MOkYzg2hrR.png 

After checking they are as pictured, refresh all open Twitch pages. Go to a channel like http://www.twitch.tv/jtp5 and type "SourPls" to verify it is working.

**Comment by jtp5** [comment]
@night thank you so much i didnt have it enabled in my channel settings but only in my profile settings. Now it works so thanks a ton.
