### ISSUE TITLE
Possible GPL Licensing Issue

### ISSUE THREAD

**Issue by Martii** [night/BetterTTV#962]
This is partly related to #961... since you currently have [a reference to GPL](https://github.com/night/BetterTTV/blob/190ef3d8fbbc683f80208bc734a89460633f0dbd/betterttv.js#L41) inside your Code you should investigate the requirement of separating out that possible Code, if applicable, into a separate .js module. If it is just referencing an object you import as a module then you really don't need the GPL notice since it's not Code but references that library module. 

Thanks *(this is non-official OUJS business)*... you may be interested in this to avoid someone who may act upon this with a DMCA if applicable.

See also:
* http://www.gnu.org/copyleft/gpl.html

**Comment by night** [comment]
We use the gritter module, but it is nowhere near a major component of our extension. We provide attribution because it's the right thing to do. Since it's a dual license the subject of if it's legal is a grey area. Since we've not have issue in the past 4 years using their library, I'm not sure why we suddenly would have. Our strict license serves to prevent people from doing bad things with our code (which has happened multiple times in the past). If the author wants their module removed we'll take action at that point by replacing it with something else or removing it altogether (use primarily use the HTML5 notification API anyways).

Thanks for sharing your concerns.

**Comment by Martii** [comment]
@night 
You may want to peruse the upstream a little closer... not sure what's going on with that... but once GPL always GPL as it's very black and white in GPL terms and never grey... so you may want to open an upstream issue with your downstream project here to protect your licensing... otherwise you could lose credibility and copyright rights if someone files a DMCA and you have **their Code** in **your Code**... please take this legal information humbly but seriously... I have no desire to investigate this project at this time but there is previous case precedence which can cause a chain reaction of terminations if someone else *(not me because I have no idea what your project does and is in my passing only)* decides to pursue direct or indirect litigation.. this I know from experience with court cases pursued at the Corporate level on other projects over the decades.

Also npmjs.com **could** terminate the [*gritter*](https://www.npmjs.com/package/gritter) package as well, if they so desire, due to conflicting licensing.

* http://www.boedesign.com/ *(currently a dead link domain here)*
* [`8c4722b`/package.json#L34](https://github.com/jboesch/Gritter/blob/8c4722b56755e94209f9dfedeaf12df469a5f5e4/package.json#L34) *(package MIT license only... no reference to GPL)*
* [`30160ee`/js/jquery.gritter.js#L6](https://github.com/jboesch/Gritter/blob/30160eee599a0ca2d115e51454635f2618df6999/js/jquery.gritter.js#L6) *(Initial licensing which does include GPL... that is confusing)*
* https://github.com/jboesch/Gritter/commit/30160eee599a0ca2d115e51454635f2618df6999 *(Initial commit)*

> We provide attribution because it's the right thing to do.

Of  course attribution is... but there are GPL protections in place that must be adhered to. So at the very least I would recommend resolving that in your Code comments... since it's **very unclear upstream**... first step would be to notify those package maintainers and take whatever additional action here *(besides `wontfix` label)* to remedy the situation. :)

Some misc. things related here... hoping to help out only:
* Ignorantia juris non excusat
* nemo censetur ignorare legem
* ignorantia iuris nocet

**Comment by night** [comment]
Look, I don't need a lecture in licensing, nor did I ask you for one. IANAL and we're not a huge company profiting from this fucking extension. Why the fuck would anyone care about us, let alone sue us? Anyways, just to appease you because you're drawing people into a non-issue, the module is removed.

**Comment by Martii** [comment]
Chill out... no need to get irrational... I was trying to help you protect your investment... you made that point in the other issue. I've been in the industry a long time. I understand SOHO quite well and respect it greatly. :)

A simpler solution, which apparently I didn't convey well, would have been to point to the upstreams LICENSE file instead of copying it stock into your code *(assuming you had their code in yours)*... just thought you might be interested in learning something but perhaps I made a mistake.

**Comment by night** [comment]
> protect your investment

LOL, what investment? I run this project in my spare time and generate no profit from it currently. The license serves only to save our users from other people forking my code, distributing it, and charging money for it, which has happened on numerous occasions in the past.

**Comment by Martii** [comment]
You are preaching to the choir here as the saying goes. I have had GPL code sold as well in the *nix tree and commercially without attribution and that wasn't pretty. I am pro-FOSS for sure with strong attribution. So I do understand where you are coming from.

Investments aren't always monetary... they can be in generous time spent as well. I apologize if I upset you... that wasn't anywhere near what I was intending... I am a literal, exacting, and professional type of person and I thought I would share some of that info with you as we started off pretty good.

**Comment by vendethiel** [comment]
You seem to be amazing at circle-jerking, at least.

**Comment by isaacs** [comment]
Hey, all.  Showing up because I was summoned.

I'm not a lawyer.  I'm just a simple service provider, trying to do the right thing.  This is not legal advice, but since the subject was raised about what npm would do, I am qualified to speak on that.

If the owner of gritter complains about copyright violations, we'll have our lawyer look at it, and probably do what our lawyer says (since that's the kind of thing we pay lawyers for).

From what I can tell, gritter is dual-licensed as MIT and GPL.  **As a developer**, what I **personally** try to do in dual-licensing situations is make it clear specifically which license I am using the project under.  If you want to use gritter, and do the things that the MIT license gives you rights to do, then I'd make it clear that you're taking advantage of the MIT license to gritter.

The MIT license says you have the right to sublicense, so long as you include attribution.  If you're doing it because it's the right thing to do, ok, that's probably fine, too.  But again, if the gritter author sees it differently, and complains, we'll have a lawyer take a look, and it may end up going a different way.  Who knows.  I'm not a legal expert with experience in such things, so not me.  DMCA says that we *must* take it down when we get a valid complaint, but also that you have time to counter-claim, and so on.

I'm not a participant on this repo or a user of this module.  I have no dog in this fight.  But *probably* you all would have better results by being courteous, rather than cursing and being vulgar to someone who, right or wrong, appears to be trying to help you out.
