### ISSUE TITLE
That timeout button doe

### ISSUE THREAD

**Issue by vivimusprime** [night/BetterTTV#968]
If we had a setting to change the default timeout button to a purge button that would be great!

**Comment by night** [comment]
You can right click on names for better timeout options already..

**Comment by vivimusprime** [comment]
I meant the button the shows up on the left of the name...instead of the automatic 10 minute timeout have it just purge. Or the option to change it to purge. I don't time people out for 10 minutes very often, I purge a lot...

**Comment by voloshink** [comment]
why not just use the hotkeys

**Comment by vivimusprime** [comment]
If I give a suggestion it's not because it needs to be implemented, it's not because there isn't other options, it's because I believe this feature may make what you have a little bit better. I could be entirely wrong, that is up to you to decide. It is solely based on my experience and what would work better for me for ease of use and to improve reaction times to purging content instead of making multiple clicks, that doesn't mean it will work better for everyone and could be entirely not viable as an option.

A simple "Thank you for your suggestion, we will look into it in the future! There are currently a few features that allow you to purge within BTTV *list them*." would have sufficed as an answer.

But thank you for your suggestions! Thank you Night for telling Klause that my setting was on for shift click and not right click, I really like the slider feature. And yes Voloshink there are hotkey options, it's for ease of use and reaction times to purging content, I do currently use the hotkeys, though after Night's suggestions I think I will switch to the slider.

I hope you both have a lovely day. <---actually, not sarcasm.

**Comment by HelmicNewciv** [comment]
Yeah, I don't want to use a hotkey.  I don't want to carefully navigate that in a fast-flowing chat and hope I got the right person.  I want to click an icon next to the offending message and make that message go away.

Being able to set how long the timeout button times people out should be an option.  It doesn't take up any extra screen space, it allows chats with special rules to more easily enforce them (30 minute bans by default instead of 10, or 1 minute bans as a warning, or in the case of most smaller channels just 1 second to clear spoilers).  It's a shitton more touch friendly for those of us that aren't using a physical keyboard or are using a laptop (just tap the icon and the message is gone).  There's already lots of fiddly options in the options menu, I don't see why a little toggle for how the timeout button behaves would be too much.

And in general, a single click is way more convenient than a click and a keyboard shortcut, or a click and manipulating a slider and hoping that the slider loads quickly enough to avoid accidentally giving someone an hour-long timeout.
