### ISSUE TITLE
A possible fix for the notification popup 

### ISSUE THREAD

**Issue by forkthiscode** [night/BetterTTV#970]
After noticing the follower notification popup on the top left was removed I found out it was due to persistent individuals I found 2 replacements that might work as a replacement for the awful Twitch notify thing.   http://ksylvest.github.io/jquery-growl/ and https://notifyjs.com/ I hope you find one of these acceptable to include in BTTV and restore the wonderful popup in the top left

**Comment by night** [comment]
For the time being we're happy with the center bottom popup as a replacement. Since it doesn't stack notifications, automatically disappears, and is in a more prominent location it seems it might be a better solution. If we get more enough feedback stating that people are not happy with the new change, we'll consider changing it. It seems thus far that people are now at least noticing it more than they used it, which is great when people actually want to be notified when someone they follow goes live.
