### ISSUE TITLE
Name Colors and Highlights Mk II

### ISSUE THREAD

**Issue by Vendy13** [night/BetterTTV#985]
Hello Again!

I was unsure if you'd see the comment I wrote on my old post since you closed it, so I thought it may be best to open a new one.

I'm not sure if your reply was intended to sound as harsh as it came off, so I'll assume it wasn't meant to be. My post wasn't meant to sound like complaints but rather suggestions (as it was the "Send in a feature request" link that brought me here in the first place).

I was simply suggesting the options be there, such as the option to change the highlight color, nothing more. I didn't intend to make it sound like I was trying to change things; I realize I very well could be the only one with these preferences. I honestly was just offering ideas for more customization, since I thought that was a big part of BetterTTV. I hope that clears things up! :)

**Comment by MellowNebula** [comment]
Night's response was saintly. 
It was informative, honest, forthright and he provided very clear reasoning for declining. Frankly, with the amount of shit he's dealt with over the years, his responses are often far more generous than mine would be if I was in his shoes.

There's really no need to open a new issue for something like this. Your suggestion got shot down, thanks for contributing, it's nothing personal.

**Comment by Vendy13** [comment]
I can understand that there's probably a slew of people/customers that are difficult to deal with, whether intentionally or unintentionally. However, his response was just a bit odd to me considering I was sent here by the "Send in a feature request" link. Yes I agree it explained why he doesn't see it as an issue, but the extension literally asks for suggestions. I wouldn't have opened anything new had my other thread not been closed without my being able to comment again. I simply wished to explain that I wasn't trying to complain, and make sure there were no hostilities between us.

**Comment by MellowNebula** [comment]
For future reference, you can comment on closed issues. Although I wouldn't recommend doing so unless you actually have something relevant to the issue to add.

**Comment by Vendy13** [comment]
I saw that I could, however I wasn't sure to what effect it would have (i.e. if it would actually be seen or not). Thank you for letting me know.

**Comment by Vendy13** [comment]
Also, apparently FrankerFaceZ has everything I suggested PLUS some other things BTTV is missing. So, take what you will from that, but I'll just say it may be a smart move to consider having some things that your competition already has.

**Comment by night** [comment]
The problem with FrankerFaceZ is that it's succumb to what is known in the industry as feature creep. It isn't feasible to make everything in a product user configurable nor is it feasible to add every idea that gets suggested. While we understand that, they do not and users generally do not. We can only make changes that make sense and would be targeting the majority of our users. If you'd rather use their extension, then by all means you're welcome to. We would rather not clutter and overcomplicate our codebase to "compete" with that.

I apologize if you thought my initial reply was rude. I do not sugar coat responses typically, so you get facts instead of fluff.

For future reference, you can reply to closed issues. Unfortunately GitHub does not make this clear enough to users.
